dpnp/backend.pxd
dpnp/backend.pyx
dpnp/backend/backend_iface.hpp
dpnp/backend/custom_kernels.cpp
dpnp/backend_sorting.pyx
dpnp/dparray.pyx
dpnp/dpnp_iface.py
dpnp/dpnp_iface_sorting.py
tests/third_party/cupy/sorting_tests/test_count.py
tests/third_party/cupy/sorting_tests/test_search.py
tests/third_party/cupy/sorting_tests/test_sort.py
tests/third_party/cupy/testing/__init__.py

We discussed possibility to reuse sorting functionality.
So I added another func with it using to have more examples.
All tests from sorting are added.
+12 passed

Sorting funcs

---

dpnp/backend.pyx
dpnp/backend_counting.pyx
dpnp/dpnp_iface.py
dpnp/dpnp_iface_counting.py
tests/test_counting.py

cupy tests need support of bool type

count_nonzero func and tests

---

dpnp/backend.pyx
dpnp/backend_linearalgebra.pyx
dpnp/dpnp_iface_linearalgebra.py
tests/skipped_tests.tbl

- C++ backend kernel in stage2
- move dpnp_dot from `backend.pyx` in stage 1.5
+2 test passed

outer() function implementation stage 1

---

dpnp/backend.pyx
dpnp/backend_linearalgebra.pyx

No code changes. Just move sources.
This PR is related to #30

Move Dot() to backend_linearalgebra.pyx

---

MANIFEST.in
setup.py

It is not the only one way to add files, but I hope that this manifest will be useful in future.
Looks like that a lot of projects use such approach.

MANIFEST.in and additional files in package

---

dpnp/backend_statistics.pyx
dpnp/dpnp_iface_statistics.py
tests/skipped_tests.tbl

average func

---

dpnp/random/__init__.py
dpnp/random/_random.pyx

* sort functions in alphabetical order

refactor: random module

---

dpnp/random/_random.pyx

* using dpnp util funcs for raising error

refactor: random module error handling

---

dpnp/backend/backend_iface.hpp
dpnp/backend/mkl_wrap_rng.cpp
dpnp/random/_random.pyx

* renamed `mkl_rng_uniform_mt19937` to `mkl_rng_uniform`
* removed original `mkl_rng_uniform`
* update `dpnp/random/_random.pyx`

refactor: update random module backend funcs

---

dpnp/backend.pxd
dpnp/backend/backend_iface_fptr.cpp
dpnp/backend/backend_iface_fptr.hpp
dpnp/backend_mathematical.pyx
tests/skipped_tests.tbl

Skipped one test because type `bool` isn't supported.

Move math mapping to native code

---

dpnp/backend/backend_pstl.hpp
setup.py
utils/command_build_clib.py

issue 87. debug and release configurations are implemented by environment flag control

---

dpnp/backend/custom_kernels_reduction.cpp
dpnp/backend/custom_kernels_statistics.cpp
dpnp/backend/mkl_wrap_blas1.cpp
dpnp/backend/mkl_wrap_blas3.cpp
dpnp/backend/mkl_wrap_lapack.cpp
dpnp/backend/mkl_wrap_rng.cpp
dpnp/dpnp_iface_statistics.py
setup.py

it is quite strange - dpnp failed with no "mkl_rt" linked. We do not use any functionality from it at this moment.

Zero len addressed. some cleanups

---

dpnp/backend/custom_kernels.cpp
dpnp/backend/custom_kernels_elemwise.cpp
dpnp/backend/custom_kernels_manipulation.cpp
dpnp/backend/custom_kernels_mathematical.cpp
dpnp/backend/custom_kernels_reduction.cpp
dpnp/backend/custom_kernels_searching.cpp
dpnp/backend/custom_kernels_sorting.cpp
dpnp/backend/custom_kernels_statistics.cpp
dpnp/backend/mkl_wrap_lapack.cpp
dpnp/backend/mkl_wrap_rng.cpp
dpnp/backend/queue_sycl.hpp

Move MKL and PSTL headers into one place

MKL and PSTL headers refactoring

---

setup.py
utils/dpnp_build_utils.py

Tested on branch `feature/find_mkl2` checked out from old `master` (https://github.com/IntelPython/dpnp/compare/master...feature/find_mkl2).

Move search for MKL from setup.py

---

dpnp/random/__init__.py
dpnp/random/_random.pyx
dpnp/random/dpnp_iface_random.py
dpnp/random/random_iface.py
tests/test_random.py

* added python layer for `random` module
* moved python declared funcs to python srcs

REFACTOR: added python layer for random module

---

dpnp/backend/backend_fptr.hpp
dpnp/backend/backend_iface.hpp
dpnp/backend/backend_iface_fptr.cpp
dpnp/backend/mkl_wrap_rng.cpp
dpnp/random/_random.pyx

* enhaced `mkl_rng_gaussian` function signature

ENH: enhaced mkl_rng_gaussian function signature

---

conda-recipe/meta.yaml

PR is created in purpose to test work with internal CI.

GIT_DESCRIBE_TAG, GIT_DESCRIBE_NUMBER in meta.yaml

---

tests/skipped_tests.tbl
tests/third_party/cupy/random_tests/test_distributions.py

* test cases for random distribution funcs
* still have:
```bash
AttributeError: module 'dpnp' has no attribute 'testing'
``` 
unlike `tests/third_party/cupy/random_tests/test_sample.py `

TEST: added cupy test cases for random distribution funcs 

---

tests/config/deselect_random_sample.yaml
tests/skipped_tests.tbl
tests/third_party/cupy/random_tests/test_distributions.py

* fixed importing modules and disabled some tests for distributions (`random` modlue)

TEST: fixed importing modules and disabled some tests

---

dpnp/backend/custom_kernels_random.cpp
dpnp/random/_random.pyx
dpnp/random/dpnp_iface_random.py

* moved  displacement `a` param setting into backend func for `random.exponential`

FIX: update `random.exponential`

---

setup.py

Pay attention, that `_project_cmplr_flag_lib` is moved from `linker` to `extra_link_postargs` in backend lib configuration.

SDL checks

---

tests/conftest.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

* added `tests/skipped_tests_gpu.tbl` for functionality, where only `gpu` device is not supported, but `cpu` and `host` is OK

TEST: update tests configuration

---

tests/skipped_tests_gpu.tbl
tests/test_random.py

* fix typo
* renamed test suits
* in alphabetical order.

TEST: refactor tests/test_random.py

---

dpnp/backend/backend_iface_fptr.hpp
setup.py

Previous part of changes was done during adding of SDL flags in https://github.com/IntelPython/dpnp/pull/178.
For now we work with activation of oneAPI beta10 environment.

build on windows part 1

---

utils/dpnp_coverage.py

initial version of function coverage in the module

---

dpnp/backend.pyx
dpnp/backend_arraycreation.pyx
dpnp/backend_statistics.pyx
dpnp/dpnp_iface_arraycreation.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/test_arraycreation.py
tests/third_party/cupy/creation_tests/test_ranges.py

+28 passed tests from cupy
+48 own tests
Unexpected fails of tests on GPU are detected, issue is created:
https://github.com/IntelPython/dpnp/issues/228

Funcs geomspace linspace logspace

---

conda-recipe/build.sh
conda-recipe/meta.yaml

- Add wheel build to build command
- Copy created package to WHEELS_OUTPUT_FOLDER if it defined

[WIP] Add wheels build

---

dpnp/dpnp_iface_mathematical.py
dpnp/dpnp_iface_trigonometric.py

Enable links to `numpy` for `ufuncs`.

DOCS enable links to numpy

---

dpnp/random/dpnp_iface_random.py

This is correct solution for #244 
@samir-nasibli Please use same approach for all iface functions in RNG

add execution queue check

---

dpnp/random/_random.pyx
dpnp/random/dpnp_iface_random.py

REF: random functions in alphabet order

---

dpnp/backend.pyx
dpnp/backend_indexing.pyx
dpnp/dpnp_iface.py
dpnp/dpnp_iface_indexing.py
dpnp/dpnp_utils.pxd
dpnp/dpnp_utils.pyx
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

source file for indexing routines
nonzero function implementation
+3 passed tests

Indexing funcs nonzero

---

dpnp/random/dpnp_iface_random.py

* docstrings for `random.standard_exponential`
* block `limitations` for this function and for other random module funcs will be added later on other PRs.

DOCS: docstrings for `random.standard_exponential`

---

dpnp/random/dpnp_iface_random.py

deprecate using dpnp own exception handlers/raise

DEP: update `random.seed` exception handler

---

dpnp/backend/backend_iface.hpp
dpnp/random/_random.pyx

* cython level random function in alphabet order

REF: align in alphabet order cython level and backend function for `random.normal`

---

dpnp/backend/backend_iface.hpp

FIX: `random.multinomial` backend func declaration

---

dpnp/random/dpnp_iface_random.py

choice(a[, size, replace, p]) Generates a random sample from a given 1-D array
calls `numpy.random.choice` on the backend.

ENH: `random.choice`, numpy call

---

dpnp/random/dpnp_iface_random.py

* dirichlet(alpha[, size]) Draw samples from the Dirichlet distribution.
* f(dfnum, dfden[, size]) Draw samples from an F distribution.
* logistic([loc, scale, size]) Draw samples from a logistic distribution.
* logseries(p[, size]) Draw samples from a logarithmic series distribution.
* noncentral_chisquare(df, nonc[, size]) Draw samples from a noncentral chi-square distribution.
functions  uses `numpy` on the backend

ENH: random distributions funcs, numpy call, [1/3]

---

doc/conf.py
dpnp/backend/backend_iface.hpp
dpnp/backend/custom_kernels_random.cpp
dpnp/backend_arraycreation.pyx
dpnp/dpnp_iface_arraycreation.py
dpnp/dpnp_iface_linearalgebra.py
dpnp/dpnp_iface_statistics.py
dpnp/random/_random.pyx
tests/third_party/cupy/creation_tests/test_matrix.py

+58 passed tests
0 skipped tests

diag, digflat, tri, tril, triu funcs

---

dpnp/fft/dpnp_iface_fft.py
tests/skipped_tests.tbl
tests/third_party/cupy/fft_tests/test_fft.py

Tests fixed due to difference in return types between numpy and cupy

FFT. add API functions for ifft and irfft sets

---

tests/skipped_tests_gpu.tbl

enabled GPU tests for #332 (missed on #333)

TEST: enabled GPU tests due to PR332 changes

---

dpnp/backend_arraycreation.pyx
dpnp/dpnp_iface_arraycreation.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

+16 passed tests
arange tests are also unskipped

Meshgrid func

---

dpnp/backend_indexing.pyx
dpnp/dpnp_iface_indexing.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/third_party/cupy/indexing_tests/test_generate.py
tests/third_party/cupy/indexing_tests/test_indexing.py
tests/third_party/cupy/indexing_tests/test_insert.py
tests/third_party/cupy/indexing_tests/test_iterate.py
tests/third_party/cupy/testing/__init__.py

indexing ops: diag indices

---

dpnp/random/dpnp_iface_random.py

fix fallback on numpy, add check for params of distribution

FIX: `random.beta` fallback

---

dpnp/random/dpnp_iface_random.py

* update fallback
* update docstring

FIX: random.chisquare fallback

---

dpnp/random/dpnp_iface_random.py

Removed size assignee on random funcs level, when given size is default value(`None`)

DEP: removed removed size assigne on random funcs level

---

dpnp/dpnp_iface_arraycreation.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

mgrid ogrid classes

---

tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/test_random.py

* redesign `test_randn_normal_distribution` enabled it for check

TEST: redesign `test_randn_normal_distribution`

---

setup.py

DEP: changed deprecated dpctl lib name

---

tests/test_random.py

* `*_check_moments()` test suits

REF: refactor `tests/test_random.py`

---

conda-recipe/meta.yaml
scripts/azure-pipelines.yml
scripts/build_deps_dpctl.sh

ci improvements

---

tests/test_random.py

tests for `random.uniform`
will be redesign after #397 merge/

TEST: added tests for random.uniform distr

---

dpnp/random/dpnp_iface_random.py

* update fallback `random.rand` and align docstring with templates

ENH: update fallback `random.rand` and align docstring with templates

---

dpnp/random/dpnp_iface_random.py

* removed unnecessary  non-negative check on `loc` param

FIX: removed unnecessary check

---

dpnp/random/dpnp_iface_random.py

* misc. fixes random docstrings

DOC: misc. fixes random docstrings

---

dpnp/random/dpnp_iface_random.py

* align docstring with templates for `random.random_sample`

DOC: align docstring with templates for `random.random_sample`

---

dpnp/random/dpnp_iface_random.py

* align docstring with templates for `random.ranf`

DOC: align docstring with templates for `random.ranf`

---

dpnp/random/dpnp_iface_random.py
tests/skipped_tests_gpu.tbl

Update `random.multivariate_normal` python level:
* update python level
* align with template docstring
* fix fallback
* enabled tests

ENH: update `random.multivariate_normal` python level

---

tests/skipped_tests_gpu.tbl

* removed unnecessary tests cases from skip list.

DEP: removed deprecated tests from skip list

---

dpnp/random/_random.pyx
dpnp/random/dpnp_iface_random.py
tests/skipped_tests_gpu.tbl
tests/test_random.py

* update python level
* align with template docstring
* fix fallback
* enabled tests

ENH: update `random.multinomial` python level

---

dpnp/random/dpnp_iface_random.py
tests/skipped_tests_gpu.tbl

* fix reseeding for functions, that will fallback (simple solution)
* ++9 removed test cases form skip list

FIX: reseeding for future fallbacks

---

dpnp/random/dpnp_iface_random.py

* update fallback `random.random_integers` and align docstring with templates

ENH: update fallback random.random_integers and align docstring

---

.github/workflows/build-sphinx.yml

Try to add cuPy for "comparison table" third column

Install cuPy for documentation build

---

dpnp/backend_mathematical.pyx
dpnp/dparray.pyx
dpnp/dpnp_iface_mathematical.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/third_party/cupy/core_tests/test_ndarray_math.py
tests/third_party/cupy/testing/__init__.py

round funcs

---

dpnp/backend/examples/example7.cpp
dpnp/backend/examples/example8.cpp
dpnp/backend/examples/example9.cpp
dpnp/backend/include/dpnp_gen_1arg_1type_tbl.hpp
dpnp/backend/include/dpnp_gen_1arg_2type_tbl.hpp
dpnp/backend/include/dpnp_gen_2arg_1type_tbl.hpp
dpnp/backend/include/dpnp_gen_2arg_3type_tbl.hpp
dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/kernels/dpnp_krnl_bitwise.cpp
dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
dpnp/backend/kernels/dpnp_krnl_linalg.cpp
dpnp/backend/kernels/dpnp_krnl_manipulation.cpp
dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
dpnp/backend/kernels/dpnp_krnl_reduction.cpp
dpnp/backend/kernels/dpnp_krnl_searching.cpp
dpnp/backend/kernels/dpnp_krnl_sorting.cpp
dpnp/backend/kernels/dpnp_krnl_statistics.cpp
dpnp/backend/src/dpnp_iface_fptr.cpp
dpnp/backend/src/queue_sycl.cpp

style will be applied later to keep this PR clear

Rename custom_ to dpnp_ and macro

---

setup.py
utils/command_build_cmake_clib.py

make common kwargs for all modules. The idea gathered from `dpctl` package

common kwargs and style

---

scripts/azure-pipelines.yml

disable external testing

---

dpnp/backend/kernels/dpnp_krnl_random.cpp

Added missed exception raise in `dpnp_rng_multivariate_normal_c`

Added exception raise in `multivariate_normal`

---

dpnp/backend/tests/test_random.cpp

* backend tests based on gtest
* gtest will be added to cmake on other PR
* refactoring: main into test_main.cpp

TEST: added tests for backend random

---

tests/tests_perf/math_tests/test_black_scholes.py
tests/tests_perf/test_perf_base.py

`DPNP_QUEUE_GPU=1 pytest tests/tests_perf/math_tests/test_black_scholes.py -s`

TESTS PERF add black scholes test

---

conda-recipe/build.sh

- Use manylinux1 for Python 3.6
- Use manylinux2014 for Python > 3.6

[WIP] Update linux build tah for wheels

---

dpnp/backend/kernels/dpnp_krnl_random.cpp
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

fix and closes #256 
* vector-scalar multiply by OneMLK i kernel

FIX: rayleigh dist

---

dpnp/backend/include/dpnp_iface.hpp

* aligned docstrings in dpnp_iface.hpp -> google style [Doxygen]

REFACTOR: aligned docstrings in dpnp_iface.hpp

---

dpnp/backend/CMakeLists.txt
dpnp/backend/tests/CMakeLists.txt
scripts/install_system_deps.sh
utils/command_build_cmake_clib.py

Added using Google Test
* add test_run.sh

DEV: cmake for gtest

---

dpnp/backend/include/dpnp_iface_random.hpp
dpnp/backend/kernels/dpnp_krnl_random.cpp
dpnp/random/dpnp_algo_random.pyx

* added missed `const` declarations
* change in alphabetic order
* renamed backend `chi_square` backend func to `chisquare` (like on python API)

REFACTOR: refactor `random` backend srcs

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/include/dpnp_iface_random.hpp
dpnp/backend/kernels/dpnp_krnl_indexing.cpp
dpnp/backend/kernels/dpnp_krnl_random.cpp
dpnp/backend/tests/test_random.cpp
dpnp/dpnp_algo/dpnp_algo_mathematical.pyx
dpnp/dpnp_iface_mathematical.py
tests/test_special.py

please use `python ./setup.py style -a` before commit

style 30Jan2021

---

scripts/build_deps_dpctl_win.bat

try to find a `rm -rf dpctl` analog on windows cmd

remove directories in addition to files deletion on windows

---

tests/skipped_tests_gpu.tbl

https://github.com/IntelPython/dpnp/issues/563

skip GPU tests for dot func until it is not fixed

---

tests/skipped_tests_gpu.tbl

https://github.com/IntelPython/dpnp/issues/565

skip GPU tests for cov and correlate funcs until they are not fixed

---

tests/skipped_tests_gpu.tbl

https://github.com/IntelPython/dpnp/issues/569

skip GPU tests for Gumbel distribution until it is not fixed

---

dpnp/backend/kernels/dpnp_krnl_random.cpp
tests/skipped_tests_gpu.tbl

* fix `random.gumbel` segfault on GPU
temporary solution for #569

FIX: random.gumbel segfault on GPU

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/kernels/dpnp_krnl_manipulation.cpp
dpnp/dpnp_algo/dpnp_algo_manipulation.pyx

Interface changes vectors -> pointers

Transpose refactoring

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/kernels/dpnp_krnl_indexing.cpp
dpnp/dparray.pyx
dpnp/dpnp_algo/dpnp_algo_indexing.pyx
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

Take func kernel

---

dpnp/backend/src/dpnp_iterator.hpp
dpnp/backend/tests/CMakeLists.txt
dpnp/backend/tests/test_utils_iterator.cpp

To continue work started by @Alexander-Makaryev 
this is initial code. a lot of things need to be added.
- iterator tests (std::vector::iterator like)
- algorithm tests with corner cases check
- algorithms check with error handling
- tests with diffrent types
and much more
will be addressed by next PRs. This PR is complete.

SYCL USM iterator with axis support plus few tests

---

tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl

`sort -u` to both files applied

sort skipped tests files

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/include/dpnp_iface_fptr.hpp
dpnp/backend/kernels/dpnp_krnl_indexing.cpp
dpnp/dpnp_algo/dpnp_algo.pxd
dpnp/dpnp_algo/dpnp_algo_indexing.pyx
dpnp/dpnp_iface_indexing.py
tests/test_indexing.py

tests:
test_put_along_axis_val_int
test_put_along_axis1
test_put_along_axis2

Native put along axis

---

conda-recipe/meta.yaml

Seems we need Todd's approve before merge the PR.

Support MLK 2021.2.0

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/include/dpnp_iface_fptr.hpp
dpnp/backend/kernels/dpnp_krnl_logic.cpp
dpnp/dpnp_algo/dpnp_algo.pxd
dpnp/dpnp_algo/dpnp_algo_logic.pyx
dpnp/dpnp_iface_logic.py

tests/test_logic.py::test_any[(4,)-float64]
tests/test_logic.py::test_any[(4,)-float32]
tests/test_logic.py::test_any[(4,)-int64]
tests/test_logic.py::test_any[(4,)-int32]
tests/test_logic.py::test_any[(4,)-bool] 
tests/test_logic.py::test_any[(4,)-bool_]
tests/test_logic.py::test_any[(2,3)-float64]
tests/test_logic.py::test_any[(2,3)-float32]
tests/test_logic.py::test_any[(2,3)-int64]
tests/test_logic.py::test_any[(2,3)-int32]
tests/test_logic.py::test_any[(2,3)-bool] 
tests/test_logic.py::test_any[(2,3)-bool_]
tests/test_logic.py::test_any[(2,2,2)-float64]
tests/test_logic.py::test_any[(2,2,2)-float32]
tests/test_logic.py::test_any[(2,2,2)-int64] 
tests/test_logic.py::test_any[(2,2,2)-int32] 
tests/test_logic.py::test_any[(2,2,2)-bool] 
tests/test_logic.py::test_any[(2,2,2)-bool_]

native version dpnp.any()

---

setup.py

For wheels due to issue while uploading:
Invalid value for classifiers. Error: Classifier 'Development Status :: 0 - Alpha' is not a valid classifier.

Update development status to Beta

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/kernels/dpnp_krnl_sorting.cpp
dpnp/dpnp_algo/dpnp_algo_sorting.pyx

test DPNP_QUEUE_GPU=1 pytest "tests/test_sort.py::test_partition[[3, 4, 2, 1]-float64-0]" was aborted on GPU. In this PR bag was fixed.

Fix partition

---

doc/conf.py
dpnp/backend/CMakeLists.txt
dpnp/backend/doc/Doxyfile
dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/include/dpnp_iface_fptr.hpp
dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
dpnp/backend/kernels/dpnp_krnl_random.cpp
dpnp/backend/src/queue_sycl.cpp
dpnp/dpnp_algo/dpnp_algo.pxd
dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
dpnp/dpnp_iface_arraycreation.py
dpnp/random/dpnp_algo_random.pyx
dpnp/version.py
scripts/azure-pipelines.yml
scripts/install_python_deps.sh
tests/conftest.py
tests/test_arraycreation.py
tests_external/skipped_tests_numpy.tbl

Reverts IntelPython/dpnp#705
Looks like the PR was squashed and merged, but we need to merge it w/o squash.

Revert "Merge master to gold"

---

dpnp/backend/kernels/dpnp_krnl_random.cpp
dpnp/random/dpnp_algo_random.pyx

ENH: misc update; `random.weibull`

---

scripts/azure-pipelines.yml

Need to move these tests to NumPy 1.20 version

Temporarily disable external tests

---

dpnp/dpnp_iface_types.py
tests/third_party/numpy_ext/__init__.py
tests_external/numpy/runtests.py

This is not a type implementation.
This is forward declaration for types to allow external tests.
Also, cleared preparation procedure for such tests

Forward types declarations for external tests

---

dpnp/dpnp_iface.py
dpnp/dpnp_iface_linearalgebra.py

Move matmul to linalg py module

---

benchmarks/pytest_benchmark/README.md
benchmarks/pytest_benchmark/test_random.py

test cases for pytest-benchmark

ENH: added pytest benchmark tests; initial

---

dpnp/dpnp_algo/dpnp_algo.pyx
dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
dpnp/dpnp_algo/dpnp_algo_bitwise.pyx
dpnp/dpnp_algo/dpnp_algo_counting.pyx
dpnp/dpnp_algo/dpnp_algo_indexing.pyx
dpnp/dpnp_algo/dpnp_algo_linearalgebra.pyx
dpnp/dpnp_algo/dpnp_algo_logic.pyx
dpnp/dpnp_algo/dpnp_algo_manipulation.pyx
dpnp/dpnp_algo/dpnp_algo_mathematical.pyx
dpnp/dpnp_algo/dpnp_algo_searching.pyx
dpnp/dpnp_algo/dpnp_algo_sorting.pyx
dpnp/dpnp_algo/dpnp_algo_special.pyx
dpnp/dpnp_algo/dpnp_algo_statistics.pyx
dpnp/dpnp_algo/dpnp_algo_trigonometric.pyx

All these files are "include" files into one module "algo".
I didn't find a method how to make one Cython module with many object pyx files - so, "include" used (not the best solution)

algo module. optimize imports a bit

---

dpnp/dpnp_algo/dpnp_algo.pyx
dpnp/dpnp_algo/dpnp_algo_linearalgebra.pyx

No code changes.
Just move function.

Move dpnp_matmul() to right place

---

dpnp/dpnp_iface_manipulation.py

Python API calls for `hstack`, `stack`, `vstack`; numpy fallbacks
* TODO: fix numpy external tests + enable test cases for array manipulation module

ENH: python API funcs for `hstack`, `stack`, `vstack`; fallbacks

---

dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp

Misc. refactoring `trace`
* will be optimized

MAINT: misc refactoring `trace`

---

tests/test_mathematical.py

MAINT: refactor `tests/test_mathematical.py`

---

dpnp/random/dpnp_algo_random.pyx
dpnp/random/dpnp_iface_random.py

RNG to desc 3

---

dpnp/dpnp_algo/dpnp_algo.pxd
dpnp/dpnp_algo/dpnp_algo.pyx
dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
dpnp/dpnp_algo/dpnp_algo_indexing.pyx
dpnp/dpnp_algo/dpnp_algo_linearalgebra.pyx
dpnp/dpnp_algo/dpnp_algo_manipulation.pyx
dpnp/dpnp_algo/dpnp_algo_mathematical.pyx
dpnp/dpnp_algo/dpnp_algo_sorting.pyx
dpnp/dpnp_algo/dpnp_algo_statistics.pyx
dpnp/dpnp_utils/dpnp_algo_utils.pxd
dpnp/dpnp_utils/dpnp_algo_utils.pyx
dpnp/fft/dpnp_algo_fft.pyx
dpnp/linalg/dpnp_algo_linalg.pyx
dpnp/linalg/dpnp_iface_linalg.py
dpnp/random/dpnp_algo_random.pyx

@Alexander-Makaryev @densmirn @samir-nasibli @KsanaKozlova @LukichevaPolina
Please note these changes
This is just replacement `dparray_shape_type` with `shape_type_c`
nothing else

Replace dparray shape type

---

dpnp/backend/kernels/dpnp_krnl_statistics.cpp
dpnp/dpnp_iface_statistics.py

Reverts IntelPython/dpnp#828 to check internal CI testing.

Revert "Fix issue discovered by test tests/test_statistics.py"

---

dpnp/random/dpnp_algo_random.pyx
dpnp/random/dpnp_iface_random.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/test_random.py

rng shuffle to desc

---

dpnp/config.py
dpnp/dpnp_utils/dpnp_algo_utils.pxd
dpnp/dpnp_utils/dpnp_algo_utils.pyx

Many tests are passed with command
`DPNP_OUTPUT_NUMPY=1 pytest
`
on CPU

Add NumPy.ndarray as return type

---

dpnp/config.py
dpnp/dpnp_utils/dpnp_algo_utils.pyx

Using DPCTL data container, test system status
`====== 2699 failed, 8163 passed, 1191 skipped, 2 xfailed in 349.75s (0:05:49) ======
`

DPCTL data container initial usage implementation

---

dpnp/dpnp_algo/dpnp_algo.pyx
dpnp/dpnp_algo/dpnp_algo_mathematical.pyx
dpnp/dpnp_iface_mathematical.py
tests/test_mathematical.py

algo module free of dparray

---

dpnp/dpnp_iface_mathematical.py

TODO address case where "out_desc" is False

Handling 'out' parameter in math mod

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/kernels/dpnp_krnl_indexing.cpp
dpnp/dpnp_algo/dpnp_algo_indexing.pyx

**DPNPC API changed!**
I didn't find acceptable method to calculate array sizes properly.

use sycl_adapter in krnl_indexing

---

dpnp/backend/include/dpnp_iface.hpp
dpnp/backend/kernels/dpnp_krnl_statistics.cpp
dpnp/dpnp_algo/dpnp_algo_statistics.pyx

**DPNPC API changed!**
I didn't find acceptable method to calculate array sizes properly.

use sycl_adapter in krnl_statistics

---

utils/command_build_clib.py

fix TBB issue on release branch

---

tests/test_histograms.py

fix `IndexError: tuple index out of range` in `tests/test_histograms.py`

BUG: fix test_histograms.py

---

dpnp/backend/kernels/dpnp_krnl_common.cpp
dpnp/backend/kernels/dpnp_krnl_statistics.cpp
dpnp/backend/src/dpnp_utils.hpp
dpnp/dpnp_algo/dpnp_algo_linearalgebra.pyx
dpnp/dpnp_iface_linearalgebra.py

Using of cl::sycl::reduction requires compiler version 2021.4

dot func with strides impl

---

dpnp/dpnp_iface_indexing.py
dpnp/dpnp_utils/dpnp_algo_utils.pyx

Fix "Arrays are not equal" part 2

---

dpnp/dpnp_algo/dpnp_algo_mathematical.pyx
dpnp/dpnp_iface.py

Replaced `.item(i+1)` with use of slice and multi-indexes to iterative over elements.

fix diff function

---

dpnp/dpnp_array.py

fixes https://github.com/IntelPython/dpnp/issues/1103

__neg__ (unary -) for array

---

README.md

fixes https://github.com/IntelPython/dpnp/issues/1100

fix typo in readme.md with pypi installation

---

dpnp/backend/CMakeLists.txt
utils/command_build_clib.py

Modified `build_clib` step to apply `-fno-approx-func`.

Cmake cleanup

---

dpnp/backend/CMakeLists.txt
utils/command_build_clib.py

Cmake cleanup master

---

.github/workflows/conda-package.yml

Using conda-incubator, the hunch is that we must activate conda environment before we can use it.

attempt to fix upload steps of the workflow on Linux

---

doc/conf.py
dpnp/backend/CMakeLists.txt
dpnp/backend/doc/Doxyfile
dpnp/version.py

Out of cycle release to distribute the fix of #1192 for dpnp.erf.

Setting version to 0.10.2

---

doc/conf.py
dpnp/backend/CMakeLists.txt
dpnp/backend/doc/Doxyfile
dpnp/version.py

Out of cycle release to distribute the fix of #1210 to intel channel on Anaconda.

Setting version to 0.10.3

---

.github/workflows/conda-package.yml
doc/conf.py
dpnp/backend/CMakeLists.txt
dpnp/backend/doc/Doxyfile
dpnp/backend/include/dpnp_iface_fptr.hpp
dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
dpnp/dparray.pyx
dpnp/dpnp_algo/dpnp_algo.pxd
dpnp/dpnp_algo/dpnp_algo.pyx
dpnp/dpnp_container.py
dpnp/dpnp_iface_arraycreation.py
dpnp/version.py
tests/skipped_tests_gpu.tbl
tests/test_arraycreation.py
tests/test_sycl_queue.py

Out of cycle release to distribute the fix of https://github.com/IntelPython/dpnp/pull/1210 to intel channel on Anaconda.

Merge changes for OOC release 0.10.3

---

.github/workflows/build-sphinx.yml
.github/workflows/conda-package.yml
.github/workflows/pre-commit.yml

Updated actions with the latest versions.

Update versions of external github actions

---

.github/pull_request_template.md

Added a checkbox reminding to investigate performance impact of changes in PR

PR template: memento perficientur

---

.github/workflows/conda-package.yml

Following example of https://github.com/IntelPython/dpctl/pull/1159, apply similar changes to dpnp's workflow to build conda packages.

Fix OCL CPU RT activation in test_windows and test_linux steps

---

conda-recipe/meta.yaml

change numpy version from 1.19 to 1.21

---

doc/conf.py
dpnp/backend/doc/Doxyfile
dpnp/version.py

The PR updates a internal version to be aligned with dpnp git tag.

Update DPNP version to 0.11.2dev2

---

CHANGELOG.md

The PR introduces a change log file for DPNP releases.

Added ChangeLog.md

---

doc/conf.py
dpnp/backend/doc/Doxyfile
dpnp/version.py

Update DPNP version to `0.12.0` as part of IDP release `2023.2.0`.

Update version to 0.12.0

---

doc/conf.py

Merge master to gold/2021

---

doc/install.rst

Update install.rst to correct link to ONEAPI Toolkits

---

.pre-commit-config.yaml
tests/third_party/cupy/creation_tests/test_from_data.py
tests/third_party/cupy/testing/array.py
tests/third_party/cupy/testing/helper.py
tests/third_party/cupy/testing/parameterized.py

The PR proposes to extend pre-commit configuration with `pygrep-hooks`.

Added pygrep-hooks to pre-commit config

---

doc/conf.py
dpnp/backend/doc/Doxyfile
dpnp/version.py

The PR updates internal dpnp version to `0.12.1`.

Update version to 0.12.1

---

CHANGELOG.md

The PR is about to update change log with the latest commits which are going to be included into the next release.

Update change log due to 2024.0 release

---

dpnp/backend/include/dpnp_iface_fptr.hpp
dpnp/backend/kernels/dpnp_krnl_logic.cpp

Clean up old implementation of logic functions that are not use.

Clean up old implementation of logic functions

---

tests/test_sycl_queue.py

The PR is about to add #1601 to `gold/2021` branch.

Muted a test `test_array_creation_cross_device`

---

dpnp/dpnp_algo/dpnp_elementwise_common.py
tests/third_party/cupy/statistics_tests/test_meanvar.py

In this PR, elementwise call API in `dpnp` is updated to align with new changes in `dpctl` [#1463](https://github.com/IntelPython/dpctl/pull/1463)

update elementwise call API

---

.github/workflows/build-sphinx.yml
.github/workflows/conda-package.yml
.github/workflows/generate_coverage.yaml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml

The PR steps versions of used GitHub actions to the latest ones which currently available. It will help to get rid of the warnings.
Also PR updates `pre-commit` action to the latest available versions of checks.

Update versions of used GitHub actions and pre-commit checks

---

.github/workflows/build-sphinx.yml
.github/workflows/openssf-scorecard.yml
README.md

The PR adds OpenSSF scorecard badge to the README file.

Add OpenSSF Scorecard badge to README

---

.github/workflows/build-sphinx.yml
.github/workflows/generate_coverage.yaml
scripts/install_python_deps.sh

OpenSSF guides to explicitly pin version of packages installed with `pip` command.
The PR is about to align with the requirement.

Pin version of packages installed with pip command

---

dpnp/random/dpnp_algo_random.pyx

This PR suggests handling all exceptions from `Exception` class instead of `TypeError` and `ValueError` to solve Coverity reported issue [SW-404](https://cwe.mitre.org/data/definitions/404.html)

Fix Coverity issue in dpnp_algo_random

---

CHANGELOG.md

The PR updates `CHANGELOG.md` in scope of `0.14.0` release tag.

Update to CHANGELOG for 0.14.0

---

SECURITY.md

The PR adds a Security policy page to improve OpenSSF score.

Adds a Security policy

---

.github/workflows/conda-package.yml

The PR propose to extend number of tests running in public CI through GitHub actions by enabling previously skipped scopes.

Enable more tests to be run through GitHub action

---

dpnp/backend/extensions/blas/blas_py.cpp
dpnp/backend/extensions/blas/gemm_batch.cpp
dpnp/dpnp_iface_linearalgebra.py
dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
tests/test_product.py

In this PR, some updates are implemented related to BLAS routines.

minor updates related to BLAS routines

---

.github/workflows/generate_coverage.yaml

This PR is a temporary workaround to unblock `Coverage` action until dpnp is updated to support the latest dpctl where asynchronous execution is implemented.

Install `dpctl` package from dedicated channel in coverage GitHub action

---

.pre-commit-config.yaml
CODE_OF_CONDUCT.md
dpnp/backend/extensions/elementwise_functions/elementwise_functions.hpp
dpnp/dpnp_iface_linearalgebra.py
tests/third_party/cupy/testing/_helper.py

The PR updates versions of hooks used in pre-commit.
All new issues identified were addressed by that PR also.

Bump versions used in pre-commit hooks

---

.github/workflows/generate_coverage.yaml

The PR updates coveralls version `3.3.1` up to `4.0.1`.

Bump coveralls version `3.3.1` up to `4.0.1`

---

.github/workflows/CODEOWNERS

The PR adds `.github/CODEOWNERS` file.

Add codeowner file in .github

---

dpnp/backend/extensions/ufunc/CMakeLists.txt

Adapt ufunc extension for build on cuda devices

Adapt ufunc extension for build on cuda devices

---

dpnp/dpnp_iface_indexing.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/test_indexing.py
tests/test_sycl_queue.py
tests/test_usm_type.py
tests/third_party/cupy/indexing_tests/test_generate.py

Implement dpnp.ix_(). Add tests.

Implement dpnp.ix_()

---

dpnp/dpnp_iface_manipulation.py
tests/test_manipulation.py
tests/test_sycl_queue.py
tests/test_usm_type.py
tests/third_party/cupy/manipulation_tests/test_split.py

In this PR, `dpnp.array_split`, `dpnp.split`, `dpnp.hsplit`, `dpnp.vsplit`, and `dpnp.dsplit` are implemented.

implementation of `dpnp.array_split`, `dpnp.split`, `dpnp.hsplit`, `dpnp.vsplit`, and `dpnp.dsplit`

---

CHANGELOG.md
CMakeLists.txt

The PR adds 0.17 development in CHANGELOG.md

Start dpnp 0.17 development

---

CHANGELOG.md
dpnp/dpnp_iface_manipulation.py
tests/test_manipulation.py
tests/test_sycl_queue.py
tests/test_usm_type.py
tests/third_party/cupy/manipulation_tests/test_add_remove.py
tests/third_party/cupy/manipulation_tests/test_rearrange.py

This PR backports of #2030 from development branch to `maintenance/0.16.x`.

Backport gh-2030

---

CHANGELOG.md
dpnp/dpnp_iface_manipulation.py
tests/third_party/cupy/manipulation_tests/test_add_remove.py

This PR backports of #2034 from development branch to `maintenance/0.16.x`.

Backport gh-2034

---

setup.py

This PR backports of https://github.com/IntelPython/dpnp/pull/1855 from `maintenance/0.15.x` branch to development branch.

Backport gh-1855 to development branch

---

setup.py

This PR backports of https://github.com/IntelPython/dpnp/pull/1855 from `maintenance/0.15.x` branch to `maintenance/0.16.x` branch.

Backport gh-1855 to `maintenace/0.16.x` branch

---

CHANGELOG.md
dpnp/dpnp_iface_manipulation.py
tests/test_arraymanipulation.py
tests/test_manipulation.py
tests/test_sycl_queue.py
tests/test_usm_type.py
tests/third_party/cupy/manipulation_tests/test_kind.py

This PR backports of https://github.com/IntelPython/dpnp/pull/2036 from development branch to `maintenance/0.16.x` branch.

Backport gh-2036

---

dpnp/dpnp_iface_indexing.py

This PR is about resolving formatting issues detecting while reviewing new documentation of `dpnp.ravel_multi_index` and `dpnp.unravel_index` functions.

Resolve formatting issue in documentation of `dpnp.ravel_multi_index` and `dpnp.unravel_index`

---

.gitignore
CHANGELOG.md
dpnp/backend/kernels/dpnp_krnl_random.cpp
dpnp/backend/src/queue_sycl.cpp

The PR is about to resolve compilation warning and error while building in debug mode.

Resolve compilation failure in debug build

---

CHANGELOG.md
dpnp/fft/dpnp_utils_fft.py

This PR backports of https://github.com/IntelPython/dpnp/pull/2067 from development branch to `maintenance/0.16.x`.

backport-gh-2067

---

CHANGELOG.md
dpnp/backend/extensions/blas/blas_py.cpp
dpnp/backend/extensions/blas/gemm.cpp
dpnp/backend/extensions/blas/gemm.hpp
dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
tests/test_mathematical.py

This PR backports of #2101 from development branch to `maintenance/0.16.x`.

Backport gh-2101

---

dpnp/backend/extensions/ufunc/CMakeLists.txt
dpnp/backend/extensions/ufunc/elementwise_functions/spacing.cpp
dpnp/backend/extensions/ufunc/elementwise_functions/spacing.hpp
dpnp/backend/kernels/elementwise_functions/spacing.hpp
dpnp/dpnp_iface_mathematical.py
tests/skipped_tests.tbl
tests/skipped_tests_gpu.tbl
tests/test_mathematical.py
tests/test_sycl_queue.py
tests/test_usm_type.py

The PR proposes to add implementation of `dpnp.spacing` function.
The new dedicated `_spacing` function is added to `_ufunc_impl` pybind11 extension.
All the required tests are implemented to cover the new function.

Add implementation of `dpnp.spacing` function

---

.github/CODEOWNERS
conda-recipe/meta.yaml

The PR proposes to update the list of code owners and maintainers.

Update code owners and maintainers

---

.github/workflows/cron-run-tests.yaml

The PR resolves issue with `Run tests suite` GitHub action. The `if` condition works properly now.

Update step to run only for Windows

---

dpnp/tests/test_histogram.py

```python
with pytest.raises(TypeError):
dpnp.digitize(x_np, bins_dp)
dpnp.digitize(x_dp, bins_np)  # <= unreachable line
```
```python
with pytest.raises(TypeError):
dpnp.digitize(x_np, bins_dp)
with pytest.raises(TypeError):
dpnp.digitize(x_dp, bins_np)  # <= reachable line
```

fix test_digitize_error

---

dpnp/backend/kernels/dpnp_krnl_elemwise.cpp

PR proposes to pass `striped` property into `group_load` and `group_store` calls. It will help to fully replicate the legacy behavior of `sub_group::load<vec_sz>`and `sub_group::store<vec_sz>`.

Properly set properties of group_load/group_store to striped

---

.github/CODEOWNERS
conda-recipe/meta.yaml

The PR updates `.CODEOWNERS` file and a list of recipe maintainers in `conda-recipe/meta.yaml`.

Update code owners and recipe maintainers

---

CHANGELOG.md
dpnp/backend/extensions/statistics/sliding_window1d.hpp
dpnp/tests/test_usm_type.py

This PR backports of #2333 from development branch to `maintenance/0.17.x`.

Backprt gh-2333

---

CHANGELOG.md

The PR sets release date for `0.17.0` as part of `2025.1` release preparation.

Set release date

---

CHANGELOG.md
dpnp/backend/extensions/window/blackman.hpp
dpnp/backend/extensions/window/window_py.cpp
dpnp/dpnp_iface_window.py
dpnp/tests/test_sycl_queue.py
dpnp/tests/test_usm_type.py
dpnp/tests/test_window.py
dpnp/tests/third_party/cupy/math_tests/test_window.py

In this PR, `dpnp.blackman` is implemented.
- [x Have you provided a meaningful PR description?

implement `dpnp.blackman`

---

CHANGELOG.md
dpnp/backend/extensions/window/bartlett.hpp
dpnp/backend/extensions/window/blackman.hpp
dpnp/backend/extensions/window/window_py.cpp
dpnp/dpnp_iface_window.py
dpnp/tests/test_sycl_queue.py
dpnp/tests/test_usm_type.py
dpnp/tests/test_window.py
dpnp/tests/third_party/cupy/math_tests/test_window.py

In this PR, `dpnp.bartlett` is implemented.

implement `dpnp.bartlett`

---

CHANGELOG.md

The PR populates the changelog with gh-2339 changes.

Add gh-2339 to Changelog

---

CHANGELOG.md
dpnp/dpnp_utils/dpnp_algo_utils.pyx

This PR backports of #2467 from development branch to `maintenance/0.18.x`.

Backprt gh-2467

---

CHANGELOG.md

This PR backports of #2471 from development branch to `maintenance/0.18.x`.

Backprt gh-2471

---

dpnp/dpnp_iface_manipulation.py

The PR updates the examples to make it a bit clear.

Slightly update the examples in `dpnp.column_stack` and `dpnp.dstack`

---

conda-recipe/meta.yaml
environments/dpctl_pkg.txt
environments/dpctl_pkg.yml
pyproject.toml

This PR bumps dependency on dpctl package.

Bump required dpctl version up to `0.21.0*`

---

CHANGELOG.md

This PR updates changelog by adding entries for `dpnp.linalg.lu_factor`.

Update CHANGELOG for `dpnp.linalg.lu_factor`
