IntelPython/dpnp

- dpnp/backend/backend_iface.hpp
- dpnp/backend/mkl_wrap_blas1.cpp
- dpnp/backend/mkl_wrap_blas3.cpp
- dpnp/backend/mkl_wrap_lapack.cpp
- dpnp/backend/mkl_wrap_rng.cpp
- dpnp/linalg/linalg.pyx
- tests/test_linalg.py
I missed this PR
https://github.com/IntelPython/dpnp/pull/5
beta9 is required for work with linalg.eig in any case.
Test shows issues and difference between current (mkl::lapack::syevd) and original implementations. 
tests/test_linalg.py::test_eig_arange[2-float64] PASSED[  5%]
tests/test_linalg.py::test_eig_arange[2-float32] PASSED[ 10%]
tests/test_linalg.py::test_eig_arange[2-int64] PASSED[ 15%]
tests/test_linalg.py::test_eig_arange[2-int32] PASSED[ 20%]
tests/test_linalg.py::test_eig_arange[4-float64] PASSED[ 25%]
tests/test_linalg.py::test_eig_arange[4-float32] FAILED[ 30%]
tests/test_linalg.py::test_eig_arange[4-int64] PASSED[ 35%]
tests/test_linalg.py::test_eig_arange[4-int32] PASSED[ 40%]
tests/test_linalg.py::test_eig_arange[8-float64] PASSED[ 45%] …
> linalg.eig and beta09 related changes

- dpnp/backend/backend_iface_fptr.cpp
perhaps `eft_LNG` is not a good name.
- tried to keep the same length of the variable to keep code formatting.
- tried to avoid possible names interference (LONG with long, etc)
> map init. one more variant

- dpnp/dparray.pyx
- dpnp/dpnp_iface_manipulation.py
- tests/skipped_tests.tbl
- tests/third_party/cupy/manipulation_tests/test_shape.py
Current implementation of `dparray.ravel` just calls `dparray.flatten()` that returns copy of the input array.
> Add methods flatten and ravel + cupy tests

- dpnp/backend.pxd
- dpnp/backend.pyx
- dpnp/backend/backend_iface_fptr.cpp
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend_mathematical.pyx
- dpnp/backend_trigonometric.pyx
Additionally moved `call_fptr_1in_1out` and `call_fptr_2in_1out` to `backend.pyx`.
> Move trigonometric functions to new FPRT structure

- dpnp/backend.pxd
- dpnp/backend/backend_iface.hpp
- dpnp/backend/backend_iface_fptr.cpp
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend/custom_kernels_statistics.cpp
- dpnp/backend_statistics.pyx
- dpnp/dparray.pyx
- dpnp/dpnp_iface_statistics.py
- tests/skipped_tests.tbl
Combined 2 functions to 1 PR because one depends on the other.
> Add functions std and var

- dpnp/backend/backend_fptr.hpp
- dpnp/backend/backend_iface_fptr.cpp
- dpnp/backend/custom_kernels_manipulation.cpp
- distribute fptr storage initialization across diffrent files with the kernel definition
- move specialization of the kernel template function to this initialization procedure (avoid explicit specialization)
> FPTR distributed init. step 1

- tests/skipped_tests.tbl
- tests/test_random.py
* added `test_randn_normal_distribution`. See: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html
* added `test_radnom_seed`
* skipped tests
TODO:
* add `scipy` dependency into test build
> tests: more tests for random funcs

- dpnp/backend/backend_iface.hpp
- dpnp/backend/custom_kernels_random.cpp
- dpnp/random/_random.pyx
- examples/example5.cpp
- setup.py
* renamed `mkl_wrap_rng.cpp` to `dpnp/backend/custom_kernels_random.cpp`
* renamed backend kernels names for `random` module
> REFACTOR: renamed random module functions and sources names

- dpnp/backend/custom_kernels_mathematical.cpp
- tests/test_arithmetic.py
Aligned `remainder` with `np.remainder` as MKL team proposed.
> REMAINDER align with numpy

- dpnp/__init__.py
- examples/example1.py
- examples/example2.py
- examples/example6.py
- examples/example7.py
This PR is close issue #132 
if we load `numpy` from `inteloneapi` it loads MKL library. Usually, loaded MKL has some old version and some symbols can not be resolved correctly.
The solution is to load `DPNP` before `numpy`.
This PR add a warning about unexpected loading order of a modules.
> show message if numpy loaded first and fix module loading order

- utils/dpnp_coverage.py
Example output:
```
numpy public API:                                                                                                                                                                                                 
functions: add_newdoc, alen, all, allclose, alltrue, amax, amin, angle, any, append, apply_along_axis, apply_over_axes, argmax, argmin, argpartition, argsort, argwhere, around, array2string, array_equal, array_equiv, array_repr, array_split, array_str, asanyarray, asarray, asarray_chkfinite, ascontiguousarray, asfarray, asfortranarray, asmatrix, asscalar, atleast_1d, atleast_2d, atleast_3d, average, bartlett, base_repr, binary_repr, bincount, blackman, block, bmat, broadcast_arrays, broadcast_to, busday_count, busday_offset, byte_bounds, can_cast, choose, clip, …
```
> Implement script to show coverage dpnp vs cupy

- dpnp/backend.pxd
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend/custom_kernels_random.cpp
- dpnp/random/_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_random.py
gamma(shape[, scale, size]) Draw samples from a Gamma distribution.
* array_like of floats for `scale` and `shape` params
> ENH: added `random.gamma`

- setup.py
Needed for compatibility with oneAPI TBB. Known issue when building with gcc 9
> adding -DPSTL_USE_PARALLEL_POLICIES=0 for TBB

- dpnp/backend.pxd
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend/custom_kernels_random.cpp
- dpnp/random/_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
standard_normal([size]) Draw samples from a standard Normal distribution (mean=0, stdev=1).
* after merge of this PR, `randn` will be redesigned and `normal` will be added
* is it needed `standard_normal` on backend? We just can call `normal` with params (mean=0, stdev=1) from `standard_normal` on python level.
```python
>>> np.mean(dpnp.random.standard_normal(10**6));np.var(dpnp.random.standard_normal(10**6))
0.00030427453642504083
1.0013896813115708
>>> np.mean(np.random.standard_normal(10**6));np.var(np.random.standard_normal(10**6))
0.00011309454634553527
1.0003356224869078
```
> ENH: added `random.standard_normal`

- dpnp/random/_random.pyx
E.g.
```
In [1]: import dpnp
mkl-service + Intel(R) MKL: THREADING LAYER: (null)
mkl-service + Intel(R) MKL: setting Intel(R) MKL to use INTEL OpenMP runtime
mkl-service + Intel(R) MKL: preloading libiomp5.so runtime
MKL_VERBOSE Intel(R) MKL 2021.0 Update 1 beta10 build 20201008 for Intel(R) 64 architecture Intel(R) Advanced Vector Extensions 2 (Intel(R) AVX2) enabled processors, Lnx 1.
10GHz lp64 intel_thread
MKL_VERBOSE SDOT(2,0x561c72606c10,1,0x561c72606c10,1) 1.41ms CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:6
Running on: Intel(R) Graphics Gen9 [0x9bca]
DPCtrl SYCL queue used
SYCL kernels link time: 0.190619 (sec.)
In [2]: dpnp.random.gamma(3.4, 0.67)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent …
```
> Use ctypedef ... except + to intercept oneMKL exceptions

- dpnp/backend.pxd
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend/custom_kernels_random.cpp
- dpnp/random/_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
poisson([lam, size]) Draw samples from a Poisson distribution.
* array_like of floats for `lam` params
```python
>>> np.mean(dpnp.random.poisson(12, 10**6))
12.00312
>>> np.var(dpnp.random.poisson(12, 10**6))
12.02310547279755
>>> # theoretical mean and var are equal to lam
```
> ENH: added `random.poisson`

- dpnp/backend.pxd
- dpnp/backend.pyx
- dpnp/backend/backend_fptr.hpp
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend/dpnp_kernels_fft.cpp
- dpnp/fft/dpnp_algo_fft.pyx
- dpnp/fft/dpnp_iface_fft.py
- tests/skipped_tests.tbl
need to add limited support for `DPNP_FT_CMPLX128` because `fft.fft()` is required it (output type is always complex128)
> add custom kernel to fft.fft()

- dpnp/backend/backend_iface.hpp
- dpnp/backend/custom_kernels_random.cpp
- dpnp/random/_random.pyx
* using 'simple' interface instead of STL. ( `const double* p_vector, const size_t p_vector_size` instead of `std::vector<double>& p_vector`) -> `random.multinomial` backend function (`custom_rng_multinomial_c` signature was changed)
>Perhaps it might be fixed later.
This is a not quite good to use STL in the functions interface. These containers are good for regular usage but in our case we need to provide "simple" interface. Usually we use Cython or Numba IR as a customer for this intrface. Importing C++ STL is a quite big pain for such usage model.
Please use const double* p_vector, size_t p_vector_size instead. @shssf . See #276
> API: changed `random.multinomial` backend function api

- dpnp/random/_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
style fix (whitespace, PEP8), refactoring docs for random module
Fixed:
* dpnp/random/_random.pyx:314:55: E241 multiple spaces after ','
* dpnp/random/_random.pyx:710:121: E501 line too long (127 > 120 characters)
* dpnp/random/dpnp_iface_random.py:680:9: E303 too many blank lines (2)
* dpnp/random/dpnp_iface_random.py:1645:1: W293 blank line contains whitespace
* dpnp/random/dpnp_iface_random.py:1662:1: W293 blank line contains whitespace
* tests/test_random.py:405:121: E501 line too long (133 > 120 characters)
Corrected:
* function names in docstrings
* docstrings in numpy style 
* added needed blanklines
* misc updates
> STY: style fix (whitespace, PEP8), refactoring docs for random module

- dpnp/backend.pxd
- dpnp/backend/backend_iface.hpp
- dpnp/backend/backend_iface_fptr.hpp
- dpnp/backend/custom_kernels_random.cpp
- dpnp/random/_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/skipped_tests_gpu.tbl
- tests/test_random.py
multivariate_normal(mean, cov[, size, ...) Draw random samples from a multivariate normal distribution.
* fallback to `numpy` (on other PR)
* update docstrings. Currently modified `numpy`'s one + add block limitations (on other PR)
```python
>>> mean = (109, 234, 123)
>>> cov = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
>>> np.mean(dpnp.random.multivariate_normal(mean, cov, (3**10, 2))); np.mean(np.random.multivariate_normal(mean, cov, (3**10, 2)))
155.3329662598603
155.33495759713927
>>> np.var(dpnp.random.multivariate_normal(mean, cov, (3**10, 2))); np.var(np.random.multivariate_normal(mean, cov, (3**10, 2)))
3127.633479105447
3127.877595801929
```
> ENH: added `random.multivariate_normal`

- dpnp/random/dpnp_iface_random.py
Permutations:
* shuffle(x) Modify a sequence in-place by shuffling its contents.
* permutation(x) Randomly permute a sequence, or return a permuted range.
functions call  `numpy.random.shuffle` and `numpy.random.permutation` on the backend.
> ENH: random permutation funcs, numpy call

- dpnp/random/dpnp_iface_random.py
* noncentral_f(dfnum, dfden, nonc[, size]) Draw samples from the noncentral F distribution.
* pareto(a[, size]) Draw samples from a Pareto II or Lomax distribution with specified shape.
* power(a[, size]) Draws samples in [0, 1] from a power distribution with positive exponent a - 1.
* standard_t(df[, size]) Draw samples from a standard Student’s t distribution with df degrees of freedom.
* triangular(left, mode, right[, size]) Draw samples from the triangular distribution over the interval [left, right].
* vonmises(mu, kappa[, size]) Draw samples from a von Mises distribution.
* wald(mean, scale[, size]) Draw samples from a Wald, or inverse Gaussian, distribution.
* zipf(a[, size]) Draw samples from a Zipf distribution.
* functions uses `numpy` on the backend
> ENH: random distributions funcs, numpy call, [2/3]

- tests/skipped_tests.tbl
- tests/third_party/cupy/random_tests/test_distributions.py
waiting merge #332 (CI will be green after)
* fixed tests for random.zipf
* enabled:
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsZipf_param_2_{a_shape=(3, 2), shape=(4, 3, 2)}::test_zipf
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsZipf_param_3_{a_shape=(3, 2), shape=(3, 2)}::test_zipf
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsZipf_param_0_{a_shape=(), shape=(4, 3, 2)}::test_zipf
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsZipf_param_1_{a_shape=(), shape=(3, 2)}::test_zipf
> TEST: enabled some third_party/cupy tests for `random` module

- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/third_party/cupy/random_tests/test_distributions.py
* fixed tests for `dirichlet`, `beta` distributions
* removed 20 test cases form list
1) 
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsBeta_param_0_{a_shape=(), b_shape=(), shape=(4, 3, 2)}::test_beta
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsBeta_param_1_{a_shape=(), b_shape=(), shape=(3, 2)}::test_beta
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsBeta_param_2_{a_shape=(), b_shape=(3, 2), shape=(4, 3, 2)}::test_beta
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsBeta_param_3_{a_shape=(), b_shape=(3, 2), shape=(3, 2)}::test_beta
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsBeta_param_4_{a_shape=(3, 2), b_shape=(), shape=(4, …
> TEST: enabled third_party cupy tests for distributions check

- tests/skipped_tests_gpu.tbl
- tests/third_party/cupy/random_tests/test_distributions.py
- utils/dpnp_build_utils.py
* fixed tests for `chisquare` distributions
* removed 4 test cases from skipp list
1) fails when calls dpnp on backend (CPU):
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsChisquare_param_0_{df_shape=(), shape=(4, 3, 2)}::test_chisquare
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsChisquare_param_1_{df_shape=(), shape=(3, 2)}::test_chisquare
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsChisquare_param_2_{df_shape=(3, 2), shape=(4, 3, 2)}::test_chisquare
+ tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsChisquare_param_3_{df_shape=(3, 2), shape=(3, 2)}::test_chisquare
> TEST: enabled third_party cupy tests for distributions check 2

- dpnp/backend/backend_pstl.hpp
- dpnp/backend/queue_sycl.hpp
- setup.py
- utils/command_build_clib.py
address the error:
```
error: kernel name cannot be a type in the "std" namespace
```
> Change default compiler name

- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
* fix `random.binomial` fallback
* update `random.binomial` docstring: align docstrings with template
* add `test_binomial_invalid_args`
> FIX: `random.binomial` fallback

- dpnp/random/dpnp_iface_random.py
I removed size check from python level since it is handled by dpnp.dparray.
Also it fixes limitation for size types. 
Removed size assignee on random funcs level, when given size is default value(`None`)
> DEP: removed size check. random

- doc/docstring_template.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- tests/tests_perf/math_tests/test_trigonometric.py
- tests/third_party/cupy/random_tests/test_distributions.py
- utils/dpnp_build_utils.py
Style fix (whitespace, PEP8):
/utils/dpnp_build_utils.py:219:57: W291 trailing whitespace
/doc/docstring_template.py:66:51: W291 trailing whitespace
/dpnp/dpnp_iface_arraycreation.py:965:19: W291 trailing whitespace
/dpnp/dpnp_iface_linearalgebra.py:137:73: W291 trailing whitespace
/dpnp/dpnp_iface_manipulation.py:257:9: E265 block comment should start with '# '
/dpnp/dpnp_iface_manipulation.py:322:9: W503 line break before binary operator
/dpnp/dpnp_iface_manipulation.py:323:9: W503 line break before binary operator
/dpnp/dpnp_iface_manipulation.py:324:9: W503 line break before binary operator
/dpnp/dpnp_iface_manipulation.py:325:9: E125 continuation line with same indent as next logical line
/tests/third_party/cupy/random_tests/test_distributions.py:306:5: E303 too many blank lines (2) …
> STY: style fix (whitespace, PEP8)

- dpnp/random/dpnp_iface_random.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/third_party/cupy/random_tests/test_distributions.py
* update random python level funcs fallback
* aligned docstrings
the same issue for fail as is on #346 , #347 :
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsWeibull_param_0_{a_shape=(), shape=(4, 3, 2)}::test_weibull
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsWeibull_param_0_{a_shape=(), shape=(4, 3, 2)}::test_weibull_for_inf_a
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsWeibull_param_0_{a_shape=(), shape=(4, 3, 2)}::test_weibull_for_negative_a
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsStandardGamma_param_0_{shape=(4, 3, 2), shape_shape=()}::test_standard_gamma
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsStandardGamma_pa …
> FIX: update random funcs fallback

- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/third_party/cupy/random_tests/test_distributions.py
* enabled third-party tests for random funcs
__324 test cases removed form skip lists__
```DPNP_QUEUE_GPU=1 pytest tests/third_party/cupy/random_tests/test_distributions.py```
Before: 176 passed, 421 skipped
After: 248 passed, 121 skipped 
__Update: ++72 passed, --300 skipped__
```DPNP_QUEUE_GPU=0 pytest tests/third_party/cupy/random_tests/test_distributions.py```
Before: 172 passed, 425 skipped
After: 244 passed, 125 skipped 
__Update: ++72 passed, --300 skipped__
> TEST: enabled third-party tests for random funcs

- dpnp/random/dpnp_iface_random.py
* align with template docstrings for some random funcs
* fix `seed` fallback
> DOC: align with template docstrings for some random funcs

- dpnp/backend/queue_sycl.cpp
- dpnp/backend/queue_sycl.hpp
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
* Added using mt19937 instead of philox4x32x10 for random as is in numpy, see [numpy.random.seed](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html#numpy.random.seed)
* update test cases: update rel_tol and abs_tol values for test cases
> DEP: using mt19937 instead of philox4x32x10 for random

- dpnp/random/_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/third_party/cupy/random_tests/test_distributions.py
* update `random.uniform`
* update `dpnp_uniform`
* align with template docstring for `random.uniform`
* enables cupy tests for check
* removed tests from skip lists ++2 passed test cases
test. root cause as on #346 , #347 :
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsUniform_param_0_{high_shape=(), low_shape=(), shape=(4, 3, 2)}::test_uniform
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsUniform_param_1_{high_shape=(), low_shape=(), shape=(3, 2)}::test_uniform
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsUniform_param_2_{high_shape=(), low_shape=(3, 2), shape=(4, 3, 2)}::test_uniform
- tests/third_party/cupy/random_tests/test_distributions.py::TestDistributionsUniform_param_3_{high_shape=(), …
> FIX: update `random.uniform`

- dpnp/random/dpnp_iface_random.py
* align docstring with templates for `random.sample`
> DOC: align docstring with templates for `random.sample`

- dpnp/backend/dpnp_kernels_random.cpp
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
Closes #257 
* Fix `random.gumbel` moments issue.
* enabled tests for the check.
```python
>>> np.mean(dpnp.random.gumbel(12, 0.8, 10**6));np.mean(np.random.gumbel(12, 0.8, 10**6))
12.463093507232983
12.464127453889729
>>> np.var(dpnp.random.gumbel(12, 0.8, 10**6));np.var(np.random.gumbel(12, 0.8, 10**6))
1.0524031728788483
1.0538524917740162
```
> FIX: `random.gumbel` moments, issue #257

- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/queue_sycl.cpp
- dpnp/backend/src/queue_sycl.hpp
* added stream for classic MKL call
* update `radnom.beta` backend func, when GPU selector
* backend tests -> TODO pytest_cpp will be added -> other PR
* update example5.cpp -> other PR
* * rename `backend_sycl` -> other PR
> ENH: dpnp backend fallback to classic MKL; update `random.beta`

- dpnp/backend/kernels/dpnp_krnl_random.cpp
* update `dpnp.radnom` backend funcs, when GPU selector:
*  binomial
* chi_square
* gamma
* hypergeometric
* multinomial
* negative_binomial
* multivariate_normal
> ENH: dpnp backend fallback to classic MKL for random

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
pareto(a[, size]) Draw samples from a Pareto II or Lomax distribution with specified shape.
* array_like of floats for `a` param
* tests for backend `dpnp_rng_pareto_c`
```python
>>> a= 30.
>>> np.mean(dpnp.random.pareto(a, size=10**6)); np.mean(np.random.pareto(a, size=10**6))
1.0345331694970257
0.0345063959568665
>>> np.var(dpnp.random.pareto(a, size=10**6)); np.var(np.random.pareto(a, size=10**6))
0.0012693687866730547
0.0012701945158571334
```
> ENH: impl `random.pareto`

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
standard_t(df[, size]) Draw samples from a standard Student’s t distribution with df degrees of freedom.
* array_like of floats for `df` param
* tests for backend `dpnp_rng_standard_t_c`
```python
>>> df = 300.
>>> np.mean(dpnp.random.standard_t(df, size=10**6)); np.mean(np.random.standard_t(df, size=10**6))
-0.0006127286643388802
-0.0005636420187996591
>>> np.var(dpnp.random.standard_t(df, size=10**6)); np.var(np.random.standard_t(df, size=10**6))
1.0054421001664342
1.0065497207136775
```
> ENH: `random.standard_t` impl

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
power(a[, size]) Draw samples from a Pareto II or Lomax distribution with specified shape.
* disabled (incorrect check for dpnp.random.power  functionality):
* random/tests/test_random.py::TestRandomDist::test_power - AssertionError: (external)
* random/tests/test_randomstate.py::TestRandomDist::test_power - AssertionError (external)
* array_like of floats for `a` param
* tests for backend `dpnp_rng_power_c` (in other PR, after `backend/tests/test_random.cpp` refactoring)
```python
>>> a = 30.
>>> np.mean(dpnp.random.power(a, size=10**6)); np.mean(np.random.power(a, size=10**6))
0.9676981468821753
0.9677700451718035
>>> np.var(dpnp.random.power(a, size=10**6)); np.var(np.random.power(a, size=10**6))
0.0009773684210089358
0.0009771529307039824
```
> ENH: impl `random.power`

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
logistic([loc, scale, size]) Draw samples from a logistic distribution.
* disabled (incorrect check for dpnp.random.logistic functionality):
* random/tests/test_random.py::TestRandomDist::test_logistic - AssertionError: (external)
* random/tests/test_randomstate.py::TestRandomDist::test_logistic - AssertionError (external)
* array_like of floats for `loc` and `scale` params
* tests for backend `dpnp_rng_logistic_c` (in other PR, after `backend/tests/test_random.cpp` refactoring)
```python
>>> loc = 2.56
>>> scale = 0.8
>>> np.mean(dpnp.random.logistic(loc, scale, size=10**6)); np.mean(np.random.logistic(loc, scale, size=10**6))
2.5602924600878927
2.5601147009097946
>>> np.var(dpnp.random.logistic(loc, scale, size=10**6)); np.var(np.random.logistic(loc, scale, size=10**6)) …
```
> ENH: impl `random.logistic`

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/tests/test_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
* return a function pointer for `random.seed` backend function.
* all this functionality checked by `test_seed` python tests (from `tests/test_random.py`).
* additionally backend test for check.
> ENH: fptr for `random.seed` backend

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/include/dpnp_iface_random.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/tests/test_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
f(dfnum, dfden[, size]) Draw samples from an F distribution.
* disabled (incorrect check for dpnp.random.f functionality):
* random/tests/test_random.py::TestRandomDist::test_f - AssertionError: (external)
* random/tests/test_randomstate.py::TestRandomDist::test_f - AssertionError (external)
* array_like of floats for `dfnum` and `dfden` params
* more tests for backend `dpnp_rng_f_c` (in other PR, after `backend/tests/test_random.cpp` refactoring)
```python
>>> dfnum = 12.56
>>> dfden = 13.0
>>> np.mean(dpnp.random.f(dfnum, dfden, size=10**6)); np.mean(np.random.f(dfnum, dfden, size=10**6))
1.1817384218229634
1.1826735659452576
>>> np.var(dpnp.random.f(dfnum, dfden, size=10**6)); np.var(np.random.f(dfnum, dfden, size=10**6))
0.581951794526341
0.5804620018787939
```
```bash
[----------] 1 …
```
> ENH: impl `random.f`

- dpnp/backend/tests/test_random.cpp
* added test based on the comparison of theoretical and sample moments
* this is function will be generalized on restructuring `backend/tests/test_random.cpp` (test class will be added) - on other PR
```bash
[----------] 2 tests from TestBackendRandomUniform
[ RUN      ] TestBackendRandomUniform.test_seed
...
[       OK ] TestBackendRandomUniform.test_seed (222 ms)
..
[       OK ] TestBackendRandomUniform.test_statistics (222 ms)
[----------] 2 tests from TestBackendRandomUniform (444 ms total)
```
> TEST: add checking statistics for distr

- scripts/azure-pipelines.yml
- utils/command_build_cmake_clib.py
* added env val to enbale DPNP backend tests
* update README.md (add `Gtest`, as deps if is needed enabling dpnp backend tests)
* add `export DPNP_BACKEND_TESTS_ENABLE=1` to some azure-pipelines job (`dpnp/scripts/azure-pipelines.yml`)
> TEST: env val to enbale DPNP backend tests

- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
We have several options to do the same
- __attribute__((unused)) it is GCC compiler specific
- [[maybe_unused]] but it requires C++17 and brings changes (at least in style) in API line https://en.cppreference.com/w/cpp/language/attributes/maybe_unused
Need cross platform and cross compiler solution with minimum changes in source code (style and lines length)
So, according to the KISS principle I did this PR
> mark unused variable in partable way with no API changes

- tests/skipped_tests_gpu.tbl
https://github.com/IntelPython/dpnp/issues/567
> skip GPU tests for eig, eigvals and svd funcs until they are not fixed

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/include/dpnp_iface_random.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
triangular(left, mode, right[, size]) Draw samples from the triangular distribution over the interval [left, right].
* disabled (incorrect check for dpnp.random.triangularfunctionality):
* random/tests/test_random.py::TestRandomDist::test_triangular - AssertionError: (external)
* random/tests/test_randomstate.py::TestRandomDist::test_triangular - AssertionError (external)
* array_like of floats for `left`, `mode` and `right` params
* tests for backend `dpnp_rng_triangular_c` (in other PR, after `backend/tests/test_random.cpp` refactoring PR552 )
```python
>>> left = 1.0
>>> mode = 2.0
>>> right = 3.0
>>> numpy.mean(numpy.array(numpy.random.triangular(left, mode, right, 10**6)));numpy.mean(numpy.array(dpnp.random.triangular(left, mode, right, 10**6)))
2.000347680676491
2.0000300156353137 …
```
> ENH: impl `random.triangular`

- dpnp/backend/kernels/dpnp_krnl_random.cpp
let queue managing on device
For all funcs will commit in one other PR, if this will be accepted.
> ENH: some optimization for `random.triangular`

- dpnp/backend/tests/CMakeLists.txt
- dpnp/backend/tests/test_main.cpp
- dpnp/backend/tests/test_random.cpp
* redesigned backend testing
* all todos from `dpnp/backend/tests/test_random.cpp`
* some fix for https://github.com/IntelPython/dpnp/issues/551
> ENH: update backend tests

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/include/dpnp_iface_random.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/tests/test_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
zipf(a[, size]) Draw samples from a Zipf distribution.
* some tests fails investigate -> all related test passes
* disabled (incorrect check for dpnp.random.zipf functionality):
* tests/test_random.py::TestRandomDist::test_zipf
* tests/test_random.py::TestRandomDist::test_zipf_0
* tests/test_randomstate.py::TestRandomDist::test_zipf
* tests/test_randomstate.py::TestRandomDist::test_zipf_0
* tests/test_randomstate.py::TestBroadcast::test_zipf
* array_like of floats for `a` param
* add backend test -> on other PR, after merge PR552
* some tests fail will be investigated on other PR:
* tests/test_randomstate.py::TestBroadcast::test_zipf
* tests/test_randomstate.py::test_integer_dtype[zipf]
* tests/test_random.py::TestBroadcast::test_zipf
```python
>>> …
```
> ENH: impl `random.zipf`

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/include/dpnp_iface_random.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_random.py
- tests_external/skipped_tests_numpy.tbl
noncentral_chisquare(df, nonc[, size]) Draw samples from a noncentral chi-square distribution.
* disabled (incorrect check for dpnp.random.noncentral_chisquare functionality):
* random/tests/test_random.py::TestRandomDist::test_noncentral_chisquare - AssertionError: (external)
* random/tests/test_randomstate.py::TestRandomDist::test_noncentral_chisquare - AssertionError (external)
* array_like of floats for `df` and `nonc ` params
* tests for backend `dpnp_rng_noncentral_chisquare_c` (in other PR, after `backend/tests/test_random.cpp` refactoring PR552 )
* ``if you use this variable for loops only - use standard way to declare it inside loop boby`` https://github.com/IntelPython/dpnp/pull/543#discussion_r571027739
* "DPNP alloc will take care about errors" - don't check errors for DPNP …
> ENH: impl random.noncentral_chisquare

- dpnp/backend/src/queue_sycl.cpp
> MAINT: fix typo

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_indexing.pyx
Implemented native version for function dpnp.fill_diagonal().
tests:
tests/test_indexing.py::test_fill_diagonal[[[0, 0], [0, 0]]--1]
tests/test_indexing.py::test_fill_diagonal[[[0, 0], [0, 0]]-0]
tests/test_indexing.py::test_fill_diagonal[[[0, 0], [0, 0]]-1]
tests/test_indexing.py::test_fill_diagonal[[[1, 2], [1, 2]]--1]
tests/test_indexing.py::test_fill_diagonal[[[1, 2], [1, 2]]-0]
tests/test_indexing.py::test_fill_diagonal[[[1, 2], [1, 2]]-1]
tests/test_indexing.py::test_fill_diagonal[[[1, 2], [3, 4]]--1]
tests/test_indexing.py::test_fill_diagonal[[[1, 2], [3, 4]]-0]
tests/test_indexing.py::test_fill_diagonal[[[1, 2], [3, 4]]-1]
tests/test_indexing.py::test_fill_diagonal[[[0, 1, 2], [3, 4, 5], [6, 7, 8]]--1]
tests/test_indexing.py::test_fill_diagonal[[[0, 1, 2], [3, 4, 5], [6, 7, 8]]-0] …
> add native version function fill_diagonal

- dpnp/backend/kernels/dpnp_krnl_random.cpp
No need in extra alloc checks due to:
* changes on `dpnp_memory_alloc_c` (https://github.com/IntelPython/dpnp/commit/e36bb8511ed849976220038ea34506f34ddc5f87)
* classic MKL and OneMKL funcs handling `nullptrs`
> MAINT: removed extra checks for allocs on random module

- dpnp/random/dpnp_iface_random.py
- tests_external/skipped_tests_numpy.tbl
`permutation(x)` Randomly permute a sequence, or return a permuted range.
disabled (incorrect check for dpnp.random.permutation functionality):
* random/tests/test_randomstate.py::TestRandomDist::test_permutation - AssertionError: (external)
``` python
>>> dpnp.random.permutation(10)
<DPNP DParray:name=dparray: mem=0x560e5f71bd00: size=10: shape=(10,): type=int64>
>>> print(dpnp.random.permutation(10))
[3 8 7 9 0 6 1 2 4 5]
```
> ENH: enabled random.permutation on CPU and GPU

- conda-recipe/meta.yaml
`libmkl_sycl.so` was moved to separate package `mkl-dpcpp` for MLK of version `2021.2.0`. So now we need the package to be installed in internal CI environment.
> Support MLK 2021.2.0

- dpnp/backend/examples/example9.cpp
- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/backend/kernels/dpnp_krnl_reduction.cpp
- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pyx
Make output array pointer as a first parameter of the function call.
In this case, all other parameters starting from second are input (const) parameters
> dpnpc_sum move result parameter to the front

- dpnp/backend/include/dpnp_gen_2arg_1type_tbl.hpp
- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/kernels/dpnp_krnl_bitwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_algo/dpnp_algo_bitwise.pyx
- parameters order changed
- 'const' added
- supported scalar as parameter to kernels
no tests for this case found
> Add scalar support in bitwise functions (partial)

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_indexing.pyx
- tests/test_indexing.py
tests/test_indexing.py::test_nonzero[[[1, 0], [1, 0]]] 
tests/test_indexing.py::test_nonzero[[[1, 2], [3, 4]]] 
tests/test_indexing.py::test_nonzero[[[0, 1, 2], [3, 0, 5], [6, 7, 0]]]
tests/test_indexing.py::test_nonzero[[[0, 1, 0, 3, 0], [5, 0, 7, 0, 9]]] 
tests/test_indexing.py::test_nonzero[[[[1, 2], [0, 4]], [[0, 2], [0, 1]], [[0, 0], [3, 1]]]] 
tests/test_indexing.py::test_nonzero[[[[[1, 2, 3], [3, 4, 5]], [[1, 2, 3], [2, 1, 0]]], [[[1, 3, 5], [3, 1, 0]], [[0, 1, 2], [1, 3, 4]]]]]
> add native version nonzero

- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/random/dpnp_algo_random.pyx
* left only dparray alloc and fptr call on cython layer
* update dpnp_rng_binomial_c
tests/test_random.py::TestDistributionsBinomial::test_extreme_value                                                                                                                                                       
tests/test_random.py::TestDistributionsBinomial::test_invalid_args
tests/test_random.py::TestDistributionsBinomial::test_moments
tests/test_random.py::TestDistributionsBinomial::test_seed
> ENH: update `random.binomial`

- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/src/dpnp_iterator.hpp
- dpnp/backend/src/dpnp_utils.hpp
- dpnp/backend/tests/CMakeLists.txt
- dpnp/backend/tests/dpnp_test_utils.hpp
- dpnp/backend/tests/test_broadcast_iterator.cpp
- dpnp/backend/tests/test_utils_iterator.cpp
- dpnp/dpnp_iface_mathematical.py
This PR shows current status of broadcasting implementation through USM iterator.
Currently issue below is under investigation:
```
DPNP_QUEUE_GPU=1 python -c "import dpnp; a = dpnp.array([7]); b = dpnp.array([7]); c = dpnp.multiply(a, b); print(c)"
Available SYCL devices:
- id=4466, type=8, gws=67108864, cu=12, name=Intel(R) FPGA Emulation Device
- id=32902, type=2, gws=8192, cu=12, name=Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
- id=32902, type=4, gws=256, cu=24, name=Intel(R) Graphics [0x9bca]
- id=32902, type=4, gws=256, cu=24, name=Intel(R) Graphics [0x9bca]
- id=32902, type=18, gws=1, cu=1, name=SYCL host device
Running on: Intel(R) Graphics [0x9bca]
queue initialization time: 0.000503686 (sec.)
SYCL kernels link time: 0.112728 (sec.)
terminate called after throwing an instance of …
```
> MULTIPLY enable broadcasting

- dpnp/backend/kernels/dpnp_krnl_random.cpp
update DPNPC lib `dpnp_rng_logistic_c` function:
* add `dpnp_rng_logistic_c_kernel`
* DPNP own
```
tests/test_random.py::TestDistributionsLogistic::test_invalid_args PASSED                                                                                                                                                             
tests/test_random.py::TestDistributionsLogistic::test_moments PASSED                                                                                                                                                                  
tests/test_random.py::TestDistributionsLogistic::test_seed PASSED 
```
* \+ numpy external
> ENH: update `random.logistic` backend; kernels

- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/random/dpnp_algo_random.pyx
Refactor: `radom.beta`, `radom.gamma`, `radom.geometric`, `radom.gumbel`, `radom.hypergeometric`, `radom.laplace`
* DPNP own:
```shell
tests/test_random.py::TestDistributionsBeta::test_invalid_args PASSED
tests/test_random.py::TestDistributionsBeta::test_moments PASSED
tests/test_random.py::TestDistributionsBeta::test_seed PASSED
tests/test_random.py::TestDistributionsGamma::test_invalid_args PASSED
tests/test_random.py::TestDistributionsGamma::test_moments PASSED
tests/test_random.py::TestDistributionsGamma::test_seed PASSED
tests/test_random.py::TestDistributionsGeometric::test_extreme_value PASSED
tests/test_random.py::TestDistributionsGeometric::test_invalid_args PASSED
tests/test_random.py::TestDistributionsGeometric::test_moments PASSED …
```
> MAINT: refactor `random` module

- dpnp/backend/kernels/dpnp_krnl_random.cpp
Enabled `random.multivariate_normal` on GPU.
* DPNP own
``` bash
tests/test_random.py::TestDistributionsMultivariateNormal::test_invalid_args PASSED
tests/test_random.py::TestDistributionsMultivariateNormal::test_moments PASSED
tests/test_random.py::TestDistributionsMultivariateNormal::test_output_shape_check PASSED
tests/test_random.py::TestDistributionsMultivariateNormal::test_seed PASSED 
```
> ENH: `random.multivariate_normal` enable on GPU

- dpnp/backend/kernels/dpnp_krnl_random.cpp
delegate sync on device
* dpnp own
```shell
tests/test_random.py::TestDistributionsStandardT::test_invalid_args PASSED
tests/test_random.py::TestDistributionsStandardT::test_moments PASSED
tests/test_random.py::TestDistributionsStandardT::test_seed PASSED 
```
* \+ numpy external
> ENH: update `random.standart_t`

- conda-recipe/meta.yaml
numpy-devel binds package with specific version of numpy.
It allows use dpnp package with different versions of numpy that needed by numpy-dppy CI.
> Replace numpy-devel with numpy

- dpnp/backend/kernels/dpnp_krnl_random.cpp
memcpy on device.
* DPNP own:
```shell
tests/test_random.py::TestPermutationsTestShuffle::test_shuffle[float32] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_shuffle[float64] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_shuffle[int32] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_shuffle[int64] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_no_miss_numbers[float32] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_no_miss_numbers[float64] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_no_miss_numbers[int32] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_no_miss_numbers[int64] PASSED
tests/test_random.py::TestPermutationsTestShuffle::test_shuffle1[ lambda x: dpnp.array([])] …
```
> ENH: update `random.shuffle`; on device

- scripts/install_python_deps.sh
Current version of MKL in conda "mkl-2021.2.0-h06a4308_296"
MKL version in Intel One API is "2021.3.0"
So, libraries could not be used simultaneously because DPNP uses python MKL but DPNPC uses intel one API MKL.
Direct linking with particular version of MKL looks impossible because lack of version support in MKL.
The library has the same file name in diffrent real versions
```
/home/work/anaconda3/lib/libmkl_core.so -> libmkl_core.so.1
and
/opt/intel/oneapi/mkl/2021.3.0/lib/intel64/libmkl_core.so -> libmkl_core.so.1
```
> MKL version mismatch in conda and intelOneAPI

- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_mathematical.py
No algorithm changes.
Simple replace "convert_result_scalar" with "convert_single_elem_array_to_scalar".
+support shape[1,1,1,1,1] in "convert_single_elem_array_to_scalar"
+few style improvements.
> replace conv2scalar function

- dpnp/dpnp_utils/dpnp_algo_utils.pxd
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
`axis` parameter might be a scalar. the function failed and throw Python exception "scalar is not iterable".
Integer to `dparray_shape_type` (std::vector) conversion attempted.
> scalar support in normalize_axis()

- dpnp/backend/kernels/dpnp_krnl_random.cpp
Enable computations on devices [CPU/GPU].
* DPNP own:
```shell
tests/test_random.py::TestDistributionsVonmises::test_moments[large_kappa] PASSED
tests/test_random.py::TestDistributionsVonmises::test_moments[small_kappa] PASSED
tests/test_random.py::TestDistributionsVonmises::test_invalid_args PASSED
tests/test_random.py::TestDistributionsVonmises::test_seed[large_kappa] PASSED
tests/test_random.py::TestDistributionsVonmises::test_seed[small_kappa] PASSED
```
* \+ numpy external
> ENH: kernels for `random.vonmisses`; part 1

- dpnp/dpnp_iface_manipulation.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraymanipulation.py
* fixed `vstack` and `hstack` fallback
* numpy like tests for `vstack` and `hstack`
> FIX: `vstack`, `hstack` fallback and tests

- dpnp/dpnp_iface_searching.py
* `dpnp.searchsorted`, `dpnp.where`. fallbacks to numpy
* cupy tests for `searchsorted`, `where`
* TODO: numpy tests will be moved to DPNP own
> ENH: `where`, `searchsorted`; fallbacks

- dpnp/linalg/dpnp_iface_linalg.py
Before these changes, dpnp_qr cause SIGSEGV in 1 of 10 test runs.
I'm pretty sure this is not a fix for this. It needs to be addressed later
> dpnp_qr cause SIGSEGV

- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
Cython does not support overloading by different function parameters type. So, new function name implemented.
> utils function refactoring. move to cdef

- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
* `convolve` fallback
* TestConvolve
* misc refactoring`tests/test_mathematical.py `
*
* DPNP own tests
> ENH: `dpnp.convolve` fallback; tests

- dpnp/dpnp_iface_manipulation.py
- tests/test_arraymanipulation.py
* `dpnp.concatenate` fallback
* examples
* tests (some numpy original tests, while we have issue with them)
* pasta some numpy original tests to `tests/test_arraymanipulation.py`, while we have issue with numpy testing
```bash
tests/test_arraymanipulation.py::TestConcatenate::test_returns_copy PASSED
tests/test_arraymanipulation.py::TestConcatenate::test_large_concatenate_axis_None PASSED
tests/test_arraymanipulation.py::TestConcatenate::test_concatenate PASSED
```
> ENH: `dpnp.concatenate` fallback; tests

- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
The most difficult things here are sizes calculation. It is not clear what size of an array should be used.
> use sycl_adapter in krnl_arraycreation

- tests/test_arraymanipulation.py
We can't pass `usm_ndarray` as parameter to `numpy.asfarray()`.
> Fix test test_asfarray and add test test_asfarray2

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/kernels/dpnp_krnl_reduction.cpp
- dpnp/backend/kernels/dpnp_krnl_sorting.cpp
- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
- dpnp/backend/src/constants.cpp
- dpnp/backend/src/constants.hpp
- dpnp/backend/src/dpnpc_memory_adapter.hpp
- dpnp/backend/src/memory_sycl.cpp
> MAINT: codesyle 9/14/2021

- tests/test_random.py
fix `IndexError: too many indices for array` in `tests/test_random.py::TestDistributionsMultivariateNormal::test_moments`
> BUG: fix IndexError in tests/test_random.py

- dpnp/dpnp_iface.py
- tests/test_strides.py
We need a workaround for inputs with strides because current implementations of functions in dpnp assume that data is c-contiguous without strides.
> Copy inputs if they have strides

- dpnp/dpnp_iface_manipulation.py
`call_origin` can convert sequence of array to sequence of ndarrays
> Fix "Arrays are not equal" part 1

- dpnp/dpnp_algo/dpnp_algo_statistics.pyx
- dpnp/dpnp_iface_counting.py
- dpnp/dpnp_iface_logic.py
Fix "ufunc 'isnan' not supported for the input types..."
> Fix "ufunc 'isnan' not supported for the input types..."

- tests/skipped_tests_gpu.tbl
This PR covers few others:
https://github.com/IntelPython/dpnp/pull/954
https://github.com/IntelPython/dpnp/pull/958
https://github.com/IntelPython/dpnp/pull/959
https://github.com/IntelPython/dpnp/pull/977
Some additional information can be found in them, but it can be not actual (as changes themselves too)
> Skip tests for unsupported funcs due to migration to dpctl container

- .github/workflows/conda-package.yml
- conda-recipe/meta.yaml
> Use Python 3.9 [public CI]

- dpnp/dpnp_iface_arraycreation.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
* removed dpnp error raise, fallback when order is not c contiguous
DPNP error: in function asanyarray() paramenter 'order' expected `C`, but 'None' provided -> 'int' object has no attribute 'c_contiguous'
* disabled tests for ['int' object has no attribute 'c_contiguous']. See `Reproduce dpctl usm_array flags` below
```bash
tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asanyarray_with_order
tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asarray_from_numpy
tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asarray_with_order
```
FAILED tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_asanyarray_with_order
```bash
tests/third_party/cupy/creation_tests/test_from_data.py:365: in …
```
> BUG: fix asanyarray fallback + disabled tests

- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
As DPL/PSTL developers say, the correct way is to provide such unique classes for naming in each kernel. They can be removed at all, but in this case name for kernel will be generated automatically and it will be very long and impossible to read.
I tried to do so and debug become a hell.)
> Changing kernel names to be compatible with latest dpl/pstl

- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/verbose.cpp
- dpnp/backend/src/verbose.hpp
`cl::sycl::vector_class` is deprecated.
We should use `std::vector` instead of it.
> replace deprecated sycl::vector_class with std::vector

- dpnp/backend/src/queue_sycl.hpp
Use `__has_include` to minimize disruption that the said reorg may cause.
> prep for dpctl/include reorg (IntelPython/dpctl#685)

- dpnp/backend/examples/example11.cpp
Merging this is not necessary.
This PR is just for reproducing DPNPC backend lib shuffle logic for 1dim and 2dim (ndim) arrays.
1) array size = 100, ndim = 1, high_dim_size = 100 (aka `ndarray` with shape `(100,)` )
2) array size = 100, ndim = 2, high_dim_size = 20 (for example `ndarray` with shape `(20, 5)` and len(array) = 20 )
> REPRODUCER: shuffle as an example

- conda-recipe/meta.yaml
The workflow uses following channels for build:
https://github.com/IntelPython/dpnp/blob/457a5984712d28e73531fd70e482c099fe87d2c8/.github/workflows/conda-package.yml#L48
At the same time recipe requires concrete numpy version:
https://github.com/IntelPython/dpnp/blob/457a5984712d28e73531fd70e482c099fe87d2c8/conda-recipe/meta.yaml#L11 
I have relaxed requirements for numpy version in conda recipe because `defaults` channel does not have `numpy 1.19.5` (only `1.19.2`).
> Relax build dependency to numpy

- conda-recipe/meta.yaml
For some reason on Windows `conda list` command in test section in recipe finish testing and prevent execution of other commands below in this section.
> remove conda list command from test section in meta.yaml

- conda-recipe/meta.yaml
* dpnp can be compatible with all libaries of a specific major version
> Loosen pinning of MKL and compiler runtimes to just major version

- dpnp/backend/kernels/dpnp_krnl_fft.cpp
- dpnp/fft/dpnp_iface_fft.py
- tests/test_fft.py
Support ifft function and norm as "backward", "forward", "ortho" for fft and ifft.
> add ifft support

- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/linalg/dpnp_algo_linalg.pyx
- dpnp/linalg/dpnp_iface_linalg.py
- tests/skipped_tests_gpu.tbl
- tests/test_linalg.py
DPNP function "linalg.qr" raised an exception when running in mode='reduced'.
DPNP backend kernel for "linalg.qr" crashed with a core dump for m*n matrix when m>n.
> Function "linalg.qr" raised an exception with mode='reduced'

- dpnp/backend/CMakeLists.txt
Use `-fno-fast-math` to ensure that device code uses accurate transcendentals
Use of this compiler option ensures that accurate code for computing transcendental functions in single precision is used.
This ensures that `dpnp.cos(dpnp.asarray([2], 'float32'))` is close to NumPy's result.
> Fix precision issues with single precision transcendentals

- dpnp/backend/CMakeLists.txt
Use of `-fno-fast-math` is too strong of a hammer to ensure accurate evaluation of transcendental functions. 
This compiler option is also not recognized on Windows (need a different one).
Instead it was suggested to use more targeted `-fno-approx-func` which applies to both platforms.
> Transcendental precision control

- tests/test_sycl_queue.py
Do not test on host device for now. Also make sure to skip rejected devices.
DPL may throw an exception if execution at host device is requested. 
These exceptions must be caught, but this is a subject for a future PR.
> Do not test on host device in test_sycl.py for now

- dpnp/backend/kernels/dpnp_krnl_common.cpp
GEMM to use trans only if matrix if not C-contig.
Fixed logic for determining `transA` and `transB` in call to `gemm`
> GEMM to use trans only if matrix if not C-contig

- dpnp/dpnp_algo/dpnp_algo_indexing.pyx
`dpnp_take` must use data-type of both arguments to deduce the function pointer type.
> Corrected logic for kernel function pointer lookup for dpnp_take_c

- dpnp/backend/kernels/dpnp_krnl_random.cpp
Add a null-terminated symbol at the end of char array to avoid "Improper Null Termination" issue reported by Checkmarx scan.
> Get rid of "Improper Null Termination" issue

- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
tests/third_party/cupy/statistics_tests/test_order.py::TestOrder::test_ptp_all_nan
tests/third_party/cupy/statistics_tests/test_order.py::TestOrder::test_ptp_nan
Need to skip them because CI does not work due to this.
> Skip for two more tests till waiting fix

- .github/workflows/conda-package.yml
- conda-recipe/bld.bat
- conda-recipe/meta.yaml
- scripts/build_conda_package.sh
- utils/dpnp_build_utils.py
Introduced DPNP build for Windows through git workflow action.
Added upload action for the build towards dppy channel upon the merge.
Both is implemented for python 3.8 and 3.9.
> Add git workflow factions or Windows

- .github/workflows/conda-package.yml
It is required to explicitly define default shell when installing miniconda with "conda-incubator" action and "activate-environment: true" used. The action will update default shell to run each next step run inside created conda environment.
Otherwise (without shell option defined) it will require activate the environment inside each next run additionally.
No need to pass "auto-activate-base: true", since specific environment is created per each target step and so "base" environment is never used in the step runs.
> Set default shell in upload actions

- conda-recipe/bld.bat
DPNP build on Windows was previously successful in internal CI where setuptools=58.0.4. The same setuptools version is currently used in intel channel of Anaconda.
Switching to newer version setuptools=63.4.1 in internal CI broke the build flow due to non-backward compatible changed released in setuptools=60.0.0.
To prevent this and keep the legacy setuptools behavior, a workaround with setting environment variable SETUPTOOLS_USE_DISTUTILS="stdlib" is implemented.
> [Build] setuptools 63.4.1 breaks build for Windows

- README.md
Update the README to add some extra information on how to build dpnp from source.
> Add extra information on how to build dpnp from source.

- dpnp/__init__.py
In case of Windows OS t is required to explicitly define a path where to search for DLLs towards both DPNP backend and DPCTL Sycl interface, otherwise the DPNP import will fail. This is because the libraries are not installed under any of default paths where Python is looking for.
Python 3.10 modifies the behavior on how it looks for DLLs to make it more secure. An environment variable PATH isn't longer used as default DLL search location. Library provides must add it to DLL search path using 'add_dll_directory' utility for Python's internal dynamic library opener to be able to find it.
The solution working with all supported pythons is supposed to be a combination of two approaches with extending PATH env variable and with calling os.add_dll_directory() if available.
> Fix import dpnp on Win & python 3.10

- .github/workflows/conda-package.yml
In order to run the tests scope on Windows platform from the github action, it's required to modify OpenCL RT configuration file to explicitly define a path towards TBB DLLs location.
The previous solution was based on setting environment variable TBB_DLL_PATH, which doesn't work with new OpenCL RT (since 2022.2.0 version).
In additional, minor cosmetic changes relating to environment variables usage were implemented.
> Missing path towards TBB DLLs on Windows

- .github/workflows/conda-package.yml
- dpnp/dpnp_iface_libmath.py
A missing part of compute follows data implementation was added for dpnp.erf function.
Tests for dpnp.erf validation was included into a scope of checks triggered on both Linux and Windows platforms by github action. It's enough to secure the fix is working, since the tests running on CPU device with the latest DPCtl from dppy/label/dev channel reproduce the same fault as reported in #1192.
> Fix missing support of compute follows data in dpnp.erf

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .gitignore
- doc/conf.py
- doc/reference/fft.rst
- doc/reference/ndarray.rst
- doc/reference/polynomials.rst
Since spinx 5.0.0, autosummary extension will trigger an error if any input rst file includes unknown module.
Thus, as a fix. the modules which aren't currently implemented in DPNP have been commented in the rst files.
Additionally build docs action will be partly running on each push request (excluding deploy step) now. It should help to find an issue similar to the fault observing with a newer spinx version on early stage (previously the action was running on PR merge only).
> Fix github action for building docs

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/pre-commit.yml
Updated action versions to pick up update from EOL node-12 to node-16.
> Updated actions per prompt from GitHub

- dpnp/dpnp_array.py
- dpnp/dpnp_container.py
- dpnp/dpnp_iface.py
- tests/test_sycl_queue.py
DPNP must adhere Compute Follows Data programming model, meaning among other things, that a copy of input array has to be created on the same device and with the same queue as the input array had unless either device or queue is passed explicitly and with different value.
To reproduce the issue:
```
import dpnp, dpctl
dpctl.get_devices()
Out:
[<dpctl.SyclDevice [backend_type.opencl, device_type.gpu,  Intel(R) UHD Graphics [0x9bca]] at 0x7fb5007d9070>,
<dpctl.SyclDevice [backend_type.level_zero, device_type.gpu,  Intel(R) UHD Graphics [0x9bca]] at 0x7fb5006f0d30>]
dpctl.tensor.Device.create_device(None)
Out:
Device(level_zero:gpu:0)
data = dpnp.empty((4, 4), device="opencl:gpu")
data.sycl_device
Out:
<dpctl.SyclDevice [backend_type.opencl, device_type.gpu,  Intel(R) UHD Graphics [0x9bca]] …
```
> Align normalize_queue_device call with CFD

- .github/workflows/conda-package.yml
- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/backend/kernels/dpnp_krnl_fft.cpp
- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/fft/dpnp_algo_fft.pyx
- dpnp/fft/dpnp_iface_fft.py
- dpnp/linalg/dpnp_algo_linalg.pyx
- dpnp/linalg/dpnp_iface_linalg.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_fft.py
- tests/test_linalg.py
- tests/test_sycl_queue.py
The PR is intended to apply Compute Follows Data approach for all supported DPNP functions of `fft` and `linalg` libraries.
- The implemented changes include an adaptation in python, cython and backend parts associated with `fft` and `linalg` functionality.
- Additional tests are introduced in `test_sycl_queue.py` to secure Compute Follows Data support for `fft` and `linalg` in DPNP. The new tests assume running checks for equality of underlying `backend`, `sycl_device`, `sycl_context` and properties of argument sycl queues at the end of verifying sequence.
- The tests from `test_fft.py`, `test_linalg.py` and `test_sycl_queue.py` (covering `fft` and `linalg` functionality) are added to a validation jobs running as github actions per each commit in DPNP.
> Enable Compute Follows Data in Cython in fft and linalg

- conda-recipe/meta.yaml
Update numpy restrictions because now dpnp is still building with numpy 1.21 instead 1.22
> update numpy restriction by adding numpy 1.22

- conda-recipe/meta.yaml
Update numpy restrictions because now dpnp is still building with numpy 1.21 instead 1.22. This PR backport changes added in https://github.com/IntelPython/dpnp/pull/1207 to fix for gold/2021
> update numpy restriction by adding numpy 1.22 (backport PR1207 to gold/2021)

- dpnp/config.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
DPNP has a run dependency on DPCTL from meta.yaml, assuming `dpctl.tensor` has to be deployed when DPNP is running.
There is no need to have an environment variable `__DPNP_OUTPUT_DPCTL__`, which controls if a function from `dpctl.tensor` module can be used.
This PR is some kind of clean up to remove code relating to the obsolete environment variable `__DPNP_OUTPUT_DPCTL__`.
> Get rid of env var which handles dep on dpctl.tensor

- conda-recipe/meta.yaml
Remove a temporary pinning of `dpcpp-cpp-rt` on `2022.2.0` version.
It safely to update configs of internal CI to be able to build DPNP release `0.10.3`, rather than modifying `meta.yaml`.
> Remove temporary pinning of 'dpcpp'

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- 0.build.sh
- conda-recipe/meta.yaml
DPNP requires OneDPL headers during the build step.
Previously the headers fetch from OneDPL github repo prior the build in external CI or alternatively there was a shared folder where the headers located on the host. In both cases a path towards the files location is handled through DPLROOT environment variable. The variable needs to be defined/added to the environment prior the build.
The new solution proposed to install a package with OneDPL files required for build. The package is available on both external (`intel` on Anaconda) and internal channels. Thus it's only required to define a host dependency on `onedpl-devel` package in `meta.yaml` file of DPNP. The files will be installed following by default `$CONDA_PREFIX` root, so no additional include path is required to define for the …
> Define OneDPL package as a host dependency in meta.yaml

- tests/skipped_tests_gpu.tbl
- utils/command_build_clib.py
SYCL DPC++ 2023 compiler introduces alternative names for sycl.lib on Win OS.
The PR adds a support of this while building DPNP backend.
> Add support of DPNP backend linking with sycl6.lib on Win

- dpnp/dpnp_array.py
- tests/test_random_state.py
- tests/test_sycl_queue.py
Adds dpnp_array.usm_type property in dpnp.
> dpnp_array must expose usm_type

- dpnp/backend/src/dpnp_utils.hpp
- dpnp/backend/src/dpnpc_memory_adapter.hpp
Since SYCL DPC++ 2023 compiler the function is_host() is deprecated as the host device is no longer supported.
The PR excludes is_host() call from the code when the new compiler is used, i.e. when `__SYCL_COMPILER_VERSION < 20221102L`.
> Leave is_host() call with old compiler only

- doc/conf.py
- dpnp/backend/CMakeLists.txt
- dpnp/backend/doc/Doxyfile
- dpnp/version.py
Switch DPNP version to `0.11.0` for upcoming 2023.0 release
> Setting version to 0.11.0

- .github/workflows/conda-package.yml
- doc/conf.py
- dpnp/backend/CMakeLists.txt
- dpnp/backend/doc/Doxyfile
- dpnp/backend/src/dpnp_utils.hpp
- dpnp/backend/src/dpnpc_memory_adapter.hpp
- dpnp/backend/src/queue_sycl.cpp
- dpnp/dpnp_array.py
- dpnp/version.py
- tests/test_arraycreation.py
- tests/test_random_state.py
- tests/test_sycl_queue.py
Merge latest changes from master to `gold/2021`.
> Merge changes from master to gold

- conda-recipe/meta.yaml
Revert merge branch 'gold/2021' into `master` done by a [commit](https://github.com/IntelPython/dpnp/commit/a9f45e3111684e56848472e309eea93f46359d38).
> Revert merge gold/2021 to master

- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/dpnp_utils.hpp
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
The PR is intended to get rid of deprecation warnings while compiling with the latest OneMKL.
The warnings advise to replace `std::vector()` with `sycl::span()` when `oneapi::mkl::rng::multinomial` and `oneapi::mkl::rng::gaussian_mv` constructors are called.
> Replace std::vector() with sycl::span() by prompt from OneMKL

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
Updated remaining actions with the latest version to pick up update from EOL node-12 to node-16 and `set-output` command.
1. conda-incubator/setup-miniconda: `v2.1.1` -> `v2.2.0`
2. peaceiris/actions-gh-pages: `v3.8.0` -> `v3.9.0`
3. actions/upload-artifact: `v3.1.0` -> `v3.1.1`
4. actions/download-artifact: `v3.0.0` -> `v3.0.1`
> Use the latest version of external github actions

- .github/workflows/conda-package.yml
Upload steps shan't be running when merging in forked repositories.
> Exclude running upload steps for forked repo

- .github/workflows/conda-package.yml
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- tests/test_usm_type.py
The PR implements a support of combining arrays with different USM types.
The change is mainly about to replace temporary dpnp call `get_usm_type()` with dpctl API call `dpctl.utils.get_coerced_usm_type()`, since it is available now.
> Add support of combining arrays with different USM types

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/dpnp_utils.hpp
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_usm_type.py
Merge fixes for compiling warnings from SYCL DPC++ 2023 and a major fix in #1237 for Compute Follows Data functionality.
> Merge master into gold/2021

- .github/workflows/conda-package.yml
It's proper to explicitly define `main` channel when installing packages from conda rather than to rely on a value of `defaults` channel in conda configuration.
This is because `main` channel is what exactly required for building and testing dpnp and also because conda is configured by `conda-incubator/setup-miniconda` github action and we have no control on that (can't guarantee `defaults` channel is the same as `main` one).
> Use main channel instead of defaults

- .github/workflows/build-sphinx.yml
- 0.build.sh
- dpnp/backend/CMakeLists.txt
- scripts/azure-pipelines.yml
- utils/command_build_clib.py
Since SYCL DPC++ 2023 compiler use of `dpcpp` is deprecated and will be removed in a future release.
The PR replaces `dpcpp` with use of 'icpx -fsycl' in case of building for Linux OS.
> Use icpx instead of dpcpp on Linux

- .github/workflows/conda-package.yml
Extended github actions flow to validate `dpnp` build on Linux and with python 3.10 in public CI.
Also, matrix in build and upload steps is extended to combine jobs for Linux and Windows, since the entire steps are very equal.
The remaining things to do in later commits:
1. build on Windows, once `dpctl` package for python 3.10 and Windows is available
2. test on both Linux and on Windows, once `mkl` packages for python 3.10 are published in `intel` channel
3. publishing `dpnp`  for python 3.10 in `dppy/label/dev` channel, once test step is done
> Build on LInux with python 3.10 in public CI

- dpnp/dpnp_iface_linearalgebra.py
- tests/skipped_tests_gpu.tbl
- tests/test_outer.py
- tests/test_sycl_queue.py
As was reported in issue #1203, `dpnp.outer()` is falling back on numpy call. This is because DPNP called multiplication function in a loop per each pair of elements from input vectors. While `dpnp.__mul__()` is falling on numpy if an input argument is a scalar.
The PR is intended to improve `dpnp.outer()` logic. It can be enough to invoke `dpnp.__mul__()` only once with both arguments as `dpnp_array`, instead of the looping over the elements.
> Improve logic of dpnp.outer()

- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
The TR is about to implement an enhancement suggested in issue #1245.
New `asnumpy()` method of `dpnp_array` class is an equivalent of `dpnp.asnumpy()` call.
> Add asnumpy() method for dpnp_array

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
- dpnp/dpnp_container.py
- dpnp/dpnp_iface_arraycreation.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraycreation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/creation_tests/test_basic.py
- tests/third_party/cupy/statistics_tests/test_correlation.py
Use zeros() function from dpctl.tensor module instead of DPNP backend implementation.
A cython code relating to zeros() call is cleaned up.
> Use zeros() function from dpctl.tensor.

- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/backend/src/dpnp_utils.hpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_arraycreation.pyx
- dpnp/dpnp_container.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_random_state.py
- tests/test_arraycreation.py
- tests/test_random_state.py
The PR is to implement a dependency of default data type in creation functions on what is supported by target device.
The device may not support any of types: `dpnp.float16`, `dpnp.float64` or `dpnp.complex64`. Thus `dpnp` has to consider that when it's requested to create an array with default data type. The type should be selected only among supported ones by the device.
If a data type is passed explicitly in array creation function but the selected device doesn't support the type, an exception will be raise by `dpnp` indicating the issue.
> Map dtype to device in array creation functions

- dpnp/random/dpnp_random_state.py
Added missing description for `device` and `sycl_queue` parameters and implemented minor improvements in existing description text.
> Update description of functions in RandomState class

- dpnp/dpnp_array.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraycreation.py
- tests/test_dparray.py
Added property flags to dpnp_array by using dpctl.tensor.usm_ndarray.flags.
> Add property flags to dpnp_array

- .github/workflows/conda-package.yml
Extended github actions flow to complete validation support of `dpnp` build on Windows and Linux and with python 3.10 in public CI (completed work started in #1244).
Th PR includes steps with python 3.10 and
1. build on Windows
2. test on both Linux and Windows 
3. publishing `dpnp` for python 3.10 in `dppy/label/dev` channel, once test step is done
> Complete support of python 3.10 in external CI

- 0.build.sh
- dpnp/backend/CMakeLists.txt
- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/kernels/dpnp_krnl_fft.cpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/dpnp_utils.hpp
- dpnp/backend/src/dpnpc_memory_adapter.hpp
- dpnp/backend/src/queue_sycl.cpp
- dpnp/backend/src/queue_sycl.hpp
- dpnp/dpnp_algo/dpnp_algo.pyx
The PR implements a similar fix for debug building with introducing link option `-fsycl-link-huge-device-code`, as described in PR [#1028](https://github.com/IntelPython/dpctl/pull/1028) for `dpctl`.
Additionally `TMP` environment variable were set to a source directory in case of debug build in `0.build.sh` script to redirect a path where the compiler creates temporary files, since default `/tmp` location is limited and the size is not enough to keep all the generated files there.
Removed use of `__SYCL_COMPILER_2023_SWITCHOVER` and `__INTEL_MKL_2023_SWITCHOVER` preprocessor constants and introduced `__SYCL_COMPILER_VERSION_REQUIRED` and `__INTEL_MKL_2023_VERSION_REQUIRED` instead to ensure that the compiler or MKL meets the minimum required version where required.
Also few minor …
> Set minimum required versions & fix debug building

- dpnp/backend/include/dpnp_gen_2arg_2type_tbl.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_logic.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_logic.pyx
- dpnp/dpnp_iface_logic.py
- tests/test_linalg.py
- tests/test_logic.py
- tests/test_random.py
- tests/test_random_state.py
- tests/test_sycl_queue.py
- tests/third_party/cupy/logic_tests/test_comparison.py
This PR is to introduces a support of comparison operations in dpnp and covers functions:
1. dpnp.equal()
2. dpnp.greater()
3. dpnp.greater_equal()
4. dpnp.less()
5. dpnp.not_equal()
The PR continue the work started in #1275.
> Add support of comparison operations

- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_types.py
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- tests/helper.py
- tests/test_arraycreation.py
The PR assumes that array creation functions will be tested in positive scenarios with a list of only supported types (which is based on capability of a default device where the tests are executing on).
Previously, the tests include list of all possible types and they check if an exception is raised by dpctl when a type is out of support on target device.
Instead, the PR proposes to use a common parametrization approach to iterate over the list of supported types, like:
```
@pytest.mark.parametrize("dtype", get_all_dtypes())
```
Additionally, an existing dpnp function `dpnp.default_float_type()` is updated to consider the device capabilities in return type.
> Get rid of testing the array creation functions with unsupported types by a default device in positive scenarios

- dpnp/backend/include/dpnp_gen_1arg_1type_tbl.hpp
- dpnp/backend/include/dpnp_gen_2arg_2type_tbl.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_logic.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_logic.pyx
- dpnp/dpnp_iface_logic.py
- tests/helper.py
- tests/skipped_tests_gpu.tbl
- tests/test_logic.py
- tests/third_party/cupy/logic_tests/test_comparison.py
- tests/third_party/cupy/logic_tests/test_ops.py
This PR is to introduces a support of logical comparison operations in dpnp and covers functions:
1. dpnp.logical_and()
2. dpnp.logical_or()
3. dpnp.logical_xor()
4. dpnp.logical_not()
The PR continue the work started in #1278.
> Add support of logical comparison operations

- dpnp/dpnp_iface_arraycreation.py
- tests/test_arraycreation.py
dpctl.tensor array support returned for function: dpnp.empty_like(), dpnp.full_like(), dpnp.ones_like(), and dpnp.zeros_like().
> Fixed gh-1272

- dpnp/random/dpnp_random_state.py
- tests/third_party/cupy/random_tests/test_sample.py
This PR implements support of `high=None` in `dpnp.random.randint()` function.
> Add support of high=None in dpnp.random.randint() function

- dpnp/dpnp_array.py
- tests/test_dparray.py
This PR implements missing `dpnp.__index()__` and `dpnp.__complex__()` functions to support `__index__` and `__complex__` operation with dpnp array appropriately.
> Add operation __index__ and __complex__

- tests/test_sycl_queue.py
The PR fixes incorrect call of dpctl.SyclQueue() function with device keyword from `dpnp` test.
The issue breaks `dpnp` tests since PR [#1052](https://github.com/IntelPython/dpctl/pull/1052), where `dpctl` introduced a validation check which will raise an exception if any keyword passed in `SyclQueue` constructor.
> Update tests with proper call of dpctl.SyclQueue()

- conda-recipe/meta.yaml
Since `dpnp` is now built with oneAPI DPC++ 2023.0, the required RT version and MKL version should change accordingly.
Also step `dpctl` version due to dependency on latest functionality.
> Update minimum required versions of dependent components

- dpnp/dpnp_array.py
- tests/test_dparray.py
Adding string representation of the array object using `__str__` and `__repr__`
> Print dpnp array

- dpnp/backend/include/dpnp_gen_2arg_3type_tbl.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraycreation.py
- tests/test_mathematical.py
- tests/test_usm_type.py
- tests/third_party/cupy/creation_tests/test_from_data.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
Since the change implemented in #1201 and until now, implicit `operation -` of array with a scalar or explicit one through `dpnp.subtract` leads to raising of the not-implemented exception in dpnp. This is because dpnp was falling back on NumPy implementation in that use case, but has to call an internal kernel function from the backend.
The issue was reported in https://github.com/IntelPython/dpnp/issues/1273.
The PR proposes to copy a scalar data from host memory into USM allocated memory, which means to create zero-dimension dpnp array from the scalar. This way the subtraction of array with a scalar will be handled in the same way as subtraction of two arrays, which already works fine in dpnp.
Note that if some input argument is a scalar and another one is an array, memory for the …
> dpnp.subtract() doesn't work properly with a scalar

- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- tests/helper.py
- tests/test_dparray.py
- tests/test_sycl_queue.py
This PR closes #1291 
The PR adds **__dlpack__** and **__dlpack_device__** protocols to dpnp_array and implements **dpnp.from_dlpack** function including tests and docstrings.
> Add dlpack support

- 0.build.sh
This PR updates `0.build.sh` script to fix compilation issue with `example3.cpp` due to missing includes towards `dpctl` headers.
> Update example3 building from debug build script

- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- tests/test_sycl_queue.py
In terms of compute follows data paradigm it is prohibited to manipulate data if they were allocated on the same device and if they have the same SYCL context, but different SYCL queues.
The PR removes a temporary solution existing in the code which assumed the same SYCL context but different queues as valid and as following the paradigm. But that isn't needed anymore and potentially might be dangerous.
> Remove temporary solution accepting CFD with equal SYCL context instead of queue

- conda-recipe/build.sh
Use compiler CFG files for Intel LLVM to use conda's `sysroot` and `toolchain`.
The fix is based on a solution implemented in `dpctl`.
> Intel LLVM is to use conda's gcc toolchain, sysroot and target libraries

- dpnp/backend/src/queue_sycl.hpp
- dpnp/dpnp_algo/dpnp_algo.pxd
This PR adds a protection check to resolve a crash while running `dpnp` test scope when no device is available.
Since function `DPCTLQueueMgr_GetCurrentQueue()` will return a null pointer in that case.
> Tests are crashing if no default device

- doc/conf.py
- dpnp/backend/CMakeLists.txt
- dpnp/backend/doc/Doxyfile
- dpnp/version.py
Switch DPNP version to `0.11.1` for upcoming 2023.1 release
> Setting version to 0.11.1

- dpnp/dpnp_array.py
Needs to pass exactly `usm_ndarray` when calling dpctl indexer operators rather than to pass `dpnp_array`.
> Unwrap dpnp array while calling dpctl indexer operators

- dpnp/dpnp_iface_manipulation.py
- tests/test_arraymanipulation.py
This PR adds new logic for dpnp.asfarray function to return floating type depending on the device capabilities if the input array has an integer or boolean type.
These changes are necessary to support work on Iris Xe.
Subtask for #1294
> Change dpnp.asfarray to run on Iris Xe

- .gitignore
- dpnp/backend/kernels/dpnp_krnl_logic.cpp
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_logic.py
- tests/test_arraycreation.py
- tests/test_logic.py
- tests/test_usm_type.py
This PR proposes to update implementation of `dpnp.all()` and to make it compliant with compute follows data paradigm. It includes changes:
- to get rid of unnecessary temporary memory copy into shared USM memory
- to remove direct use of host memory when assigning a value into `result` array
- to add missing `DPCTLEvent_Delete()` call in `dpnp_all_c()` API function
- to rework the kernel function with subgroup and `sycl::joint_none_of()`
- to support `dpnp.complex64` and `dpnp.complex128` data types
The PR continues work started in #1155 and is aimed to substitute it.
> Remove mixed host\dev implementation from dpnp.all()

- dpnp/backend/kernels/dpnp_krnl_fft.cpp
Passing the same object of FFT descriptor to FFT compute functions `compute_backward()` and `compute_forward()` which are executing in parallel might cause an undefined behavior and race condition.
A possible was to reproduce the issue is to run following `dpnp` test:
```
tests/test_sycl_queue.py::test_fft_rfft[opencl:gpu:0-shape0-float32]
```
The PR proposes to dynamically allocate FFT descriptors and commit every one on queue. The committed descriptors will be separately passed to FFT compute functions executing in parallel.
> Allocate a separate FFT descriptor per FFT compute function

- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_algo/dpnp_algo_statistics.pyx
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/dpnp_iface_types.py
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- dpnp/linalg/dpnp_algo_linalg.pyx
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_arraycreation.py
- tests/test_dparray.py
- tests/test_random_state.py
The list of missing aliases on numpy types are ported to dpnp:
- cdouble
- complex_
- complexfloating
- cfloat
- csingle
- double
- float_
- floating
- inexact
- int_
- intc
- number
- object_
- signedinteger
- single
- singlecomplex
The flowing type-related functions are added to dpnp:
- issubdtype
- issubsctype
The following constants are borrowed from numpy:
- e
- euler_gamma
- Inf
- inf
- Infinity
- infty
- NAN
- NaN
- NINF
- NZERO
- pi
- PINF
- PZERO
This PR is intended to resolve issue #1307.
> Add missing dtype aliases

- .github/workflows/conda-package.yml
- dpnp/backend/kernels/dpnp_krnl_bitwise.cpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
The PR removes excess memory copy of shapes and strides to shared memory for elementwise and bitwise `dpnp` functions.
USM-host allocator is used to transfer strides data from the host to device memory.
The shaped data isn't required to be moved into device memory at all.
> Excess memcpy to shared memory in elementwise and bitwise functions

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_indexing.pyx
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_searching.py
- tests/skipped_tests_gpu.tbl
The PR reworks `dpnp.nonzero` implementation to invoke `dpctl.tensor.nonzero` function for an input array.
Also a missing `nonzero` method of `dpnp_array` class is implemented.
> Reuse dpctl.tensor implementation for dpnp.nonzero()

- dpnp/dpnp_iface_manipulation.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraymanipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
The PR adds `broadcast_to` function to `dpnp`.
The function is implemented to invoke `dpctl.tensor.broadcast_to` if possible.
> Add dpnp.broadcast_to() function

- dpnp/dpnp_iface_indexing.py
- tests/__init__.py
- tests/helper.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_indexing.py
- tests/third_party/cupy/indexing_tests/test_indexing.py
- tests/third_party/cupy/testing/helper.py
This PR adds support  of `dpnp.extract()` function in dpnp that reuses `dpctl.tensor.extract()` implementation.
> Add support of dpnp.extract()

- dpnp/backend/CMakeLists.txt
- setup.py
Since `dpnp_algo.pyx` includes a bunch of other `.pyx` files, build generator needs to be aware of such dependency to correctly perform incremental builds.
> Set dependencies for dpnp_algo Cython extension to account for files involved via use of include 

- dpnp/backend/kernels/dpnp_krnl_bitwise.cpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/kernels/dpnp_krnl_logic.cpp
- dpnp/backend/kernels/dpnp_krnl_searching.cpp
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_utils/dpnp_algo_utils.pxd
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- tests/test_mathematical.py
- tests/test_strides.py
- tests/test_umath.py
The PR is about to improve handling of `out` parameter in supported `dpnp` functions.
It's required to consider use cases when
- `out` refers to the same array as any of input ones
- `out` with strides
- `out` where dtype is different from expected one
In both cases extra memory is allocated and it's need to copy the result back from temporary array into `out` array.
> Support more use cases for 'out' parameter

- dpnp/dpnp_container.py
- tests/test_sycl_queue.py
close #1345 
Allow asarray to work on sequences of dpnp_array with support compute-follows-data.
> Allow asarray to work on sequences of dpnp_array

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_strides.py
- tests/test_usm_type.py
The PR implements support of `out` in-place parameter for `dpnp.add` function.
Additionally `__iadd__` function of `dpnp_array` class is added.
> Support parameter out in dpnp.add()

- dpnp/dpnp_array.py
- tests/test_indexing.py
The PR is about to close #1354.
It introduces `nbytes` as a property of dpnp array.
> Implement 'nbytes' property of dpnp array

- dpnp/dpnp_iface_statistics.py
- tests/test_statistics.py
Closes  #1367 
`rowvar` keyword is added to `dpnp.cov` function 
`dpnp.dpnp_array.dpnp_array._create_from_usm_ndarray(x.get_array().mT)` is used since it is faster than `dpnp.transpose(x)` since dpnp.tarnsport 
`%timeit dpnp.cov(dpnp.dpnp_array.dpnp_array._create_from_usm_ndarray(x.get_array().mT))`
5.4 ms ± 121 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
` %timeit dpnp.cov(dpnp.transpose(x))`
9.46 ms ± 455 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
`%timeit dpnp.cov(x, rowvar=False)`
5.49 ms ± 352 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
> using rowvar keyword in dpnp.cov

- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
- dpnp/dpnp_algo/dpnp_algo_statistics.pxi
- dpnp/dpnp_iface_statistics.py
- tests/test_statistics.py
- tests/third_party/cupy/statistics_tests/test_correlation.py
closes issue #1379 
In this PR, `dpnp.cov` is modified to work on GPUs that only support `float32`.
> fix_cov_for_no_fp64

- dpnp/backend/include/dpnp_gen_1arg_1type_tbl.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/src/dpnp_fptr.hpp
- tests/test_strides.py
OneMKL VM functions copy data to the host when a device doesn't provide support of fp64, which might impact the performance.
The PR propose to use internal DPNP kernel instead of VM function from OneMKL in that case.
> Use internal dpnp kernel instead of MKL if no FP64 support

- .gitignore
- dpnp/CMakeLists.txt
- dpnp/backend/CMakeLists.txt
- dpnp/backend/extensions/lapack/CMakeLists.txt
- dpnp/backend/extensions/lapack/heevd.cpp
- dpnp/backend/extensions/lapack/heevd.hpp
- dpnp/backend/extensions/lapack/lapack_py.cpp
- dpnp/backend/extensions/lapack/syevd.cpp
- dpnp/backend/extensions/lapack/syevd.hpp
- dpnp/dpnp_iface.py
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- tests/skipped_tests_gpu.tbl
- tests/test_linalg.py
- tests/test_sycl_queue.py
- tests/third_party/cupy/creation_tests/test_ranges.py
- tests/third_party/cupy/linalg_tests/test_eigenvalue.py
- tests/third_party/cupy/testing/helper.py
The PR is about to close #1344, since it covers the last functional gap of `pca` benchmark.
PR adds a missing `dpnp.linalg.eigh()` function to calculate the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric input matrix. OneMKL LAPACK library is used for that.
The implementation is written as a pybind11 extension above required LAPACK functions.
This is a base PR which assumes to be extended later with remaining functions from OneMKL LAPACK library, once new functionality required.
Numbers for a laptop with Iris Xe:
```
import dpnp, numpy
sh = (2024, 2024)
a = numpy.random.uniform(-1, 1, sh) + 1.j * numpy.random.uniform(-1, 1, sh)
a = a.astype(numpy.complex64)
x = numpy.matrix(a)
nx = x.getH()
%timeit _, _ = numpy.linalg.eigh(nx)
Out: 2.21 s ± …
```
> Add dpnp.linalg.eigh() function

- conda-recipe/meta.yaml
Temporarily do not use DPC++ 2023.2.0 for conda build until an issue with it is solved.
> Not use DPC++ 2023.2.0 for conda build

- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/backend/src/dpnp_utils.hpp
DPC++ 2023.1 declared a return type of `sycl::abs()` as unsigned one, even when an input type is signed.
With DPC++ 2023.2 the behavior is changed and result type has the same sign as input one now.
> Fix compilation error with sycl::abs()

- .github/workflows/generate_coverage.yaml
This PR fixes the workflow of generating coverage to run on the `master` branch when using the `push` events in `generate_coverage.yaml`
> Change the name of branches for generate_coverage.yaml

- .github/workflows/generate_coverage.yaml
- README.md
This PR sets the minimum version of cmake >= 3.21 to generate coverage and adds the coverage badge to dpnp repository
> Pin minimum version of cmake >=3.21 for generate_coverage

- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- dpnp/CMakeLists.txt
- dpnp/backend/extensions/vm/CMakeLists.txt
- dpnp/backend/extensions/vm/div.cpp
- dpnp/backend/extensions/vm/div.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
The new logic assumes to call `div` from pybind11 extension of OneMKL VM if possible or fully rely on dpctl.tensor implementation for `divide` otherwise.
> Improve dpnp.div() implementation

- dpnp/__init__.py
The PR implements a workaround when pybind11 extension hangs inside OneMKL.
The change is needed until the issue is resolve in DPC++ compiler.
> Fix hanging with pybind11 extension around MKL calls

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- .github/workflows/pre-commit.yml
- README.md
- doc/conf.py
- dpnp/CMakeLists.txt
- dpnp/__init__.py
- dpnp/backend/doc/Doxyfile
- dpnp/backend/extensions/vm/CMakeLists.txt
- dpnp/backend/extensions/vm/div.cpp
- dpnp/backend/extensions/vm/div.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/version.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/third_party/cupy/linalg_tests/test_eigenvalue.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
Merge the latest content from `master` branch to `gold/2021`.
> Merge master to gold

- dpnp/dpnp_iface_linearalgebra.py
The PR proposes to add an additional step with creating a contiguous copy of input array if it wasn't placed in contiguous memory. This has to provide better performance for the use case, since OneMKL function `dot` will be used.
Additionally, the PR is assumed to be introduced together with #1389, where excess copy is removed during transposing of an array.
> Add a copy for strided arrays in dpnp.dot()

- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
The PR fixes an issue how result type is calculated internally in cython layout on a device without fp64 support.
The issue comes from #1418.
> Obtain a proper result type on device without fp64

- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- dpnp/__init__.py
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/dpnp_random_state.cpp
- dpnp/backend/src/dpnp_random_state.hpp
- dpnp/backend/src/queue_sycl.cpp
- dpnp/backend/src/queue_sycl.hpp
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_random_state.py
- tests/test_random_state.py
- tests/test_sycl_queue.py
OneMKL provides `mcg59` engine for random generator which assumes to demonstrate a better performance on GPU device.
The PR is about to implement support of `mcg59` engine for GPU device and to left `mt19937` engine for PCU one.
> Use MCG59 engine on GPU device

- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_strides.py
- tests/test_usm_type.py
- tests/third_party/cupy/linalg_tests/test_product.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
The PR proposes to rely on implementation from dpctl.tensor for `add()`, `multiply` and `subtract` functions.
> Reuse add(), multiply() and subtract() from dpctl

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_mathematical.py
- tests/test_sum.py
- tests/third_party/cupy/math_tests/test_sumprod.py
- tests/third_party/cupy/testing/helper.py
This PR modifies `dpnp.sun()` implementation to use `dpctl.tensor.sum()` and removes skipped tests in `skipped_tests.tbl` and `skipped_tests_gpu.tbl`
> Reuse dpctl.tensor.sum for dpnp.sum

- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
The PR introduces `dpnp.result_type()` function to dpnp.
The implementation is done as a fallback on dpctl call.
> Add dpnp.result_type() support

- .github/workflows/build-sphinx.yml
The PR adds a pre-step to GitHUb action with build docs to get rid of out of memory error during execution.
> Add extra pre-step to free more memory on Ubuntu runners

- .pre-commit-config.yaml
- dpnp/backend/src/memory_sycl.cpp
- dpnp/backend/src/verbose.cpp
This RP refactors `use_sycl_device_memory` and `is_verbose_mode` functions to solve [SAT-5868](https://jira.devtools.intel.com/browse/SAT-5868) and suggest the usage of `_dupenv_s` for Windows by conditional compilation.
Also this PR removes `--version` argument for clang-format hook due to [pre-commit-hooks/issues/44 ](https://github.com/pocc/pre-commit-hooks/issues/44)
> Use _depenv_s in dpnp/backend on Windows

- .git-blame-ignore-revs
- doc/conf.py
- dpnp/backend/doc/Doxyfile
- dpnp/version.py
The PR updates internal dpnp version to `0.12.1dev0`.
> Updated versions

- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- tests/test_histograms.py
The `call_origin` function does not check the resulting array `dtype` and its support by device after `numpy function` is called when the result is tuple of arrays so `ValueError` error was raised when running on Iris Xe.
```
import dpnp
h, e = dpnp.histogram([1, 2], bins=1)
ValueError: Device Intel(R) Graphics does not provide native support for double-precision floating point type.
``` 
This PR adds the use of  `map_dtype_to_device` function for each `dtype`  of array from the resulting tuple.
> Check dtype support of each array in resulting tuple in call_origin

- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_logic.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_logic.py
- dpnp/random/dpnp_algo_random.pyx
- tests/test_random_state.py
Reuse dpctl.tensor implementation for equal, not_equal, less, less_equal, greater, and greater_equal functions.
> Reuse dpctl.tensor comparison functions.

- .github/workflows/build-sphinx.yml
The github action with a pre-step to free additional space during building the docs was updated with a new version and so it enabled docker image removal by default.
The PR proposal to explicitly disable removal of docker images, since the image is required.
> Exclude docker image removal

- .github/workflows/conda-package.yml
The PR proposes to permit parallel uploading to conda even if any single upload job fails.
It might be a case when uploading of any built conda package is failed due to some connectivity issue and it would be enough to rerun it. But with option `continue-on-error: false` all other running upload jobs will be cancelled due to that.
> Continue parallel uploading in case of error

- .github/workflows/conda-package.yml
- dpnp/backend/extensions/vm/cos.hpp
- dpnp/backend/extensions/vm/sin.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_trigonometric.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_umath.py
- tests/third_party/cupy/math_tests/test_trigonometric.py
The new logic assumes to call `cos` and `sin` from pybind11 extension of OneMKL VM if possible or fully rely on dpctl.tensor implementation otherwise.
> Improve dpnp.cos() and dpnp.sin() implementations

- dpnp/backend/extensions/vm/sqrt.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_trigonometric.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/linalg/dpnp_algo_linalg.pyx
- tests/test_umath.py
This PR adds the ability to rely on `dpctl.tensor.sqrt()` implementation for `dpnp.sqrt` function and call `sqrt` from pybind11 extension of OneMKL if possible
> Update dpnp.sqrt using dpctl and OneMKL implementations

- .github/workflows/conda-package.yml
- dpnp/backend/extensions/vm/sqr.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_trigonometric.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_umath.py
- tests/third_party/cupy/math_tests/test_misc.py
The new logic assumes to call `square` and `sin` from pybind11 extension of OneMKL VM if possible or fully rely on dpctl.tensor implementation otherwise.
> Improve dpnp.square() implementation

- .github/workflows/build-sphinx.yml
The PR resolves failure in `build-sphinx` action where incorrect name was used to install OneAPI package of DPC++ compiler.
> Corrected name of OneAPI compiler package

- dpnp/CMakeLists.txt
- dpnp/backend/extensions/sycl_ext/CMakeLists.txt
- dpnp/backend/extensions/sycl_ext/dispatcher_utils.hpp
- dpnp/backend/extensions/sycl_ext/sum_mean.cpp
- dpnp/backend/extensions/sycl_ext/sum_mean.hpp
- dpnp/dpnp_iface_mathematical.py
- tests/test_extensions.py
> Add specialized kernel for sum(axis=0) as extension

- CHANGELOG.md
The PR updates the Changelog in scope of OOC release.
> Add changelog for 0.12.1

- conda-recipe/meta.yaml
The PR pins host & run dependencies on dpctl with version `0.14.5` in scope of OOC dpnp release.
> Pin to dpctl 0.14.5

- .github/workflows/build-sphinx.yml
This PR pines `numpy<1.24` to build sphinx documentation. The change is necessary cause `cupy` uses `numpy.bool` which expired in version `numpy>1.24` [NumPy 1.24 Release Notes](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) 
```
File "/usr/share/miniconda3/envs/docs/lib/python3.9/site-packages/cupyx/scipy/sparse/_index.py", line 22, in <module>
_bool_scalar_types = (bool, numpy.bool, numpy.bool_)
File "/usr/share/miniconda3/envs/docs/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
```
> Pin to numpy<1.24 in build_sphinx

- dpnp/dpnp_iface_mathematical.py
Tests in https://github.com/IntelPython/dpnp/pull/1488 covers this functionality. Except `keepdims` due to https://github.com/IntelPython/dpnp/issues/1487
Speeds up `cov` with `rowvar=False` parameter.  As it is used in `pca` workload.
```python
import dpnp
import numpy
import time
a = dpnp.ones((1048576, 128))
dpnp.cov(a, rowvar=False, dtype=a.dtype)
start = time.time()
dpnp.cov(a, rowvar=False, dtype=a.dtype)
print(time.time() - start)
```
Before:
```
0.6248629093170166
```
After:
```
0.229935884475708
```
> Use specilized kernel for f-arrays and sum by axis=1. Add keepdims support

- conda-recipe/build.sh
The PR removes workaround to Klocwork implemented in #1433.
Due to transition to Coverity tool, the w/a is no longer necessary.
> Removed w/a to Klocwork

- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
- dpnp/dpnp_algo/dpnp_algo_statistics.pxi
- dpnp/dpnp_utils/dpnp_algo_utils.pxd
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- dpnp/dpnp_utils/dpnp_utils_statistics.py
- dpnp/linalg/dpnp_algo_linalg.pyx
- tests/test_statistics.py
This PR solves updates tests and backend of some `statistic functions` to run on Iris Xe which does not support double precision floating point type.
It solves part of #1293
Also it moves `get_ret_type_and_func` function to `dpnp_algo_utils` file for common use in cython files
> Update test_statistic.py to run on Iris Xe

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- conda-recipe/meta.yaml
- dpnp/CMakeLists.txt
- dpnp/dparray.pyx
The PR resolves compilation error which mainly looks relating to incorrect code generation by cython 3.0.0 in case of any import with asterisk. By the way, all asterisk imports were removed from `dparray.pyx`, since it makes the code more clear.
Also the PR suppresses a compilation warning caused by the deprecated pre-NumPy-1.7 C-API. The suppression is implemented by defining `-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION` through cmake following the cython recommendation.
Remaining warnings are caused by either dpctl or cython issues.
The PR removes temporary pining to cython "<3" in the receipt and from actions, since all issues are resolved.
> Resolve warning and error with cython 3.0.0

- conda-recipe/meta.yaml
- dpnp/backend/extensions/vm/common.hpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/dpnp_utils.hpp
The PR proposes to update run and build dependencies on DPC++ and OneMKL packages from `2023.2` release.
Temporary workarounds to work with DPC++ and OneMKL packages from `2023.1` are removed from the code and secured with static asserts.
> Require DPC++ and OneMKL pacakges from 2023.2

- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_algo/dpnp_algo_statistics.pxi
- dpnp/dpnp_utils/dpnp_algo_utils.pxd
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- dpnp/dpnp_utils/dpnp_utils_statistics.py
- dpnp/linalg/dpnp_algo_linalg.pyx
This PR changes signature of `get_ret_type_and_func` function. The updated function takes `sycl_device` argument instead of `x1_obj` and checks null pointer to kernel with no `fp64` support. 
Also the PR suggests using updated `get_ret_type_and_func` function in `call_fptr_1in_1out_strides`, `call_fptr_2in_1out` and `call_fptr_2in_1out_strides` functions for further test updates to run on Iris Xe.
> Use get_ret_type_and_func in call_fptr functions 

- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/random/dpnp_algo_random.pyx
- dpnp/random/dpnp_iface_random.py
- tests/test_logic.py
- tests/test_manipulation.py
- tests/test_mixins.py
- tests/test_random.py
Update random, logic, manipulation, and mixins tests to run on Iris Xe.
> Update tests to run on Iris Xe

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_indexing.pxi
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_indexing.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_indexing.py
- tests/third_party/cupy/indexing_tests/test_indexing.py
This PR modifies `dpnp.take()` implementation to use `dpctl.tensor.take()` instead of dpnp implementation.
> Reuse dpctl.tensort.take for dpnp.take

- .pre-commit-config.yaml
- dpnp/dpnp_iface_indexing.py
The PR is aimed to upgrade pre-commit hooks with `flake8` and `black` tools to the latest available version.
The PR also suppresses one new warning E721 reporting by flake8.
> Upgrade flake8 and black to newer version

- .github/workflows/build-sphinx.yml
The PR corrects checks order in `build sphinx` actions, because the check if a commit relates to pull request needs to be done before check about pull request relation to fork repository (since the fork flag is part of pull request context).
Additionally PR proposes to dump GitHub context, since it might be useful in future investigation in case of issue with the action.
> Reorder checks in build docs action

- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_utils/dpnp_utils_statistics.py
- tests/test_arraymanipulation.py
- tests/third_party/cupy/manipulation_tests/test_join.py
- tests/third_party/cupy/testing/__init__.py
- tests/third_party/cupy/testing/helper.py
The PR propose to rework implementation of `dpnp.concatenate()` to fully rely on `dpctl.tensor.concat`.
> Leverage dpctl.tensor.concat() implementation

- scripts/gen_coverage.py
The PR proposes to resolve an exception which might be potentially raised during run of coverage generation script.
The issue will come visible if to run the script with `bin_llvm=None`.
Note, the issue was identified by Coverity tool and classified as `Very high` severity.
> Fixed assigning a value to potentially none-valued dictionary

- dpnp/backend/kernels/dpnp_krnl_random.cpp
The PR proposes to resolve faulty access to a local variable outside the scope.
Note, the issue was identified by Coverity tool and classified as of `high` severity.
> Resolve `Pointer to local outside scope` issue reported by Coverity tool

- dpnp/backend/kernels/dpnp_krnl_common.cpp
The TR is intended to resolve an issue from Coverity report with "high" severity.
The tool claims that the positions of arguments in the call to `mkl_blas::gemm` do not match the ordering of the parameters: `ldb` is passed to `lda`, `lda` is passed to `ldb`.
Actually, the issue is false positive, since local variables `lda` and `ldb` are assigning to correct values. But the PR proposes to resolve the reported problem to avoid future misleading.
> Resolve `Arguments in wrong order` issue reported by Coverity tool

- CMakeLists.txt
The PR proposes to update build flow and to use the latest available pybind11 headers.
The pybind11 version is going to switch from `2.10.2` to `2.11.1`.
> Upgrade pybind11 to the newer version

- .github/workflows/conda-package.yml
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_logic.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_logic.pxi
- dpnp/dpnp_iface_logic.py
- tests/third_party/cupy/logic_tests/test_truth.py
This PR modifies `dpnp.all()` and `dpnp.any()` implementations to use `dpctl.tensor.all()` and `dpctl.tensor.any()` instead of dpnp implementations.
It also adds a new `test_truth` file and expands the scope of tests for public CI. 
The PR is open as a draft until [#1327(dpctl)](https://github.com/IntelPython/dpctl/issues/1327) is fixed
> Leverage `dpctl.tensor.all()` and `dpctl.tensor.any()` implementations

- tests/test_mathematical.py
- tests/test_umath.py
Due to the new updates in elementwise function of `dpctl` [#1352](https://github.com/IntelPython/dpctl/pull/1352), the tests in `dpnp` are updated to align them with the changes in `dpctl`.
The changes in `dpctl` include:
1) raise `ValueError` when, there is shape inconsistency between input(s) and output
2) Memory overlap between inputs and output is allowed
> Modify the tests to align them with the changes in dpctl

- .github/workflows/conda-package.yml
The PR proposes to temporary disable tests which cause the spontaneous crashes on Window till the issue is investigated and root cause is defined.
Currently the issue scientifically increases verification time and requires reruns.
> Attempt to stabilize the public CI loop

- .github/workflows/conda-package.yml
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_manipulation.pxi
- dpnp/dpnp_iface_manipulation.py
- tests/__init__.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/skipped_tests_gpu_no_fp64.tbl
- tests/test_manipulation.py
- tests/third_party/cupy/fft_tests/test_fft.py
- tests/third_party/cupy/linalg_tests/test_product.py
- tests/third_party/cupy/manipulation_tests/test_basic.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
- tests/third_party/cupy/testing/helper.py
The PR proposes to redesign existing implementation of `dpnp.copyto()` through existing functions instead of separate kernel. Also it adds missing support of all input parameters, which allows to completely remove fallback on numpy for the function.
Additionally, more tests are added to cover the functionality.
> Reworked dpnp.copyto() implementation through existing calls

- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/test_bitwise.py
- tests/test_mathematical.py
- tests/test_usm_type.py
Since `usm_ndarray` in-place arithmetic operators is fully enabled in `dpctl` [#1352](https://github.com/IntelPython/dpctl/pull/1352), `dpnp` is updated to use the newly added features.
> utilize new functionality of dpctl for in-place operators

- .github/workflows/conda-package.yml
The PR proposes to stop building conda packages of `dpnp` for Python 3.8.
The similar change is going to be implemented by `dpctl` in [gh-1363](https://github.com/IntelPython/dpctl/pull/1363).
And so the PR intends to align the build matrix with `dpctl`.
> Do not build dpnp for Python 3.8

- dpnp/backend/extensions/vm/round.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/skipped_tests_gpu_no_fp64.tbl
- tests/test_mathematical.py
- tests/third_party/cupy/core_tests/test_ndarray_math.py
- tests/third_party/cupy/math_tests/test_rounding.py
The PR changes the implementation of `dpnp.round` and its alias `dpnp.around`. These functions now invoke `oneapi::mkl::vm::int` from pybind11 extension of OneMKL VM if possible or uses `dpctl.tensor.round` implementation if not.
> use_dpctl_round_func_in_dpnp

- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/skipped_tests_gpu_no_fp64.tbl
- tests/third_party/cupy/math_tests/test_rounding.py
- tests/third_party/cupy/testing/helper.py
In this PR, `dpnp.rint` is implemented using the existing function `dpnp.round`.
> implement dpnp.rint

- dpnp/backend/kernels/dpnp_krnl_bitwise.cpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/kernels/dpnp_krnl_logic.cpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
The PR proposes to implement similar fix as dpctl did in [gh-1366](https://github.com/IntelPython/dpctl/pull/1366).
It will help to adopt towards some of the changes in SYCL 2020 for `multi_ptr` which have introduced breaking changes for SYCL 1.2.1 applications moving to SYCL 2020.
> Conversion from raw to multi_ptr should be done with address_space_cast

- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_trigonometric.py
- tests/test_mathematical.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
The PR propose to get rid of logically dead python code, which was reported by Coverity tool.
The PR is not intended to update any test or backend code, any work around that is proposed to be done by separate issue.
> Resolve logically dead code from Coverity report

- tests/test_mathematical.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR is intended to temporary mute tests for `dpnp.sum` which are failing due to dpctl issue [#1391](https://github.com/IntelPython/dpctl/issues/1391)
> Temporary mute tests for dpnp.sum

- tests/test_mathematical.py
- tests/test_sum.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR is about to unmute temporary skipped tests in #1550, since dpctl issue was resolved.
> Unmute tests for dpnp.sum

- README.md
The PR is proposed to update `Build from source` section in `README.md` and to state all the required prerequisite packages.
> Add missing packages to README.md in `Build from source` section 

- dpnp/dpnp_container.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
This PR solves #1570 
A new condition was added to `def asarray` function by #1526 which means if `dpctl` returns a zero copy, return the input argument. 
This did not consider the case where the input argument is `usm_ndarray` so it returned `usm_ndarray` without wrapping it in `dpnp.ndarray`
This PR updates the condition to return the input argument when dpctl return a zero copy and adds tests.
> Correct return of object type at zero copy

- .github/workflows/conda-package.yml
- dpnp/dparray.pyx
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_array.py
- dpnp/dpnp_container.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraycreation.py
- tests/test_mathematical.py
- tests/test_strides.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/core_tests/test_ndarray_complex_ops.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
This PR contains
- gh-1557
- gh-1563
- gh-1571
> Merge 0.13.0rc3 into gold/2021

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_arraycreation.pxi
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_manipulation.py
- tests/test_arraycreation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `device`, `usm_type`, and `sycl_queue` keywords are added to `dpnp.tri` and `dpnp.identity`.
> identity and tri with device keywords

- .github/workflows/build-sphinx.yml
The PR proposes to explicitly state a dependency on minimum required `dpctl` version while installing in build docs environment, since it's aligned with `dpnp` dependencies listed in `host` section of `meta.yaml`.
Prior the change, conda might install dpctl of older version which causes an issue.
> Added dependency on min required dpctl version while installing in build docs env

- dpnp/backend/extensions/vm/abs.hpp
- dpnp/backend/extensions/vm/types_matrix.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_usm_type.py
The PR changes the implementation of `dpnp.abs`. This function now invokes `oneapi::mkl::vm` implementation from pybind11 extension of OneMKL VM if possible or uses `dpctl.tensor.abs` implementation if not.
> re-write dpnp.abs

- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- tests/test_linalg.py
In this PR, `dpnp.linalg.cholesky` is modified to work with zero-dimensional arrays.
> fix cholesky for 0-D array

- .github/workflows/conda-package.yml
- tests/third_party/cupy/manipulation_tests/test_dims.py
The PR proposes to add `test_dims.py` with broadcast tests to the scope of public CI, as part of `Conda package` action.
> Broadcast tests to be running within github actions

- dpnp/dpnp_iface_manipulation.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraymanipulation.py
- tests/third_party/cupy/manipulation_tests/test_join.py
Updated dpnp.vstack function and unmuted tests
> Updated dpnp.vstack function

- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/linalg/dpnp_algo_linalg.pyx
- dpnp/linalg/dpnp_iface_linalg.py
- tests/test_linalg.py
`dpnp.linalg.qr` is updated to take care of the cases where input array is not 2-D.
`dpnp.linalg.det` is updated to take care of the cases where input array is an empty array.
> fix `dpnp.linalg.qr` and `dpnp.linalg.det` functions

- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/linalg/dpnp_algo_linalg.pyx
- dpnp/linalg/dpnp_iface_linalg.py
- tests/test_linalg.py
This PR contains:
-  #1592 
- #1584
> Fuzz testing fixes

- dpnp/dpnp_iface_manipulation.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraymanipulation.py
- tests/third_party/cupy/core_tests/test_ndarray_copy_and_view.py
Implemented dpnp.broadcast_arrays function and added tests.
> Implemented dpnp.broadcast_arrays function.

- .github/workflows/conda-package.yml
- tests/third_party/cupy/core_tests/test_ndarray_unary_op.py
The PR proposes to add third party core tests for ndarray to the scope of public CI, as part of `Conda package` action.
While the scope of core tests is extended with ones for unary ndarray operations.
> Core tests to be running within github actions

- tests/test_sycl_queue.py
The `test_array_creation_cross_device` test is unstable and sporadically fails.
Th PR proposes to temporary mute it until the issue is resolved.
> Mute unstable `test_array_creation_cross_device` test

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/dparray.pxd
- dpnp/dparray.pyx
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_dparray.py
- tests/test_mathematical.py
- tests/test_random.py
- tests/third_party/cupy/core_tests/test_ndarray_copy_and_view.py
Leverage dpctl.tensor.astype() implementation.
Clean up old implementation.
Refresh test_ndarray_copy_and_view.py test file.
> Update dpnp.astype function

- dpnp/dpnp_iface_manipulation.py
- tests/test_arraymanipulation.py
- tests/third_party/cupy/test_type_routines.py
Implemented dpnp.can_cast function and added tests.
> Implemented dpnp.can_cast function

- dpnp/dpnp_iface.py
The PR proposes to remove obsolete TODO from `dpnp.get_normalized_queue_device()` function.
Based on current `run` dependency on the dpctl version, we can always assume that `normalize_queue_device` is available and so the workaround with falling back on `sycl_queue` from input arguments can be safely removed.
> Removed temporary workaround from `dpnp.get_normalized_queue_device()`

- .github/workflows/generate_coverage.yaml
- dpnp/CMakeLists.txt
- pyproject.toml
- scripts/gen_coverage.py
The PR proposes to include files relating to the code of extensions to overall coverage report.
> Improve coverage report

- CMakeLists.txt
- dpnp/CMakeLists.txt
- dpnp/backend/cmake/Modules/IntelSYCLConfig.cmake
- dpnp/backend/extensions/lapack/CMakeLists.txt
- dpnp/backend/extensions/sycl_ext/CMakeLists.txt
- dpnp/backend/extensions/vm/CMakeLists.txt
Replaced deprecated `IntelDPCPPConfig.cmake` vendored script with vendored `IntelSYCLConfig.cmake`.
Changed project's cmake scripts accordingly.
> Use IntelSYCL cmake script

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_reduction.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arithmetic.py
- tests/test_mathematical.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
In this PR, `dpnp.prod` and `dpnp.nanprod` are implemented using their `dpctl.tensor` counterparts.
> implement dpnp.prod and dpnp.nanprod

- .github/workflows/conda-package.yml
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_statistics.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_statistics.py
- tests/skipped_tests.tbl
- tests/test_amin_amax.py
- tests/test_statistics.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/core_tests/test_ndarray_reduction.py
In this PR, `dpnp.max` and `dpnp.min` are implemented using their `dpctl.tensor` counterparts.
> implement dpnp.max and dpnp.min using dpctl.tensor functions

- tests/test_mathematical.py
Dedicated kernels are implemented in `dpctl` for in-place division and floor division [#1431](https://github.com/IntelPython/dpctl/pull/1431)
In this PR, this feature is added for `dpnp.divide` and `dpnp.floor_divide`.
New tests are written for them.
UPDATE: 
With recent updates in `dpctl` ([#1463](https://github.com/IntelPython/dpctl/pull/1463)), the usage of in-place operator are automatically incorporated in `dpnp`. This PR now only updates the relevant tests.
> in place divide and floor_divide

- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
The build with enabled coverage profiling is terminating with stack dump when using DPC++ 2024.0 compiler.
The PR proposes to temporary use DPC++ 2023.2 for coverage run until the issue is resolved.
> Pin DPC++ compiler to 2023.2 for coverage run to work around a crash in 2024.0

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_arraycreation.pxi
- dpnp/dpnp_array.py
- dpnp/dpnp_container.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_statistics.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arraycreation.py
- tests/test_statistics.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/core_tests/test_ndarray_reduction.py
- tests/third_party/cupy/creation_tests/test_matrix.py
In this PR, `device`, `usm_type`, and `sycl_queue` keywords are added to `dpnp.diag`, `dpnp.diagflat`, `dpnp.ptp` and `dpnp.vander`.
> rework implementation of diag, diagflat, vander, and ptp

- dpnp/dpnp_iface_manipulation.py
- tests/third_party/cupy/statistics_tests/test_meanvar.py
A skip test is removed since `dpctl` [issue #1468](https://github.com/IntelPython/dpctl/issues/1468) is resolved by `dpctl` [PR #1470](https://github.com/IntelPython/dpctl/pull/1470).
> remove skip test

- .github/workflows/build-sphinx.yml
The PR closes #1620 issues.
The PR closes #1621 pull request as superseded.
A step `Deploy docs` from building docs actions was indented to only build dpnp docs when the new commit is pushed to "master" branch. But due to wrong conditions the step was triggered from pull request of PR branch when event comes with action="closed" property.
Another major issue is missing `keep_files` option enabled for the step, which leads to removal of all files from "gh-pages" branch (as a pre-step), i.e. also including generated doc files relating to another PRs (located in a special "pull" folder and which has to be removed by separate `Clean` job per each closing PR).
The PR assumes to resolve both above issues.
Additionally GitHub bot user and email is used to push on "gh-pages" branch facelessly.
> Update deploy step of a job with building docs

- .github/workflows/conda-package.yml
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_statistics.py
- tests/test_mathematical.py
- tests/test_statistics.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.mean` is implemented using its `dpctl` counterpart.
> implement dpnp.mean

- tests/helper.py
- tests/test_fft.py
- tests/test_mathematical.py
- tests/test_sum.py
- tests/test_sycl_queue.py
This PR improves `assert_dtype_allclose` function by adding type checking for cases with inexact data types. 
It makes the behaviour of the function consistent with its purpose and improves the reliability of data type checking in `dpnp` functions.
> Add type checking in `assert_dtype_allclose` for inexact dtypes

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_indexing.pxi
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/linalg/dpnp_iface_linalg.py
- tests/helper.py
- tests/test_indexing.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/indexing_tests/test_indexing.py
The PR proposes to implement `dpnp.put_along_axis` and `dpnp.take_along_axis` functions through building a fancy index.
The indexing functionality will be used to either replace the values in an input array based on the index or to extract the values following the fancy index.
The PR continues the work started with updating `dpnp.put` and `dpnp.take` functions to leverage on dpctl.tensor implementation for indexing routine.
> Redesign `dpnp.put_along_axis` and `dpnp.take_along_axis` thorough existing calls

- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_statistics.py
- tests/test_amin_amax.py
The PR aligns supported arguments of `dpnp.amax` and `dpnp.amin` with numpy implementation.
The functions are only aliased on already updated `dpnp.max` and `dpnp.min` methods.
> Add support of missing arguments in `dpnp.amax` and `dpnp.amin`

- .github/workflows/build-sphinx.yml
- conda-recipe/meta.yaml
The compiler package `dpcpp_linux-64=2024.0.1` has known issues breaking CMake integration with DPC++.
This PR pins build-time version to `2024.0.0` until the underlying issue gets resolved.
> Stay away from 2024.0.1 compiler package

- .github/workflows/generate_coverage.yaml
The step with building coverage is failing quite often due to known issue with OCL RT.
The PR propose to automatically rerun the step multiple times until the issue is resolved and a fix is available.
> Retrying build coverage step on failure

- dpnp/dpnp_iface_mathematical.py
In NumPy `true_divide` is alias on `divide` function.
The PR proposes to implement exactly the same behavior. It will allow to have exactly the same arguments for `true_divide` as `divide` has.
> Align arguments of `dpnp.true_divide` with `dpnp.divide`

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_dparray.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_misc.py
dpnp.clip is implemented using  dpctl.tensor.clip.
> Implement of dpnp.clip()

- doc/reference/math.rst
- dpnp/dpnp_iface_trigonometric.py
- tests/helper.py
- tests/test_mathematical.py
- tests/test_strides.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.logsumexp` and `dpnp.reduce_hypot` are implemented using their `dpctl` counterpart.
> implement `dpnp.logsumexp` and `dpnp.reduce_hypot`

- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/backend/kernels/dpnp_krnl_linalg.cpp
- dpnp/backend/kernels/dpnp_krnl_sorting.cpp
- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
The PR proposes to resolve compilation warnings with the latest DPC++ towards 2024.1 release.
The warning appeared since the compiler enabled `-Wvla-extension` option for C++ by default and so the users are made aware of the extension, especially given the security implications around stack overflows with VLAs that can be mitigated by heap allocations through C++ containers.
> Resolve compilation warnings

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_reduction.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_algo/dpnp_algo_statistics.pxi
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_statistics.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_arithmetic.py
- tests/test_mathematical.py
- tests/test_statistics.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
- tests/third_party/cupy/statistics_tests/test_meanvar.py
In this PR, `dpnp.nanmean`, `dpnp.nanstd`, `dpnp.nansum`, and `dpnp.average` are implemented using existing functions in `dpnp`.
> implement `dpnp.nanmean`, `dpnp.nanstd`, `dpnp.nansum`, and `dpnp.average`

- tests/third_party/cupy/test_type_routines.py
The PR proposes to skip the test for `dpnp.result_type` until the latest dpctl is available in the internal CI.
The whole file is updated to have line endings are converted to Unix style.
> Temporary skip test for result_type

- conda-recipe/meta.yaml
The PR proposes to execute `python -m dpctl -f` before launching tests scope for printing detailed information about available devices and driver versions.
It might be helpful while troubleshooting issues if any.
> Add printing of available devices while triggering tests scope execution

- tests/test_mathematical.py
- tests/test_umath.py
- tests/third_party/cupy/core_tests/test_ndarray_unary_op.py
- tests/third_party/cupy/math_tests/test_rounding.py
In this PR, elementwise tests are updated to align with recent changes in `dpctl` [gh-1496](https://github.com/IntelPython/dpctl/pull/1496).
> update tests affected by changing `TypeError` to `ValueError` in `dpctl`

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_trigonometric.pxi
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_mathematical.py
- tests/test_strides.py
- tests/test_sycl_queue.py
- tests/test_umath.py
- tests/test_usm_type.py
- tests/third_party/cupy/core_tests/test_ndarray_complex_ops.py
- tests/third_party/cupy/math_tests/test_arithmetic.py
- tests/third_party/cupy/sorting_tests/test_search.py
- tests/third_party/cupy/statistics_tests/test_order.py
In this PR, `dpnp.angle` and `dpnp.reciprocal` are implemented using their `dpctl` counterparts.
> implement `dpnp.reciprocal` and `dpnp.angle`

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- conda-recipe/meta.yaml
The PR modifies `meta.yaml` to disallow 2024.0.1 and 2024.0.2 but allow for newer DPC++ compiler versions.
> Allow for newer version of DPC++ compiler

- dpnp/dpnp_iface_mathematical.py
Dpctl implemented `clip` function according to Python array API specification. And dpnp fully relies on `dpctl.tensor.clip` implementation.
While NumPy requires that only one of `min` or `max` be allowed to be `None` at the same time.
The PR proposes to align `dpnp.clip` with both `min` and `max` as `None` with NumPy implementation.
> Clipping with both min and max values as None

- tests/test_sycl_queue.py
The PR proposes to temporary skip tests relating to run of `var` and `std` function with OpneCL GPU device due to known issue which may lead to crash on Windows.
> Temporary mute tests due to known issue with OpenCL GPU

- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
The PR pins `conda-build` to the latest stable version `3.28.4`.
The new version `24.1.0` published on anaconda `main` channel brings unexpected `Process completed with exit code 1` issue at the end of successful run of `conda build` command.
> Pin conda-build to `3.28.4` version in GitHub action

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- .github/workflows/pre-commit.yml
This PR specifies permissions in GitHub Action workflows. Minimal read-all permission is set by default, and specific scope get elevated permission as needed.
This would improve OpenSSF Scorecard value.
> Specify permissions in GH Action workflows

- .github/dependabot.yml
- .github/workflows/build-sphinx.yml
The PR adds `.github/dependabot.yml` to run weekly jobs to update version of GitHub Actions.
> Adding dependabot file to update GH action versions

- conda-recipe/meta.yaml
The PR adds maintainers to the conda recipe and defines `summary` to the same value as description has in `setup.py`.
> Add recipe-maintainers list

- dpnp/dpnp_iface_arraycreation.py
- tests/test_arraycreation.py
Fix dpnp.asfortranarray and dpnp.ascontiguousarray functions for not array input. Add tests
> Fix dpnp.asfortranarray and dpnp.ascontiguousarray functions for not array input

- dpnp/backend/extensions/blas/CMakeLists.txt
- dpnp/backend/extensions/blas/blas_py.cpp
- dpnp/backend/extensions/blas/dot.hpp
- dpnp/backend/extensions/blas/dotc.cpp
- dpnp/backend/extensions/blas/types_matrix.hpp
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_dot.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.vdot` is updated. 1) For integer and boolean data types, `dpctl.tensor.vecdot` form the Data Parallel Control library is used, 2) For real-valued floating point data types, `dot` routines from BLAS library of OneMKL are used, and 3) For complex data types, `dotc` routines from BLAS library of OneMKL are used.
> update `dpnp.vdot` implementation

- dpnp/dpnp_iface.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
In this PR, implementation of `dpnp.matmul` and `dpnp.dot` is updated to improve the performance when `out` keyword is present and its feature matches the appropriate shape, dtype, sycl_queue, and usm_type that is needed for performing the calculation in the corresponding OneMKL BLAS routines.
Sample timing including this update
```
>>> import dpnp
>>> a = dpnp.ones((21846, 3), device='cpu')
>>> b = dpnp.ones((21846, 3), device='cpu')
>>> c = dpnp.ones((21846, 21846), device='cpu')
>>> %timeit dpnp.matmul(a, b.T, c)
229 ms ± 22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Sample timing excluding this update
```
>>> import dpnp
>>> a = dpnp.ones((21846, 3), device='cpu')
>>> b = dpnp.ones((21846, 3), device='cpu')
>>> c = dpnp.ones((21846, 21846), device='cpu')
>>> %timeit …
```
> Improve performance of `dpnp.matmul` and `dpnp.dot` with `out` keyword

- dpnp/dpnp_iface_indexing.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
This PR solves the issue of raising `ExecutionPlacementError` when using `dpnp.take_along_axis()` with 2D arrays and `axis not None`
Filling `fancy_index` in `_build_along_axis_index` did not follow compute follows data and allocated dpnp index arrays on the device and queues by default. 
Also this case was not covered in the tests so I extended them.
> Fix ExecutionPlacementError for dpnp.take_along_axis

- doc/conf.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_sorting.py
- tests/helper.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_dot.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/linalg_tests/test_product.py
In this PR, `dpnp.tensordot` is implemented using existing functions in `dpnp`.
> implement `dpnp.tensordot`

- CHANGELOG.md
That PR updates `CHANGELOG.md` with changes including in `0.14.0` release
> Updated CHANGELOG.md for 0.14.0 release

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- CHANGELOG.md
- conda-recipe/meta.yaml
The PR includes the updates in `CHANGELOG.md` with missing changes and stepping dpctl dependencies on dpctl RC version.
> Preparation for `0.14.0rc1` tag

- tests/test_dot.py
- tests/test_mathematical.py
In this PR, a seed is used to generate random input numbers in test suite for reproducibility of tests.
> use a seed for random input numbers in tests

- dpnp/dpnp_array.py
- tests/test_dparray.py
- tests/test_mathematical.py
In this PR, `dpnp.ndarray.real` and `dpnp.ndarray.imag` are modified to return a view of the input array using their `dpctl` counterpart. Note that `dpnp.real` and `dpnp.imag` return a copy consistent with `dpctl` behavior.
Also, new tests are added to check the correctness of writable flag in different scenarios, due to new changes in [dpctl #1527](https://github.com/IntelPython/dpctl/pull/1527).
> return a view for `dpnp.ndarray.real` and `dpnp.ndarray.imag`

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- conda-recipe/meta.yaml
- dpnp/dpnp_algo/dpnp_elementwise_common.py
The PR is intended to adopt to the latest changes in dpctl#1554 where boolean subtract raises `ValueError` exception. While numpy raises `TypeError` exception for the same use cases.
This PR implements a temporary workaround to unblock the CI verification loop.
> Boolean subtract to raise TypeError exception

- CHANGELOG.md
- conda-recipe/meta.yaml
Merge the latest content from master branch to gold/2021 as part of `0.14.0` release tag.
The PR includes changes from:
- #1720
> Merge `0.14.0` from master to gold

- .github/workflows/conda-package.yml
This PR removes pinning on previous version of `conda-build` introduced in #1678 and moves forward to the latest available version of `conda-build=24.1.2`, since it includes the fix now for `nonzero exitcode on success`.
Additionally PR enables `conda-index` package instead of deprecated one from `conda-build` package.
> Pin conda-build to latest version (24.1.2)

- .flake8
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_counting.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_libmath.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_sorting.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_types.py
- pyproject.toml
The PR extends pre-commit hooks with `pylint` configuration.
The current files filter for the verification is set to `dpnp/dpnp_iface*.py` (excluding files from #1712) to reduce number of issues. The other files will be added to the scope in later PRs
> Adding pylint pre-commit hook

- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- tests/test_product.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.linalg.multi_dot` implementation is updated.
> update `dpnp.linalg.multi_dot` implementation

- conda-recipe/meta.yaml
The PR is about to exclude the DPC++ release along with `2024.0.1` and `2024.0.2` for Windows, i.e. it's broken.
> Most recent release of dpcpp_win-64=2024.0.3 is still broken

- doc/reference/dtype.rst
- dpnp/dpnp_utils/dpnp_algo_utils.pxd
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
The PR removes unused function `find_common_type` from Cython backend layout.
The function also was present in NumPy and deprecated since `1.25.0`, so also it removes documentation reference on it.
> Remove find_common_type which is never used in DPNP and deprecated since NumPy 1.25.0

- .github/dependabot.yml
The PR propose to change a day of week when the updates are checking from default Monday to Saturday, because usually there are less load on public CI flow and so the PRs from dependabot will be able to be merged faster.
Another configuration update assumes to disable `rebase-strategy` to prevent automatic rebase by dependabot once any PR is merged. It will be up to assignee to rebase each PR manually, because it speeds up the merge time due to reducing load on public CI.
> Tune dependabot configuration

- tests/test_sycl_queue.py
The PR proposes to temporary skip SYCL relating tests with OpneCL GPU device due to known issue which may lead to crash on Windows.
Previously #1672 already muted few tests for OpneCL GPU device, but the same problem is facing with other SYCL relating tests occasionally.
Thus the idea is to exclude OpneCL GPU device from the verification scope temporary to unblock the internal CI verification flow.
> Temporary mute all SYCL tests for OpenCL GPU device due to known issue

- .github/workflows/conda-package.yml
The PR proposes to get rid of installation of `opencl_rt` package before running tests for Windows.
The step was previously added as a workaround and isn't required anymore, since fully covered by dependent conda packages.
Removing the step will slightly speed up `Conda package` action.
> Remove step with installing `opencl_rt`

- doc/dpctl.rst
- dpnp/backend/examples/example10.cpp
- dpnp/backend/examples/example3.cpp
- dpnp/backend/examples/example5.cpp
- dpnp/backend/examples/example7.cpp
- dpnp/backend/examples/example8.cpp
- dpnp/backend/examples/example9.cpp
- dpnp/backend/examples/example_bs.cpp
- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/queue_sycl.cpp
- dpnp/backend/src/queue_sycl.hpp
- dpnp/backend/tests/test_broadcast_iterator.cpp
- dpnp/backend/tests/test_utils_iterator.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo.pyx
- examples/example10.py
- tests/third_party/intel/zero-copy-test1.py
`DPCTLQueueMgr_*` is being removed, see https://github.com/IntelPython/dpctl/pull/1576.
This PR removes use of `DPCTLQueueMgr_*` in `queue_sycl.cpp` and `queue_sycl.hpp`. 
It effectively reverts to using `DPNP_LOCAL_QUEUE=1`.
Examples, documentation were also updated to avoid uses of `device_selector` as it is being removed.
> Replace use of queue mgr

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
The PR is about clean up backend code by removing unused enumeration with functional names which are currently implemented through pybind11 extension or leveraging on `dpctl.tensor` implementation.
> Remove unused enums with function names

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_sorting.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_sorting.pxi
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_sorting.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_sort.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/sorting_tests/test_search.py
The PR is about to implement `dpnp.searchsorted` through leveraging on `dpctl` implementation.
In addition, the PR adds missing `dpnp.ndarray.searchsorted` method and increases tests coverage.
> Implement `dpnp.searchsorted`

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
Since `2024.1` is published on `intel` channel, which contains the required fixes, there is no need to keep the workarounds with pinning of DPC++ compiler to older versions (see #1628 and #1643 for more details).
> Remove a temporary workaround in GitHub actions

- tests/test_usm_type.py
- tests/third_party/cupy/linalg_tests/test_solve.py
The PR proposes to temporary mute tests in public CI which causes hanging until the issue is resolved.
> Temporary mute tests for `dpnp.solve`

- dpnp/dpnp_iface_searching.py
- tests/test_indexing.py
- tests/test_search.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
That PR propose to remove `call_origin` call from `dpnp.where` function.
Also the PR adds more tests (including missing ones for compute follows data support) and increases coverage rate.
> Get rid of `call_origin` in `dpnp.where`

- .github/workflows/generate_coverage.yaml
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_searching.py
- tests/test_indexing.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
That PR propose to remove `call_origin` call from implementation of `dpnp.nonzero` function.
Also the PR adds more tests (including missing ones for compute follows data support) and increases coverage rate.
> Get rid of `call_origin` in `dpnp.nonzero`

- conda-recipe/meta.yaml
The PR propose to remove pinning of numpy version from conda receipt, because it affects flow of internal CI where the numpy version is specified by conda command.
> Remove numpy pinning from conda receipt

- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_trigonometric.py
- tests/test_arithmetic.py
- tests/test_mathematical.py
- tests/test_sum.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR aligns tests with the recent updates reductions over floating point data implemented in scope of [IntelPython/dpctl#1621](https://github.com/IntelPython/dpctl/pull/1621) as per the 2023.12 array API spec.
> Align with new array api version in dpctl

- dpnp/dpnp_container.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/random/dpnp_random_state.py
Due to changes in [dpctl-1626](https://github.com/IntelPython/dpctl/pull/1626), the function signatures of a few functions are modified and positional arguments are converted to keyword-only arguments.
> update `dpctl` function signature

- .github/workflows/generate_coverage.yaml
- scripts/gen_coverage.py
The PR proposes to use OneAPI compiler in GitHub actions with coverage run, because the latest conda package with DPC++ 2024.2 still has an issue with collecting of the coverage.
> Install OneAPI compiler for coverage GitHub action

- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_mathematical.py
- tests/helper.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR is about to implement `dpnp.cumsum` through leveraging on dpctl implementation.
Note `dpnp_cumsum` is left in the backend code, because it is used by `dpnp_nancumsum` function also.
> Leverage `dpnp.cumsum` through dpctl.tensor implementation

- doc/reference/math.rst
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_iface_nanfunctions.py
- tests/test_linalg.py
- tests/test_mathematical.py
- tests/test_nanfunctions.py
- tests/test_sum.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR proposes to implement `dpnp.nancumsum()` through existing call of `dpnp.cumsum` function.
The tests relating to NaN-like functions are decoupled to a new test scope `tests/test_nanfunctions.py`
> Implement `dpnp.nancumsum()` through `dpnp.cumsum` call

- dpnp/backend/CMakeLists.txt
- dpnp/backend/extensions/blas/CMakeLists.txt
- dpnp/backend/extensions/lapack/CMakeLists.txt
- dpnp/backend/extensions/sycl_ext/CMakeLists.txt
- dpnp/backend/extensions/vm/CMakeLists.txt
The PR proposes to remove use of `-flink-huge-device-code` link option, because it is no longer necessary and suspectedly makes linking of device code somewhat longer.
The option was previously introduced in scope of #1270.
> Remove use of -flink-huge-device-code link option

- doc/dpctl.rst
- doc/index.rst
- doc/quick_start_guide.rst
- doc/reference/creation.rst
- doc/reference/dtypes_table.rst
- doc/reference/linalg.rst
- doc/reference/ndarray.rst
- doc/reference/statistics.rst
- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_types.py
- dpnp/linalg/dpnp_iface_linalg.py
In this PR, a few formatting issue are resolved which were causing errors/warnings in sphinx-build.
> Fix a few sphinx-build errors and warnings

- tests/test_linalg.py
- tests/third_party/cupy/linalg_tests/test_decomposition.py
- tests/third_party/cupy/linalg_tests/test_norms.py
- tests/third_party/cupy/linalg_tests/test_solve.py
This PR suggests unlocking skipped `linalg` tests that use `oneapi::mkl::lapack::gesv` due to bug fix for it in MKL version 2024.1. 
Also this PR updates comments for TODOs with the correct ticket number of a bug in MKL.
> Unlock skipped linalg tests that use `gesv`

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- doc/_templates/autosummary/class.rst
- doc/docstring_template.py
- dpnp/backend/cmake/Modules/IntelSYCLConfig.cmake
- dpnp/backend/examples/example_bs.cpp
- dpnp/backend/extensions/blas/gemm.cpp
- dpnp/backend/extensions/blas/gemm_batch.cpp
- dpnp/backend/extensions/sycl_ext/dispatcher_utils.hpp
- dpnp/dpnp_iface_manipulation.py
- examples/example4.py
- pyproject.toml
- scripts/build_deps_dpctl_win.bat
- scripts/gen_coverage.py
- setup.py
- tests/helper.py
- tests/test_linalg.py
- tests/test_logic.py
- tests/test_random.py
- tests/test_sycl_queue.py
- tests/third_party/cupy/indexing_tests/test_indexing.py
- tests/third_party/cupy/linalg_tests/test_eigenvalue.py
- tests/third_party/cupy/manipulation_tests/test_tiling.py
- tests/third_party/cupy/sorting_tests/test_search.py
- tests/third_party/cupy/testing/_condition.py
- tests/third_party/cupy/testing/_helper.py
- tests/third_party/cupy/testing/_loops.py
- tests_external/numpy/runtests.py
The PR add a pre-commit hook with `codespell` check to identify possible common misspelling in the code.
_Note_, the versions of other hooks were updated to the latest releases.
> Extend pre-commit hooks with codespell

- dpnp/random/dpnp_iface_random.py
Function `dpnp.isnan` doesn't support scalar input and raises `TypeError` exception. But the call with scalar input is using by implementation of `dpnp.random.vonmises` function.
The PR proposes to always call `numpy.isnan` there instead, because it's secured that `kappa` is a scalar by a prior check in the code.
> Fixed an issue in `dpnp.random.vonmises` function identified by running tests scope on PVC

- .github/workflows/conda-package.yml
- doc/known_words.txt
- dpnp/dpnp_algo/dpnp_arraycreation.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/dpnp_utils/dpnp_utils_reduction.py
- dpnp/dpnp_utils/dpnp_utils_statistics.py
- dpnp/linalg/dpnp_iface_linalg.py
- tests/test_mathematical.py
- tests/test_search.py
- tests/test_statistics.py
- tests/test_sum.py
The PR implements of `out` keywords of reduction functions from `dpctl.tensor` interface and `out` and `order` keywords of `dpctl.tensor.where` function (see [gh-1643](https://github.com/IntelPython/dpctl/pull/1643) for more details how it was implemented in dpctl).
Additionally the PR adds some improvements to docstrings of dpnp functions which were identified during the implementation.
> Leverage on `out` keyword in reduction and `where` functions of `dpctl.tensor`

- conda-recipe/build.sh
This PR is designed to fix the problem described here: [SAT-6873](https://jira.devtools.intel.com/browse/SAT-6873). I did some experiments and found out that using pep600 wheel tag prevents the wheel from being installed on non-supported platforms
> update wheel tag with pep600

- dpnp/dpnp_iface_arraycreation.py
- tests/third_party/cupy/creation_tests/test_matrix.py
This PR suggests to update `dpnp.diag()` implementation with a reuse of `dpnp.diagonal()` and return a read/write view instead of copy if the input array is an instance of {`dpnp.ndarray`, `usm_ndarray`} for the default case ( `device` ,`usm_type`, `sycl_queue` are `None`).
These changes greatly improve performance compared to the old implementation
> Improve performance for dpnp.diag()

- tests/test_mathematical.py
- tests/test_nanfunctions.py
- tests/test_search.py
- tests/test_statistics.py
- tests/test_sum.py
- tests/test_umath.py
In this PR, test are re-organized as below:
* Classes for `TestNanstd`, `TestNanvar`,  and `TestNanmean`, and tests related to `dpnp.nanmin` and `dpnp.nanmax` are moved from `tests/test_statistics.py` to `tests/test_nanfunctions.py`.
* Tests related to `dpnp.nanargmin` and `dpnp.nanargmax` are moved from `tests/test_search.py` to `tests/test_nanfunctions.py`.
* Tests related to `dpnp.nanprod` are moved from `tests/test_mathematical.py` to `tests/test_nanfunctions.py`.
* Tests related to `dpnp.sum` are moved from `tests/test_mathematical.py` to `tests/test_sum.py`.
* elementwise tests are updated to reduce duplication.
> organize test suit

- .pre-commit-config.yaml
- dpnp/linalg/__init__.py
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- pyproject.toml
The PR proposes to enable `pre-commit pylint` checks in `linalg` module.
The main part of work was to split functions in `dpnp/linalg/dpnp_utils_linalg.py` with too many statements into smaller ones.
> Enable pre-commit pylint check in linalg module

- dpnp/backend/extensions/blas/gemm_batch.cpp
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
In this PR, strides are standardized before using in different places in `dpnp.matmul` to make sure the code always behave in the expected way.
> standardize the stride in matmul function

- .github/workflows/conda-package.yml
The build for Windows is temporary broken due to missing system libraries.
The PR propose to enable `continue-on-error` option to unblock the build on Linux.
> Enable `continue-on-error` option for GitHub action with `Conda build package`

- .github/workflows/conda-package.yml
Based on experimentation, switching from using `"windows-latest"` image to `"windows-2019"` fixes MS compiler use for Python packages.
The PR implements the proposed temporary pinning to `"windows-2019"`.
> Replaced windows-latest with windows-2019 to fix windows builds

- dpnp/dpnp_iface_indexing.py
This PR suggests updating `dpnp.diagonal` docstings to clarify that the returned array is a read/write view.
> Update diagonal docstrings

- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_arraycreation.pxi
- dpnp/dpnp_algo/dpnp_algo_indexing.pxi
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_arraycreation.py
- tests/test_arraycreation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/linalg_tests/test_norms.py
The PR proposes to implement `dpnp.trace` through two consequence call of `diagonal` and `sum` functions.
The similar approach is implemented in numpy and cupy.
> Leverage `dpnp.trace` implementation through existing calls

- CHANGELOG.md
This PR suggests updating `CHANGELOG.md` by adding a line with `dpnp.digitize` implementation
> Add dpnp.digitize to CHANGELOG.md

- CMakeLists.txt
- conda-recipe/meta.yaml
This change pins compile-time version of the compiler to `2024.2.0`, host MKL version to `2024.2.0`, and restricts the range of compiler runtime and MKL libraries accordingly for `dpnp=0.15.0`.
Note, `dpctl` version will be pinned to `0.17.0` once it is available.
> Pin compiler and MKL within range for 0.15 release

- tests/third_party/cupy/statistics_tests/test_histogram.py
This PR suggests removing a previously skipped test in `TestDigitize` in  case when `shape =()` and `increasing=False` since [#1689](https://github.com/IntelPython/dpctl/issues/1689) is resolved and `dpctl` package with this fix is available in the internal channel.
> Remove skip in test_digitize

- tests/third_party/cupy/statistics_tests/test_histogram.py
The #1851 enables the previously skipped test in `TestDigitize` scope for a case when `shape =()` and `increasing=False` since the appropriate `dpctl` fix is available in internal channel.
> Backport pull/1851 to maintenance/0.15.x

- conda-recipe/meta.yaml
The PR sets host and run-time pinning to the final release tag of `dpctl = 0.17.0`.
> Pin `dpctl` version to a final release tag

- CHANGELOG.md
- conda-recipe/meta.yaml
The PR sets the release date for `dpnp` version `0.15.0`.
> Set release date for 0.15.0

- .pre-commit-config.yaml
- dpnp/fft/__init__.py
- dpnp/fft/dpnp_iface_fft.py
The PR proposes to enable `pre-commit pylint` checks in `fft` module.
> Enable pre-commit pylint check in fft module

- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests_gpu_no_fp64.tbl
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR implements `dpnp.gradient` function through existing calls and adds support of all keyword arguments which available in numpy.
The affected test scope is unmuted and extended to cover more use cases.
> Implement `dpnp.gradient` function

- .github/workflows/conda-package.yml
The PR updates `conda-build` version from `24.5.0` to `24.5.1` in public CI.
> Bump conda-build version to 24.5.1

- .github/workflows/conda-package.yml
The tests are much more stable now in public CI (through GitHub actions), so the PR proposes to limit rerun attempts by only 2 number.
Also it would help to reduce the action execution time in case of real issue, when some test is failed due to an issue in dpnp, which must be addressed before merging any PR.
> Limit rerun of the tests in GitHub action by 2 attempts

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- conda-recipe/meta.yaml
There is dpctl of `0.18.0dev0` version available in public CI (through GitHub actions) and dpctl of `0.17.0` version is a minimum version since the ongoing dpnp release.
Thus the PR bumps `dpctl` versions to actual ones.
> Bump dpctl version for meta.yaml and dependecies of GH actions

- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_trigonometric.py
The `out` keyword accepts `usm_dnarray`, but that was missing in the description. This PR updates the docstring to resolve that.
Additionally, several typos were fixed.
> Update description of `out` keyword for ufuncs

- dpnp/dpnp_iface_mathematical.py
In numpy and cupy `mod` is an alias on `remainder` function.
This PR proposes to implement the same approach for dpnp.
> mod is an alias of remainder

- tests/test_random_state.py
This PR suggests temporarily skipping `test_distr`  in `TestNormal` and `TestRandN` from `test_random_state.py` due to incorrect results observed in public CI on ARM architecture with MKL package version 2024.2.0 to unlock GitHub Actions while this issue is investigated.
> Skip test_distr in TestNormal and TestRandN

- dpnp/dpnp_iface_logic.py
- tests/test_logic.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/logic_tests/test_truth.py
This PR suggests adding support `out` parameter for `dpnp.all()` and `dpnp.any()` functions using `dpnp.get_result_array()` as a W/A until `dpctl` adds support `out` parameter.
This also updates docstings and adds new tests to cover the new implementation
> Support `out` parameter for `dpnp.all/any()`

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- tests/third_party/cupy/fft_tests/test_fft.py
The conda channel `intel` is temporary inaccessible.
Due to that the PR attempts to unblock GH action with building dpnp documentation. It proposes to use only `dppy/label/dev` and `conda-forge` channels. While `onedpl-devel` and `tbb-devel` conda packages are assuming to be installed now from latest Intel OneAPI by installing `intel-oneapi-libdpstd-devel` and `intel-oneapi-tbb-devel` respectively.
The new behavior will be controlled by action environment variable `INSTALL_ONE_API`. It is implemented in that way to provide a fast solution to switch back to `intel` channel approach.
> Build conda enviroment for build docs action without `intel` channel

- .github/workflows/conda-package.yml
The conda channel `intel` is temporary inaccessible.
Due to that the PR attempts to unblock GH action with `Conda package` run. It proposes to follow oneAPI installation instruction via the conda package manager ([link](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/conda.html#GUID-BAA00723-86B2-4E54-9343-E817171F8A39)) and to replace `intel` channel with `https://software.repos.intel.com/python/conda/` one.
> Replace `intel` channel for `Conda package` action

- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
The PR continues work started in #1897.
It propose to update all dpnp functions from linear algebra routine which use BLAS extension and to align them with asynchronous dpctl execution.
> Adopt linalg functions from BLAS extension to asynchronous dpctl execution

- doc/quick_start_guide.rst
The PR replaces `-c intel` with `-c https://software.repos.intel.com/python/conda/` in Quick start guide.
The PyPI channel for intel packages still seems to function.
> Replace "-c intel" with "-c https://software.repos.intel.com/python/conda"

- dpnp/linalg/dpnp_utils_linalg.py
The PR proposes to implement a fix preventing possible race condition inside `dpnp.inv` function.
It assumes `_gesv` call depends on both copy event and event produced above `dpnp.eye` call and so it is mandatory to pass `depends=_manager.submitted_events` there.
The issue was caught during the analysis of failed tests in GitHub actions. No need to implement any dedicated test to cover that use case.
> Resolve a possible race condition in dpnp.inv() implemenetation

- doc/reference/manipulation.rst
- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
The PR adds implementation of `dpnp.trim_zeros` function.
All test scenarios are covered with new tests. Additionally `tests/third_party/cupy/manipulation_tests/test_add_remove.py` is included to verify with third party tests.
> Add `dpnp.trim_zeros` implementation

- CMakeLists.txt
The PR updates CMakeLists.txt to pull pybind11 `2.13.1` up from `2.12.0`.
> Use Pybind11 `2.13.1` to build dpnp

- tests/test_mathematical.py
The PR implements a conditional run of `tests/test_mathematical.py::TestLogSumExp::test_logsumexp_out_dtype` test which fails with `numpy < 1.26.4` due to exception raised:
```python
exp = numpy.logaddexp.reduce(a, out=out, axis=1)
E   OverflowError: cannot convert float infinity to integer
```
The PR proposes to run the test only with `numpy >= 1.26.4` which contains a fix for that.
> Add conditional run of test which fails with older numpy

- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_sorting.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- dpnp/fft/dpnp_utils_fft.py
- dpnp/linalg/dpnp_utils_linalg.py
- tests/test_arraymanipulation.py
- tests/test_flipping.py
- tests/test_indexing.py
- tests/test_linalg.py
- tests/test_mathematical.py
- tests/test_sort.py
- tests/third_party/cupy/core_tests/test_ndarray.py
- tests/third_party/cupy/lib_tests/test_shape_base.py
- tests/third_party/cupy/manipulation_tests/test_dims.py
- tests/third_party/cupy/manipulation_tests/test_join.py
- tests/third_party/cupy/manipulation_tests/test_transpose.py
- tests/third_party/cupy/math_tests/test_sumprod.py
- tests/third_party/cupy/sorting_tests/test_sort.py
- tests/third_party/cupy/statistics_tests/test_meanvar.py
- tests/third_party/cupy/testing/_loops.py
As part of the work to support numpy 2.0 we need to align with new import of `normalize_axis_index`, `normalize_axis_tuple` and `AxisError` which was changed in non-backward compatible way since numpy 2.0.
That PR proposes to use the same functionality but from `dpctl.tensor._numpy_helper` module which already adopted to support different numpy versions (including numpy 2.0).
> Reuse `dpctl.tensor._numpy_helper` module

- doc/reference/ufunc.rst
- dpnp/backend/extensions/ufunc/CMakeLists.txt
- dpnp/backend/extensions/ufunc/elementwise_functions/fmax.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/fmin.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/fmod.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/radians.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/radians.hpp
- dpnp/backend/include/dpnp_gen_1arg_2type_tbl.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/kernels/elementwise_functions/fabs.hpp
- dpnp/backend/kernels/elementwise_functions/radians.hpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_trigonometric.pxi
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/test_sycl_queue.py
- tests/test_umath.py
- tests/test_usm_type.py
The PR proposes to rework implementation of `dpnp.deg2rad` and `dpnp.radians` functions which are quite limited now.
Both functions are completely equivalent to one another.
The implementation is done by adding new binary universal function `_radians` to `_ufunc_impl` pybind11 extension.
The all affected tests are updated to cover different use cases.
> Rework implementation of `dpnp.deg2rad` and `dpnp.radians` functions

- dpnp/backend/extensions/ufunc/CMakeLists.txt
- dpnp/backend/extensions/ufunc/elementwise_functions/degrees.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/degrees.hpp
- dpnp/backend/include/dpnp_gen_1arg_2type_tbl.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/kernels/elementwise_functions/degrees.hpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_trigonometric.pxi
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/test_sycl_queue.py
- tests/test_umath.py
- tests/test_usm_type.py
The PR proposes to rework implementation of `dpnp.rad2deg` and `dpnp.degrees` functions which are quite limited now.
Both functions are completely equivalent to one another.
The implementation is done by adding new binary universal function `_degrees` to `_ufunc_impl` pybind11 extension.
The all affected tests are updated to cover different use cases.
> Rework implementation of `dpnp.degrees` and `dpnp.rad2deg` functions

- .github/workflows/conda-package.yml
The PR proposes temporary enable rerun on failure in tests run for GitHub action "Conda package" until the public CI is stable back.
As for now the tests on Linux are not stable due to spontaneous crash in SVD relating tests. The issue is under investigation.
> Enable rerun of test failure

- .pre-commit-config.yaml
- dpnp/backend/extensions/ufunc/CMakeLists.txt
- dpnp/backend/extensions/ufunc/elementwise_functions/logaddexp2.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/logaddexp2.hpp
- dpnp/backend/kernels/elementwise_functions/logaddexp2.hpp
- dpnp/dpnp_iface_trigonometric.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_strides.py
- tests/test_sycl_queue.py
- tests/test_umath.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_explog.py
The PR adds implementation of `dpnp.logaddexp2` function.
New binary universal function `_logaddexp2` as added to `_ufunc_impl` pybind11 extension.
The all affected tests are updated to cover different use cases.
> Implement `dpnp.logaddexp2` function

- doc/reference/sorting.rst
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_indexing.py
- dpnp/linalg/dpnp_utils_linalg.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/sorting_tests/test_search.py
The PR adds implementation of `dpnp.flatnonzero` function.
The implementation is done through already available functions: `dpnp.nonzero` and `dpnp.ravel`.
The tests are enabled to cover new function.
> Implement `dpnp.flatnonzero` function

- .github/workflows/conda-package.yml
The PR proposes to switch `conda-build` version from `24.5.1` to `24.7.1`.
> Bump conda-build version from 24.5.1 to 24.7.1

- tests/test_fft.py
- tests/test_sycl_queue.py
- tests/test_umath.py
In this PR, tests for `dpnp.fft.irfft` and `dpnp.fft.hfft` (which calls back `dpnp.fft.irfft`) are updated to make sure input array is Hermitian. This means that for 1-D array 0th element of the array has zero imaginary part. In addition, if output array size is N and N is even, the N/2-th element (N/2+1 frequency point) of input (Nyquist mode) also has zero imaginary part.
> update tests for `dpnp.fft.irfft` and `dpnp.fft.hfft`

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/fft/dpnp_iface_fft.py
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/random/dpnp_iface_random.py
- dpnp/random/dpnp_random_state.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/core_tests/test_ndarray.py
The PR proposes to extend `dpnp.ndarray.copy` method with `device`, `sycl_queue` and `usm_type` keywords.
Additionally, the description of `sycl_queue` keyword is aligned with other dpnp functions.
The tests are added to cover new keywords for `dpnp.ndarray.copy` and `copy.copy` methods.
Affected third party tests are unmuted.
> Add device, sycl_queue and usm_type keywords to `dpnp.ndarray.copy` method

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_mathematical.cpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_mathematical.pxi
- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
This PR suggests to update `dpnp.ediff1d` implementation using `dpnp.subtract()` and includes full support for `to_end` and `to_begin` parameters.
The old implementation of `dpnp_ediff1d` has been removed and new tests have been added
> Update `dpnp.ediff1d()` function

- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
This PR suggests updating the` dpnp.ediff1d()` implementation to make it more readable and adding a new `_process_ediff1d_args` helper function to reduce duplicate code
Additionally it updates tests to unlock the internal CI cover the new helper function.
> Update `dpnp.ediff1d` function

- tests/test_strides.py
Apply `rtol` and `atol` for assert_allclose for current dtype.
Before this test `test_strides_2args[(3, 3)-float32-hypot]` failed:
Max absolute difference: 9.536743e-07
Max relative difference: 1.1086239e-07
> Fix strides tests

- dpnp/dpnp_iface_manipulation.py
- pyproject.toml
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
The PR addresses the comment from gh-1972 and implements a proper handling of NaN values in all use cases.
Note, that the result may vary towards numpy in case of complex dtype, because for complex all possible NaNs are considered equivalent (i.e. `complex(nan, 1)`, `complex(2, nan)` and `complex(nan, nan)` are the same).
> Add proper handling of NaN values in `dpnp.unique` implementation with axis not None

- .github/workflows/generate_coverage.yaml
The PR proposes to limit numpy version installed for coverage job till #1985 is merged.
> Install `numpy<2.0a` in code coverage GitHub action

- .pre-commit-config.yaml
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_misc.py
The PR proposes to implement `dpnp.real_if_close` function.
The implementation is done through existing python calls.
Existing third party tests are unmuted. And new tests are added to cover different use cases.
> Add implementation of `dpnp.real_if_close`

- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_sumprod.py
The PR proposes to implement `dpnp.trapezoid` function.
The implementation is done through existing python calls.
Existing third party tests are unmuted. And new tests are added to cover different use cases.
Note that in numpy prior 2.0 version there is `numpy.trapz` function which was deprecated and new function `numpy.trapezoid` was added since 2.0. Thus the PR proposes to implement `dpnp.trapezoid` function from the beginning, rather than `dpnp.trapz` one which is going to be removed in future numpy versions.
> Add implementation of `dpnp.trapezoid`

- .github/workflows/conda-package.yml
- conda-recipe/meta.yaml
Build conda packages with NumPy 2.0 in the build environment. The `meta.yaml` file for `dpnp` was changed to not use `pin_compatible('numpy', min='x.x', max='x')` per migration guidelines from conda-forge.
Testing should still pick NumPy 1.26.4 from Intel channel.
> Build with numpy 2.0

- dpnp/backend/extensions/lapack/evd_batch_common.hpp
- dpnp/backend/extensions/lapack/evd_common.hpp
- dpnp/backend/extensions/lapack/evd_common_utils.hpp
- dpnp/backend/extensions/lapack/geqrf.cpp
- dpnp/backend/extensions/lapack/geqrf.hpp
- dpnp/backend/extensions/lapack/geqrf_batch.cpp
- dpnp/backend/extensions/lapack/gesv.cpp
- dpnp/backend/extensions/lapack/gesv.hpp
- dpnp/backend/extensions/lapack/gesv_batch.cpp
- dpnp/backend/extensions/lapack/gesv_common_utils.hpp
- dpnp/backend/extensions/lapack/getrf.cpp
- dpnp/backend/extensions/lapack/getrf.hpp
- dpnp/backend/extensions/lapack/getrf_batch.cpp
- dpnp/backend/extensions/lapack/getri.hpp
- dpnp/backend/extensions/lapack/getri_batch.cpp
- dpnp/backend/extensions/lapack/getrs.cpp
- dpnp/backend/extensions/lapack/getrs.hpp
- dpnp/backend/extensions/lapack/heevd.cpp
- dpnp/backend/extensions/lapack/heevd_batch.cpp
- dpnp/backend/extensions/lapack/orgqr.cpp
- dpnp/backend/extensions/lapack/orgqr.hpp
- dpnp/backend/extensions/lapack/orgqr_batch.cpp
- dpnp/backend/extensions/lapack/potrf.cpp
- dpnp/backend/extensions/lapack/potrf.hpp
- dpnp/backend/extensions/lapack/potrf_batch.cpp
- dpnp/backend/extensions/lapack/syevd.cpp
- dpnp/backend/extensions/lapack/syevd_batch.cpp
- dpnp/backend/extensions/lapack/ungqr.cpp
- dpnp/backend/extensions/lapack/ungqr.hpp
- dpnp/backend/extensions/lapack/ungqr_batch.cpp
This PR suggests updating `dpnp lapack` extensions :
1. Pass `sycl::queue` by reference
2. Pass  `dpctl::tensor::usm_ndarray` by constant reference
It is necessary to avoid unnecessary copying
Additionally it changes the name of `q` variable to `exeq_q` in some functions to follow the common code style
> Update lapack extensions

- dpnp/fft/dpnp_utils_fft.py
- tests/test_fft.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/fft_tests/test_fft.py
In this PR, a few tests are updated to avoid failure in comparison with NumPy 2.0. Also, third party tests are updated to avoid deprecated warning from NumPy 2.0 for "if `s` is given, `axes` cannot be `None`".
> update tests for `dpnp.fft` module to avoid failures and warning with NumPy 2.0

- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- tests/third_party/cupy/creation_tests/test_from_data.py
The `copy` keyword behavior changes in `numpy.asarray` and `numpy.array` during migration to NumPy 2.0 (see [link](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword) for details).
The PR propose to align `dpnp.array` behavior with the changes done for `numpy.asarray`.
And also to add `copy` keyword to `dpnp.asarray`, which has been already present in `dpctl.tensor` interface for a time.
All the impacted tests are updated to cover any numpy version between 1.23 and 2.0.
> Add `copy` keyword to `dpnp.asarray` and align `dpnp.array(..., copy=None)` with NumPy 2.0

- dpnp/backend/extensions/ufunc/CMakeLists.txt
- dpnp/backend/extensions/ufunc/elementwise_functions/heaviside.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/heaviside.hpp
- dpnp/backend/kernels/elementwise_functions/heaviside.hpp
- dpnp/dpnp_iface_mathematical.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_misc.py
The PR proposes to add implementation of `dpnp.heaviside` function.
The new dedicated `_heaviside` function is added to `_ufunc_impl` pybind11 extension.
All the required tests are implement to cover the function.
> Add implementation of `dpnp.heaviside` function

- CMakeLists.txt
The PR updates CMakeLists.txt to pull pybind11 `2.13.5` up from `2.13.3`.
> Use Pybind11 `2.13.5` to build dpnp

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_sorting.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/dpnp_utils/dpnp_utils_einsum.py
- tests/test_linalg.py
- tests/third_party/cupy/linalg_tests/test_einsum.py
In this PR, 
1) new tests are added for `dpnp.einsum` and accordingly a few updates are made in the code to pass all the test.
2) The tests are update to pass with any numpy version between 1.23 and 2.0.
3) docsting of several functions are updated to be consistent with each other.
> Add new tests for `dpnp.einsum` and adopt it with `NumPy-2.0.0`

- doc/reference/manipulation.rst
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_nanfunctions.py
- tests/test_arraycreation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
- tests/third_party/cupy/manipulation_tests/test_kind.py
In this PR,
1) `dpnp.append` and `dpnp.asarray_chk_finite` are implemented
2) `order` keyword in `eye`, `ones`, `zeros`, `full`, and `empty` functions in NumPy only supports `"C"` and `"F"`, and `dpnp` does not have any limitation in this regard. Docstring of these functions in `dpnp` is updated to reflect this fact.
> Implementation of `dpnp.append` and `dpnp.asarray_chkfinite`

- doc/index.rst
- doc/known_words.txt
- doc/reference/binary.rst
- doc/reference/fft.rst
- doc/reference/random.rst
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/fft/__init__.py
- dpnp/fft/dpnp_iface_fft.py
- dpnp/linalg/dpnp_iface_linalg.py
- tests/test_arraymanipulation.py
- tests/test_bitwise.py
- tests/test_manipulation.py
- tests/test_mathematical.py
- tests/test_umath.py
In this PR, the following aliases which are introduced in `NumPy 2.0` are added to `dpnp`: `dpnp.acos`, `dpnp.acosh`, `dpnp.asin`, `dpnp.asinh`, `dpnp.atan`, `dpnp.atanh`, `dpnp.atan2`, `dpnp.bitwise_invert`, `dpnp.bitwise_left_shift`, `dpnp.bitwise_right_shift`, `dpnp.pow`, `dpnp.permute_dims`, `dpnp.concat`, and `dpnp.linalg.matmul`.
In addition, doc is updated to avoid error and warning generated during `Build Sphinx / Build and Deploy Docs`.
> Implement aliases introduced in `NumPy 2.0`

- README.md
- doc/quick_start_guide.rst
This PR removes the wheels installation with Anaconda from the instruction, since we will no longer be able to upload packages to Anaconda. And so far, wheels can only be uploaded on Pypi
> Remove the wheels installation with anaconda from the instruction

- conda-recipe/meta.yaml
The package is a pseudo-package which creates symbolic link to ${PREFIX}/etc/OpenCL/vendors to /etc/OpenCL/vendors/intel.icd which load implementation library for Intel OpenCL GPU devices.
Availability of this device is required by oneMKL, and hence this is added to dpnp, rather than to dpctl.
> Add runtime dependency on intel-gpu-ocl-icd-system package

- .github/workflows/conda-package.yml
- dpnp/dpnp_iface_indexing.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_indexing.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
implemented dpnp.ravel_multi_index and dpnp.unravel_index.
Added tests.
> Implement dpnp.ravel_multi_index and dpnp.unravel_index

- CMakeLists.txt
- dpnp/backend/extensions/fft/common.hpp
OneMKL FFT 2025.0.0 includes some backward incompatible changes. However, code can not be updated with these changes yet since public CI is still using older version of OneMKL.  To keep `dpnp` working with both new compiler/MKL pakcge and the old one, a compile flag is defined to compile the proper part of the code based on the compiler version.
> Add a `COMPILER_VERSION_2025_OR_LATER` to be able to run `dpnp` with both 2024.2 and 2025.0 versions of the compiler/MKL

- CHANGELOG.md
The PR populates `CHANGELOG.md` for ongoing `0.16.0` release.
> update CHANGELOG.md for 0.16.0 release

- conda-recipe/meta.yaml
This change pins compile-time version of the compiler to 2025.0.0 and host MKL version to 2025.0.0, and restricts the range of compiler runtime and MKL libraries accordingly for dpnp=0.16.0.
> Pin compiler at build time to 2025.0 for 0.16.x release

- tests/third_party/cupy/core_tests/test_core.py
- tests/third_party/cupy/core_tests/test_ndarray.py
The PR extends test coverage of `dpnp.size` implemented in #2014 by enabling third party tests for the function.
The affected tests are unmuted in `test_ndarray.py` scope and the new `test_core.py` with more third party tests of core functionality.
> Enable third party tests for dpnp.size

- dpnp/dpnp_iface_mathematical.py
- tests/third_party/cupy/core_tests/test_ndarray.py
The PR proposes to clean the code and to remove the TODO which is no plan to be implemented.
The `shape.setter` documentation in both `dpnp.ndarray` and `usm_ndarray` clearly states that only non-negative new shape value is supported. And it is suggested to use `dpnp.reshape` instead (numpy recommends the same).
> Remove TODO from the code as no plan to support negative values in shape setter

- doc/reference/manipulation.rst
The PR proposes to update the documentation with the latest changes done in numpy and to list new functions which were implemented as aliases in dpnp.
> Update documentation page with `Manipulation routine`

- dpnp/dpnp_iface_manipulation.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
The PR proposes to implement a fix for test from `tests/third_party/cupy/manipulation_tests/test_add_remove.py` scope failing with a device without fp64 support.
Additionally formatting issues in description of `dpnp.append` and `dpnp.asarray_chkfinite` were resolved and `dpnp.asarray_chkfinite` was moved in `dpnp/dpnp_iface_manipulation.py` file to keep lexicographical order.
> Fix failing test for `dpnp.append` when no fp64 for device

- tests/third_party/cupy/core_tests/test_core.py
- tests/third_party/cupy/core_tests/test_ndarray.py
This PR backports of #2031 from development branch to `maintenance/0.16.x`.
> Backport gh-2031

- dpnp/dpnp_iface_mathematical.py
- tests/third_party/cupy/core_tests/test_core.py
- tests/third_party/cupy/core_tests/test_ndarray.py
This PR backports of #2032 from development branch to `maintenance/0.16.x`.
> Backport gh-2032

- CHANGELOG.md
The PR adds entries to `CHANGELOG.md` regarding backported PRs (#2032, #2033 and #2034) to `maintenance/0.16.x` branch.
> Update changelog with backported gh-2032, gh-2033 and gh-2034

- CMakeLists.txt
The PR updates CMakeLists.txt to pull pybind11 `2.13.6` up from `2.13.5`.
> Use Pybind11 `2.13.6` to build dpnp

- CHANGELOG.md
- CMakeLists.txt
- dpnp/backend/extensions/fft/common.hpp
In continuation of #2025, the code is modified to use `INTEL_MKL_VERSION` flag to determine which version of MKL is installed and being used and accordingly run the proper part of the code.
> Use `INTEL_MKL_VERSION` flag

- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
- tests/third_party/cupy/manipulation_tests/test_rearrange.py
In this PR, `dpnp.rot90` and `dpnp.resize` are implemented.
Note that the `dpnp.ndarray.resize` behaves different than `dpnp.resize` and will be addressed separately.
> Implement `dpnp.rot90` and `dpnp.resize`

- CHANGELOG.md
The PR adds entries to `CHANGELOG.md` regarding backported #2041 and #2030 to `maintenance/0.16.x` branch.
> Update changelog with backported gh-2041 and gh-2030

- CHANGELOG.md
- CMakeLists.txt
- dpnp/backend/extensions/fft/common.hpp
- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
- tests/third_party/cupy/manipulation_tests/test_rearrange.py
This PR backports of #2035 from development branch to `maintenance/0.16.x`.
> Backport gh-2035

- CHANGELOG.md
- doc/reference/indexing.rst
- doc/reference/ndarray.rst
- dpnp/dpnp_iface_indexing.py
- tests/test_indexing.py
The PR is intended to resolve an exception raised while passing input array of `usm_ndarray` type.
The test is added to cover the scenario. Also small improvements to existing tests are implemented.
> Add proper handling of unput array of `usm_ndarray` type in `dpnp.ix_`

- .github/workflows/conda-package.yml
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/third_party/cupy/indexing_tests/test_generate.py
The PR proposes to enable all tests scopes from `indexing_tests` folder in public CI.
While `tests/third_party/cupy/indexing_tests/test_generate.py` is updated with the recent latest changes in third party tests.
> Enable the whole scope of indexing tests in public CI

- CHANGELOG.md
- doc/reference/indexing.rst
- doc/reference/ndarray.rst
- dpnp/dpnp_iface_indexing.py
- tests/test_indexing.py
This PR backports of #2047 from development branch to `maintenance/0.16.x`.
> Backport gh-2047

- CHANGELOG.md
- dpnp/dpnp_iface_manipulation.py
- tests/test_arraymanipulation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/manipulation_tests/test_kind.py
In this PR, `dpnp.require` is implemented.
> implementation of `dpnp.require`

- dpnp/dpnp_iface_indexing.py
This PR backports of #2053 from development branch to `maintenance/0.16.x`.
> Backport gh-2053

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
Based on information stated [here](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/):
> With the [Miniforge 23.3.1 release](https://github.com/conda-forge/miniforge/releases/tag/23.3.1-0), the Miniforge and Mambaforge installers became essentially identical. The only difference between the two was their name and, subsequently, the default installation directory.
The PR proposes to remove `miniforge-variant: Mambaforge` option from the setup of `conda-incubator/setup-miniconda` per each affected GitHub action. The removed option will assume to use Miniforge installer inside the actions and will help to get rid of deprecation warning in the logs.
> Use Miniforge installer in GutHub actions

- CHANGELOG.md
- dpnp/backend/extensions/elementwise_functions/elementwise_functions.hpp
- dpnp/backend/extensions/lapack/common_helpers.hpp
- dpnp/backend/extensions/lapack/geqrf.cpp
- dpnp/backend/extensions/lapack/geqrf_batch.cpp
- dpnp/backend/extensions/lapack/gesv.cpp
- dpnp/backend/extensions/lapack/gesv_batch.cpp
- dpnp/backend/extensions/lapack/gesv_common_utils.hpp
- dpnp/backend/extensions/lapack/gesvd.cpp
- dpnp/backend/extensions/lapack/gesvd_batch.cpp
- dpnp/backend/extensions/lapack/getrf.cpp
- dpnp/backend/extensions/lapack/getrf_batch.cpp
- dpnp/backend/extensions/lapack/getri_batch.cpp
- dpnp/backend/extensions/lapack/getrs.cpp
- dpnp/backend/extensions/lapack/heevd.cpp
- dpnp/backend/extensions/lapack/heevd_batch.cpp
- dpnp/backend/extensions/lapack/orgqr.cpp
- dpnp/backend/extensions/lapack/orgqr_batch.cpp
- dpnp/backend/extensions/lapack/potrf.cpp
- dpnp/backend/extensions/lapack/potrf_batch.cpp
- dpnp/backend/extensions/lapack/syevd.cpp
- dpnp/backend/extensions/lapack/syevd_batch.cpp
- dpnp/backend/extensions/lapack/ungqr.cpp
- dpnp/backend/extensions/lapack/ungqr_batch.cpp
The PR replaces `sycl::free` with `dpctl::tensor::alloc_utils::sycl_free_noexcept` from dpctl tensor headers.
Replaced calls to `sycl::free` in `host_task` with use of `sycl_free_noexcept`.
This change should improve stability of test suite run executed on CPU device due to a known issue.
> Replace sycl::free with `sycl_free_noexcept`

- CHANGELOG.md
- dpnp/backend/extensions/elementwise_functions/elementwise_functions.hpp
- dpnp/backend/extensions/lapack/common_helpers.hpp
- dpnp/backend/extensions/lapack/geqrf.cpp
- dpnp/backend/extensions/lapack/geqrf_batch.cpp
- dpnp/backend/extensions/lapack/gesv.cpp
- dpnp/backend/extensions/lapack/gesv_batch.cpp
- dpnp/backend/extensions/lapack/gesv_common_utils.hpp
- dpnp/backend/extensions/lapack/gesvd.cpp
- dpnp/backend/extensions/lapack/gesvd_batch.cpp
- dpnp/backend/extensions/lapack/getrf.cpp
- dpnp/backend/extensions/lapack/getrf_batch.cpp
- dpnp/backend/extensions/lapack/getri_batch.cpp
- dpnp/backend/extensions/lapack/getrs.cpp
- dpnp/backend/extensions/lapack/heevd.cpp
- dpnp/backend/extensions/lapack/heevd_batch.cpp
- dpnp/backend/extensions/lapack/orgqr.cpp
- dpnp/backend/extensions/lapack/orgqr_batch.cpp
- dpnp/backend/extensions/lapack/potrf.cpp
- dpnp/backend/extensions/lapack/potrf_batch.cpp
- dpnp/backend/extensions/lapack/syevd.cpp
- dpnp/backend/extensions/lapack/syevd_batch.cpp
- dpnp/backend/extensions/lapack/ungqr.cpp
- dpnp/backend/extensions/lapack/ungqr_batch.cpp
This PR backports of #2058 from development branch to `maintenance/0.16.x`.
> Backport gh-2058

- tests/third_party/cupy/core_tests/test_flags.py
The PR is about to add `test_flags` scope to third party tests of dpnp for proper verification of flags behavior.
> Add test_flags scope to third party tests of dpnp

- CHANGELOG.md
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- tests/test_product.py
In this PR, implementation of `dpnp.kron` is updated to get rid of unnecessary copy for non-contiguous arrays. There is no need to make input arrays contiguous before performing the calculations. In addition, the final result would be `c_contiguous` regardless of the status in the middle steps.
> Improve implementation of `dpnp.kron` to avoid unnecessary copy for non-contiguous arrays

- CHANGELOG.md
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- tests/test_product.py
This PR backports of https://github.com/IntelPython/dpnp/pull/2059 from development branch to `maintenance/0.16.x`.
> Backport gh-2059

- CHANGELOG.md
- tests/test_sycl_queue.py
The PR implements a temporary workaround to prevent crash in dpnp tests on Windows in internal CI/CD jobs (when running on either Lunar Lake or Arrow Lake machine).
The w/a has to be removed once the issue is resolved.
> Add workaround to prevent crash on Windows in internal CI/CD

- CHANGELOG.md
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
The PR resolves crash in `dpnp.choose` observing in internal CI/CD flow on PVC machine with Linux OS.
The issue was caused by missing dependency of temporary allocated device memory on a computing event. Thus the memory was released before the execution kernel completes work,
While allocation of temporary memory was implicit, because `DPNPC_ptr_adapter` constructor identified the input pointer `choices1` as of unknown USM allocation type. And it was valid classification, since the pointer was allocated in host memory for holding a list of pointers on arrays in device memory.
The change assumes to request explicit memory transfer for `choices1` pointer from host to device memory and to add a dependency from the temporary allocated device memory on the event from the submitted kernel.
> Resolve crash identified in backend implementation of `dpnp.choose`

- CHANGELOG.md
- dpnp/backend/kernels/dpnp_krnl_indexing.cpp
This PR backports of https://github.com/IntelPython/dpnp/pull/2063 from development branch to `maintenance/0.16.x`.
> Backport gh-2063

- .gitignore
- CHANGELOG.md
- dpnp/backend/kernels/dpnp_krnl_random.cpp
- dpnp/backend/src/queue_sycl.cpp
This PR backports of https://github.com/IntelPython/dpnp/pull/2066 from development branch to `maintenance/0.16.x`.
> Backport gh-2066

- CHANGELOG.md
- dpnp/fft/dpnp_utils_fft.py
In this PR, an issue regarding asynchronous execution of  `dpnp.fft` module is resolved. In the process of padding the input arrays, dependent event list (`dep_evs`) was obtained before creating the new zero array which by itself add a new dependent event to `dep_evs` list. So, we need to get `dep_evs` after calling `dpnp.zeros`.
> Fix an issue with asynchronous execution in `dpnp.fft` module

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
- tests/test_fft.py
In this PR, FFT test suite is updated to avoid initializing input arrays with `dpnp.empty` which might produce invalid data.
> update the test suit for `dpnp.fft` module

- CHANGELOG.md
- pyproject.toml
- tests/test_fft.py
This PR backports of https://github.com/IntelPython/dpnp/pull/2071 from development branch to `maintenance/0.16.x`.
> backport-gh-2071

- CHANGELOG.md
- dpnp/dpnp_iface_mathematical.py
- tests/third_party/cupy/math_tests/test_misc.py
This PR suggests using `a_min` and `a_max` arguments of `dpnp.clip()` as `None` by default to align with Numpy 2.0 instead of using `np.NoValue` as in Numpy=2.0 and also updates cupy tests for this function
> Update `dpnp.clip()` with Numpy 2.0

- CHANGELOG.md
- tests/third_party/cupy/linalg_tests/test_solve.py
This PR suggests skipping some cupy tests for `dpnp.linalg.solve()` until `dpnp.linalg.solve()` is updated to support numpy>=2.0
> Update cupy tests for dpnp.linalg.solve()

- CHANGELOG.md
- dpnp/dpnp_iface_mathematical.py
- tests/third_party/cupy/linalg_tests/test_solve.py
- tests/third_party/cupy/math_tests/test_misc.py
This PR backports of #2048 and #2074  from development branch to maintenance/0.16.x.
> Backport gh-2048 & gh-2074

- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
The PR proposes to relax upper numpy version which can be used by dpnp tests through GitHub actions.
The PR is assumed to be merged once all dpnp tests are adopted towards to NumPy 2.0.
> Enable dpnp tests with NumPy 2.0 in public CI

- conda-recipe/meta.yaml
The PR pins a dependency on dpctl using final tag `0.18.0`.
> Pin dpctl to `0.18.0` version

- tests/third_party/cupy/manipulation_tests/test_rearrange.py
There was issue#27431 resolved since NumPy 2.1.2 which allows unsigned shift argument value for `numpy.roll`.
Thus `test_roll_invalid_shift` test from `tests/third_party/cupy/manipulation_tests/test_rearrange.py::TestRollTypeError` scope will no raise `TypeError` in that case.
[dpctl#1857](https://github.com/IntelPython/dpctl/issues/1857) is filed to address the same issue in dpctl.
Meanwhile that PR proposes to limit the test run by `numpy<2.1.2` condition and to update the test again once the issue is resolved by dpctl.
> Limit a test run for `roll` function by NumPy version

- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- tests/test_arraycreation.py
- tests/third_party/cupy/creation_tests/test_basic.py
In this PR, support for `order="K"` and `order="A"` is added to for `dpnp.empty_like`, `dpnp.ones_like`, `dpnp.zeros_like` and `dpnp.full_like`.
> Add support for `order="K"` or `"A"` for `dpnp.empty_like`, `dpnp.ones_like`, `dpnp.zeros_like` and `dpnp.full_like`

- doc/reference/linalg.rst
- dpnp/linalg/dpnp_iface_linalg.py
- tests/test_linalg.py
This PR suggests adding a new implementation of `dpnp.linalg.svdvals()` function that was implemented in [Numpy 2.0](https://numpy.org/devdocs/release/2.0.0-notes.html#svdvals-for-numpy-linalg) 
This function is Array API compatible:
```
array_api_tests/test_linalg.py::test_svdvals PASSED 
```
> Add implementation of `dpnp.linalg.svdvals()`

- README.md
- doc/quick_start_guide.rst
TDO team has deployed pypi channel, which will be used starting from the 2025 release. This PR updates the instructions by adding the installation from Intel pypi channel
> Add Intel channel for installing wheels

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
- tests/third_party/cupy/manipulation_tests/test_shape.py
In this PR, `dpnp.reshape` and `dpnp.ndarray.reshape` are updated to align with changes in `NumPy 2.1` and support for `order="A"` is added.
Accordingly, `dpnp.ravel` is also updated.
> update `dpnp.reshape` to use `shape` keyword argument instead of `newshape`

- CHANGELOG.md
- README.md
- doc/quick_start_guide.rst
This PR backports of #2098 from development branch to `maintenance/0.16.x`.
> Backport gh-2098

- CHANGELOG.md
The PR updates `CHANGELOG.md` with proper release date for `0.16.0`.
> Set release date for `0.16.0`

- tests/third_party/cupy/linalg_tests/test_product.py
The PR proposes to mute warnings while running tests for `dpnp.cross`.
> Mute deprecation warning in tests for dpnp.cross

- dpnp/dpnp_utils/dpnp_utils_einsum.py
- dpnp/dpnp_utils/dpnp_utils_statistics.py
- tests/test_linalg.py
In this PR, code is modified and new tests are added to increase coverage for `dpnp_iface_linearalgebra.py` and `dpnp_utils/dpnp_utils_einsum.py` to 100% and improves coverage for `dpnp_utils/dpnp_utils_statistics.py`
> improve coverage

- dpnp/backend/include/dpnp_iface.hpp
- dpnp/backend/include/dpnp_iface_fptr.hpp
- dpnp/backend/kernels/dpnp_krnl_sorting.cpp
- dpnp/backend/kernels/dpnp_krnl_statistics.cpp
- dpnp/backend/src/dpnp_fptr.hpp
- dpnp/dpnp_algo/dpnp_algo.pxd
- dpnp/dpnp_algo/dpnp_algo_statistics.pxi
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_sorting.py
- dpnp/dpnp_iface_statistics.py
- tests/test_mathematical.py
- tests/test_sort.py
- tests/test_statistics.py
- tests/test_strides.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/statistics_tests/test_meanvar.py
In this PR, `dpnp.median` is implemented using existing functions in dpnp including `dpnp.sort`.
> implement `dpnp.median`

- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_utils/dpnp_utils_einsum.py
- tests/test_linalg.py
- tests/third_party/cupy/linalg_tests/test_einsum.py
In NumPy 2.0 and above, `numpy.einsum` function follows [NEP-50](https://numpy.org/neps/nep-0050-scalar-promotion.htm) while in previous version it was not followed.
`dpnp.einsum` is updated to behave similarly.
New behavior in `NumPy` and update `dpnp` on this branch:
```python
import numpy as np
np.__version__
a=np.ones(2, dtype=np.float32)
np.einsum(",i->", 3., a)
import dpnp
a_dp=dpnp.ones(2, dtype=dpnp.float32)
dpnp.einsum(",i->", 3., a_dp).dtype # on a device with support for double precision
```
Old behavior in `NumPy` and `dpnp`:
```python
import numpy as np
np.__version__
a=np.ones(2, dtype=np.float32)
np.einsum(",i->", 3., a).dtype
import dpnp
a_dp=dpnp.ones(2, dtype=dpnp.float32)
dpnp.einsum(",i->", 3., a_dp).dtype
```
> Update `dpnp.einsum` to align with NEP-50

- dpnp/dpnp_iface_logic.py
- tests/test_logic.py
- tests/third_party/cupy/logic_tests/test_type_test.py
This PR suggests adding an implementation of `dpnp.isfortran()` to check if the array is Fortran-contiguous using a call to `dpnp.ndarray.flags.fnc` attribute.
> Add implementation of `dpnp.isfortran()`

- .github/workflows/conda-package.yml
- tests/third_party/cupy/test_type_routines.py
This PR updates tests for `dpnp.result_type` to align with recent changes in https://github.com/IntelPython/dpctl/pull/1877
> update `dpnp.result_type` tests

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- conda-recipe/meta.yaml
The PR is about to unblock GitHub actions until all components from `2025.0` release will be published (currently it's done only for part of components which breaks the workflows).
> Implement a temporary workaround to avoid usage of `2025.0` components in GutHub actions

- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- tests/test_linalg.py
In this PR, `rtol` kwarg is added to  `dpnp.linalg.pinv` and `dpnp.linalg.matrix_rank` to align with NumPy 2.0.
> add `rtol` kwarg to `dpnp.linalg.pinv` and `dpnp.linalg.matrix_rank`

- tests/test_sycl_queue.py
This PR suggests skipping `test_solve` with `3D_Matrix_and_Vectors` in `test_sycl_queue.py` until dpnp.linalg.solve() is updated to support numpy>=2.0
Also removes skip for SAT-6842 due to irrelevance (Issue has been fixed)
> Skip test_solve with 3D matrix for numpy 2.0

- dpnp/dpnp_iface_arraycreation.py
- tests/test_arraycreation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/creation_tests/test_from_data.py
In this PR, support for `ndmin` kwarg is added for `dpnp.array` , new tests are added and cupy tests are updated to include relevant test cases.
In addition, test classes in `test_manipulation` are re-ordered to follow alphabetic order:
> add support for kwarg `ndmin` for `dpnp.array`

- doc/reference/binary.rst
- doc/reference/linalg.rst
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- dpnp/linalg/dpnp_iface_linalg.py
- tests/test_mathematical.py
- tests/test_product.py
- tests/test_sycl_queue.py
- tests/test_umath.py
- tests/test_usm_type.py
In this PR, `dpnp.vecdot` and `dpnp.linalg.vecdot` are implemented.
> implement `dpnp.vecdot` and `dpnp.linalg.vecdot`

- tests/third_party/cupy/sorting_tests/test_search.py
The slow mark was implemented in scope of #1831.
So the PR is about to remove `pytest.mark.skip` around slow tests, because tests deselecting is now done through `slow` mark.
> Remove `pytest.mark.skip`, since slow mark is supported

- tests/test_arraypad.py
In this PR, a test for `dpnp.pad` with `mode="empty"` is updated to avoid direct comparison since in "empty" mode, arrays are uninitialized and comparing may fail.
> updating a test for `dpnp.pad` with `mode="empty"` to avoid direct comparison

- dpnp/dpnp_iface_indexing.py
- tests/test_indexing.py
The PR proposes to leverage on dpctl.tensor implementation in `dpnp.put_along_axis` function.
Additionally, the function signature is extended with new keyword `mode` to provide a control how out-of-bounds indices will be handled.
> Leverage on dpctl.tensor implementation in `dpnp.put_along_axis`

- .github/workflows/build-sphinx.yml
The PR enables posting a comment with link to rendered documentation for a PR from forked repository.
Previously the check was based on repo data of a pull request entry (i.e. `github.event.pull_request.head.repo`). It means the step with comment will be disable for a PR created in forked repo. But it can merged either into fork repo itself or into original repo (i.e. the repo it was forked from). And the second option is valid, i.e. it has to be allowed posting a comment with docs for a PR coming from the fork but into the origin repo.
To do that it is proposed to check `fork` property of `github.event.pull_request.base.repo` entry, i.e. info about repo where the PR is going to be merged.
> Post a comments with link to built docs for PR from forked repo

- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/manipulation_tests/test_add_remove.py
In this PR, `dpnp.delete` is implemented.
> implement `dpnp.delete`

- doc/reference/ndarray.rst
- dpnp/dpnp_array.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- tests/test_mathematical.py
This PR adds support for inplace matrix multiplication via the `@=` operator.
Also the PR refactors the tests from `TestMatmulInvalidCases` class and corrects type of exception raised for invalid value passed to `axes` keyword to report `AxisError` exception there.
> Add inplace matrix multiplication

- .github/workflows/conda-package.yml
This PR suggests removing `TEST_SCOPE` env variable in `conda_package.yml`  to run all available dpnp tests in public CI
All test files have been updated and run successfully in `Generate coverage data for dpnp` [action](https://github.com/IntelPython/dpnp/actions/workflows/generate_coverage.yaml)
Running all dpnp test files in public CI has been checked in #2116 (https://github.com/IntelPython/dpnp/actions/runs/11703003323/job/32594634571?pr=2116) .
> Remove TEST_SCOPE to run all tests in public CI

- .github/workflows/generate_coverage.yaml
This PR suggests removing `--ignore test_random.py` for pytest  to run generate coverage on public CI.
`test_random.py` has been updated and runs successfully on public CI.
> Run all dpnp tests to generate coverage 

- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- tests/test_manipulation.py
This PR adds the implementation of `dpnp.broadcast_shapes`
> Add dpnp.broadcast_shapes implementation

- setup.cfg
- tests/third_party/cupy/testing/_helper.py
This PR suggests using `from packaging.requirements import Requirement` instead of  `import pkg_resources` to avoid DeprecationWarning.
These changes also remove ignoring of `DeprecationWarning` in `filterwarnings` pytest settings
> Fix DeprecationWarning: pkg_resources

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- conda-recipe/meta.yaml
The PR updates GutHub actions to adapt to changes in oneAPI Basekit 2025.0
- Modify step to add Intel repository
- Install Unified Memory Framework (UMF) component
- Install `hwloc` utility which is required by UMF
- Revert changes done in gh-2131 
- Bump required dpctl, DPC++ compiler and oneMKL versions in `meta.yaml`
The PR also includes minor improvements to pass `-e` to `bash` on Linux and to properly check if script activating OCL CPU RT exists before attempting to run it.
> Update GitHub actions to work with dependent components from `2025.0` release

- dpnp/dpnp_iface_manipulation.py
- tests/test_manipulation.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.insert` is implemented.
> implement `dpnp.insert`

- tests/test_arraypad.py
In this PR, a test for array padding is temporary muted because of https://github.com/IntelPython/dpctl/issues/1887
> temporary mute a test for `dpnp.pad`

- .github/workflows/build-sphinx.yml
In this PR, NumPy, CuPy and Python versions for building doc are updated to make sure comparison table of available functions in dpnp/NumPy/CuPy is up-to-date.
NumPy is updated from v1.23.5 to the current available v2.1.3.
CuPy is updated from v9.6.0 to the current available v13.3.0.
> bump NumPy, CuPy and Python versions in build doc

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
The latest release `conda-incubator/setup-miniconda=3.1.0` implements `conda-remove-defaults` option which enables postprocessing channels list to remove 'defaults' if it was added implicitly to the 'channels' setting.
Thus the PR proposes to use the option instead of previously implemented w/a with removing 'defaults' by a separate step.
> Enable `conda-remove-defaults` option of conda-incubator/setup-miniconda

- doc/reference/misc.rst
- dpnp/__init__.py
- dpnp/dpnp_iface_utils.py
- tests/test_array_utils.py
- tests/third_party/cupy/misc_tests/test_byte_bounds.py
This PR adds the implementation of `dpnp.byte_bounds`
> Add dpnp.byte_bounds implementation

- dpnp/dpnp_iface_sorting.py
- tests/test_sort.py
In this PR, support for `kind="mergesort"` and `kind="radixsort"` is added to `dpnp.sort` and `dpnp.argsort`.
> add support for `kind="mergesort"` or `"radixsort"` for `dpnp.sort` and `dpnp.argsort`

- dpnp/dpnp_iface_statistics.py
- tests/skipped_tests.tbl
- tests/skipped_tests_gpu.tbl
- tests/test_statistics.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/statistics_tests/test_correlation.py
Implementation of `corrcoef` function.
> Implementation of corrcoef

- .github/workflows/conda-package.yml
Looking into the overall time of the `Conda package` action, it looks `actions/cache` step doesn't provide significant speed up, but complicates the flow.
Thus the PR proposes to remove the steps.
> Remove `actions/cache` steps

- dpnp/backend/extensions/statistics/CMakeLists.txt
- dpnp/backend/extensions/statistics/bincount.cpp
- dpnp/backend/extensions/statistics/bincount.hpp
- dpnp/backend/extensions/statistics/common.hpp
- dpnp/backend/extensions/statistics/histogram.cpp
- dpnp/backend/extensions/statistics/histogram_common.cpp
- dpnp/backend/extensions/statistics/histogram_common.hpp
- dpnp/dpnp_iface_histograms.py
- dpnp/dpnp_iface_statistics.py
- tests/test_histogram.py
- tests/test_statistics.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/statistics_tests/test_histogram.py
- tests_external/skipped_tests_numpy.tbl
> Implementation of bincounts

- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/dpnp_iface_histograms.py
The PR switches to `group_load_store` experimental extension per deprecation warning for 2025.1 DPC++ compiler.
> Use `group_load_store` compiler extension

- doc/reference/fft.rst
- doc/reference/functional.rst
- doc/reference/linalg.rst
- doc/reference/logic.rst
- doc/reference/manipulation.rst
- doc/reference/random.rst
- doc/reference/routines.rst
- doc/reference/sorting.rst
- doc/reference/statistics.rst
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_functional.py
- dpnp/dpnp_iface_manipulation.py
- tests/test_functional.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/lib_tests/test_shape_base.py
In this PR, `dpnp.apply_along_axis` is implemented.
> implement `dpnp.apply_along_axis`

- dpnp/dpnp_iface_indexing.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.extract` implementation is updated to avoid violation of compute-follows-data when both input are `dpnp_array`.
> Update `dpnp.extract` to avoid violation of compute-follows-data

- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
In this PR, `dpnp.cumulative_sum` and `dpnp.cumulative_prod` are implemented which are Array API alternative for `dpnp.cumsum` and `dpnp.cumprod`, respectively.
> implement `dpnp.cumulative_sum` and `dpnp.cumulative_prod`

- dpnp/backend/extensions/ufunc/CMakeLists.txt
- dpnp/backend/extensions/ufunc/elementwise_functions/i0.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/i0.hpp
- dpnp/backend/kernels/elementwise_functions/i0.hpp
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_mathematical.py
- tests/test_mathematical.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
- tests/third_party/cupy/math_tests/test_special.py
The PR proposes to add implementation of `dpnp.i0` function.
The new dedicated `_i0` function are added to `_ufunc_impl` pybind11 extension.
All the required tests are implemented to cover the new functions.
Note that SYCL kernel for the elementwise function assumes to call `sycl::ext::intel::math::cyl_bessel_i0` where possible or to rely on own implementation based on source from gcc repo.
> Add implementation of `dpnp.i0`

- dpnp/dpnp_iface_functional.py
- dpnp/tests/test_functional.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
In this PR, `dpnp.apply_over_axes` is implemented.
> implement `dpnp.apply_over_axes`

- dpnp/dpnp_iface_manipulation.py
- dpnp/tests/test_arraymanipulation.py
- dpnp/tests/test_manipulation.py
In this PR, coverage for `dpnp_iface_manipulation.py` file is improved to be at 100%.
> improve coverage `dpnp_iface_manipulation.py`

- .github/workflows/conda-package.yml
`Upload` job has been failing since version of `conda-incubator/setup-miniconda` was bumped up to `3.1.0`.
It seems `mamba install` doesn't properly work on Windows if the default job's shell is specified as `bash -el {0}`.
Since it doesn't look proper to use `bash -el {0}` as the Windows default shell, this PR proposes to remove that and to rely on default shell setting for a job.
> Do not use bash as default shell on Windows in Upload job

- dpnp/tests/test_mathematical.py
The PR propose to add seeding of random state to normalize generated data in tests which sporadically failed in internal CI.
> Add seeding before generating random data in faulty tests

- dpnp/tests/test_random_state.py
This PR suggests removing test skip for **test_dist** in **TestNormal** and ### TestRandN  since the problem has been fixed in MKL since 2024.2.1 version.
These tests pass successfully in public CI on Windows.
> Unskip test_distr in TestNormal and TestRandN

- .github/workflows/conda-package.yml
The PR rolls back a part of changes done in #2179, because the `Upload` step started to be failed on Linux.
Instead it proposes to configure default shell per OS in `Upload` step.
> Configure default shell per OS in `Upload` step

- dpnp/backend/kernels/elementwise_functions/i0.hpp
DPC++ compiler released 2025.0.1 version where `__SYCL_COMPILER_VERSION` is defined to `20241113`. But the fix for `sycl::ext::intel::math::cyl_bessel_i0(x)` support wasn't mapped there.
Thus the PR proposes to bump `__SYCL_COMPILER_BESSEL_I0_SUPPORT` define up to `20241114` value to exclude DPC++ compiler 2025.0.1 version.
> Bump DPC++ compiler min version required for proper work of `sycl::cyl_bessel_i0()`

- doc/_templates/autosummary/attribute.rst
- doc/_templates/autosummary/base.rst
- doc/_templates/autosummary/class.rst
- doc/_templates/autosummary/member.rst
- doc/_templates/autosummary/method.rst
- doc/_templates/autosummary/minimal_module.rst
- doc/_templates/autosummary/module.rst
- doc/conf.py
The PR proposes to update `autosummary` templates and to align them with the latest sphinx requirements and to implement similar to NumPy approach.
Also it adds autogenerated year for `copyright` setting.
> Update `autosummary` templates

- dpnp/dpnp_iface_functional.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_utils/dpnp_utils_pad.py
- dpnp/tests/test_indexing.py
The PR proposes to add `dpnp.ndindex` class. The implementation is fully leveraged on appropriate class in NumPy.
The tests are added to cover the new functionality.
> Add support of `dpnp.ndindex` class

- .github/workflows/cron-run-tests.yaml
The PR proposes to add a workflow which runs nightly and includes installing dpnp from `dppy/label/dev` and running tests. It will cover both Linux and Windows.
This PR ensures tests are run even if no development happens. The intent is it might catch issues due to external dependency updates, and such.
The workflow can also be triggered manually.
> Add a workflow to run nightly tests

- .github/workflows/check-mkl-interfaces.yaml
- CMakeLists.txt
- scripts/build_locally.py
The PR proposes to bump oneMKL version up to latest release `0.6`.
Also as a validation step it is proposed to add GitHub action with will build dpnp with oneMKL interface on Linux and run tests.
The action is not assumed to be run on Windows, because oneMKL has quite limited support there (i.e. no DFT support).
This PR implements new `--onemkl-interfaces-dir=` option of `python scripts/build_locally.py` script to pass a path towards a local checkout directory with oneMKL source.
The action is extended to consider the validation of the new option.
The PR closes #2163.
> Bump oneMKL version to `0.6` and add new `--onemkl-interfaces-dir` option

- .github/workflows/conda-package.yml
The PR proposes to switch `conda-build` version from `24.9.0` to `24.11.1`.
> Bump conda-build version from `24.9.0` to `24.11.1`

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_indexing.py
- dpnp/tests/test_indexing.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
- dpnp/tests/third_party/cupy/indexing_tests/test_indexing.py
This PR proposes an implementation for `dpnp.compress` using `dpctl.tensor` kernels.
`nonzero` is used to accumulate the `condition` into 1d array of indices, which are then used to take the appropriate slices of the array. When `axis` is `None`, the operand array is flattened.
The coupled `dpnp_array.compress` method is implemented through a simple call to the `compress` function,
> Implement `dpnp.compress` and `dpnp_array.compress` method

- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_trigonometric.py
This PR suggests to update the documentation of `parameters` of element-wise functions by adding `broadcasting` information to align with Numpy docs.
> Update doc of elementwise functions

- dpnp/fft/dpnp_utils_fft.py
- dpnp/tests/test_fft.py
FFT implementation validate arrays for supported strides/dtypes and if needed make a copy and cast (`_copy_array`).
Old implementation didn't validate for dtype in case of negative strides resulting in incorrect type selection in `_commit_descriptor` and failures on systems without `float64` support.
> Fix FFT negative strides case

- .github/workflows/conda-package.yml
The PR proposes to switch `conda-build` version rom `24.11.1` to `24.11.2`.
> Bump conda-build version from `24.11.1` to `24.11.2`

- dpnp/dpnp_array.py
- dpnp/tests/third_party/cupy/core_tests/test_iter.py
The PR proposes to add implementation of `dpnp.ndarray.__iter__` method.
The new code is assumed to be covered by third party tests.
> Implement `dpnp.ndarray.__iter__` method

- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/tests/third_party/cupy/creation_tests/test_ranges.py
Recent changes in DPC++ 2025.1 compiler broke DPNP compilation. It seems the legacy DPC++ compiler behavior was affected by introducing SYCL experimental extension for reduction properties.
Since the compilation issue occurred for a backend function which will be removed once #2183 is merged, that PR proposes to temporary w/a the issue and to reuse the extension for reduction properties, which seems working.
> Use SYCL experimental extension for reduction properties

- dpnp/dpnp_iface_indexing.py
- dpnp/tests/test_indexing.py
There was `__iter__` method of dpnp.ndarray implemented in scope of #2206.
While this PR proposes to add implementation of `dpnp.iterable` function which is intended to check if the object (including dpnp.ndarray) can be iterated over.
The implementation leverages on NumPy call, which is based on attempt to pass the object to `iter` function.
> Add `dpnp.iterable` function

- doc/conf.py
- dpnp/__init__.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/tests/test_dlpack.py
The PR proposes to move `dpnp.from_dlpack` function to `dpnp/dpnp_iface_arraycreation.py` and to update docstring description, because there were formatting issues with rendered documentation of `dpnp.from_dlpack`.
Also sphinx configuration was tuned to add mapping towards dpctl documentation pages.
> Move `dpnp.from_dlpack` to array creation routine

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
- CHANGELOG.md
- README.md
- dpnp/backend/kernels/dpnp_krnl_common.cpp
- tests/third_party/cupy/creation_tests/test_ranges.py
This PR backports of #2166, #2057 and #2211 from development branch to `maintenance/0.16.x`.
> Backport gh-2166, gh-2057, gh-2211

- CHANGELOG.md
- README.md
- dpnp/dpnp_iface_indexing.py
- tests/test_sycl_queue.py
- tests/test_usm_type.py
This PR backports of #2172 from development branch to `maintenance/0.16.x`.
> Backport gh-2172

- CHANGELOG.md
- doc/conf.py
- dpnp/__init__.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- tests/test_dlpack.py
This PR backports of #2209 from development branch to `maintenance/0.16.x`.
> Backport gh-2209

- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/tests/third_party/cupy/linalg_tests/test_decomposition.py
This PR suggests updating `dpnp.linagl.svd()` implementation to support running on CUDA devices.
Since cuSolver gesvd only supports m>=n ([Remark 1](https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverDN-lt-t-gt-gesvd)) the previous implementation crashed with `Segmentation fault (core dumped)`
```
$ ONEAPI_DEVICE_SELECTOR=cuda:gpu pytest -v dpnp/tests/test_linalg.py::TestSvd::test_svd
Python error: Segmentation fault
```
This suggests adding checks for `m>=n` otherwise transpose the input array.
Passing the transposed array to `oneapi::mkl::lapack::gesvd` increases the performance of `dpnp.linalg.svd()` due to the reducing a matrix with `m >= n` to bidiagonal form (inside `lapack::gesvd`) is more efficient
```
$ a_shape = (1024,2048)
$ na = generate_random_numpy_array(a_shape, …
```
> Update `dpnp.linalg.svd()` to run on CUDA 

- CHANGELOG.md
The PR proposes to populate `CHANGELOG.md` with changes done for `0.16.1` release.
> Populate changelog with `0.16.1` release

- .github/workflows/openssf-scorecard.yml
- dpnp/backend/extensions/statistics/CMakeLists.txt
- dpnp/backend/extensions/statistics/bincount.hpp
- dpnp/backend/extensions/statistics/common.cpp
- dpnp/backend/extensions/statistics/common.hpp
- dpnp/backend/extensions/statistics/dispatch_table.hpp
- dpnp/backend/extensions/statistics/histogram.cpp
- dpnp/backend/extensions/statistics/histogram.hpp
- dpnp/backend/extensions/statistics/histogram_common.cpp
- dpnp/backend/extensions/statistics/histogram_common.hpp
- dpnp/backend/extensions/statistics/sliding_dot_product1d.cpp
- dpnp/backend/extensions/statistics/sliding_dot_product1d.hpp
- dpnp/backend/extensions/statistics/sliding_window1d.cpp
- dpnp/backend/extensions/statistics/sliding_window1d.hpp
- dpnp/backend/extensions/statistics/validation_utils.cpp
- dpnp/backend/extensions/statistics/validation_utils.hpp
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_utils/dpnp_utils_common.py
- dpnp/tests/test_statistics.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
- dpnp/tests/third_party/cupy/statistics_tests/test_correlation.py
- tests_external/skipped_tests_numpy.tbl
* Implementation of dot product sliding window which is can be used to implement both `correlate` and `convolve` functions.
* Implementation of `correlate` function using dot product sliding window
> Implementation of correlate

- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_utils/dpnp_utils_statistics.py
- dpnp/tests/test_manipulation.py
- dpnp/tests/test_statistics.py
- dpnp/tests/test_umath.py
- dpnp/tests/third_party/cupy/manipulation_tests/test_add_remove.py
- dpnp/tests/third_party/cupy/statistics_tests/test_correlation.py
The PR proposes to align with changes implemented in `numpy 2.2`:
- Update `dpnp.cov` to properly transpose 2d array with `rowvar=False`.
- Handle boolean arrays in `dpnp.insert` as a mask.
- Mute or workaround tests with fail due to numpy issues in `numpy.insert` and `numpy.cov`.
- Mute tests with are not passing due to new numpy behavior (new `matvec` and `vecmat` ufuncs, support of 2d array in `trim_zeros`).
`matvec` and `vecmat` ufuncs and `trim_zeros` functions will be separately.
> Align with numpy 2.2

- dpnp/tests/third_party/cupy/sorting_tests/test_search.py
The PR proposes to extend third party tests with new nanargmin/nanargmax tests added recently.
> Add new nanargmin/nanargmax tests

- dpnp/tests/helper.py
- dpnp/tests/test_fft.py
- dpnp/tests/test_linalg.py
- dpnp/tests/test_mathematical.py
- dpnp/tests/test_product.py
- dpnp/tests/test_sort.py
- dpnp/tests/test_statistics.py
- dpnp/tests/test_sycl_queue.py
This is part 2 of a series of PRs in which the tests are refactored. In this PR, `test_linalg.py`, `test_product.py`, `test_statistics.py`, `test_fft.py`, and `test_sort.py` are updated.
Part 1 was https://github.com/IntelPython/dpnp/pull/2210.
The main change is to use a common function `generate_random_numpy_array` from `dpnp/tests/helper.py` for generating input array for different tests.
> updating tests - Part2

- dpnp/backend/kernels/dpnp_krnl_common.cpp
- dpnp/backend/kernels/elementwise_functions/i0.hpp
DPC++ compiler released 2025.0.4 version where `__SYCL_COMPILER_VERSION` is defined to `20241205`. But the fixes from #2211 and for `sycl::ext::intel::math::cyl_bessel_i0(x)` support weren't mapped there.
Thus the PR proposes to bump `__SYCL_COMPILER_REDUCTION_PROPERTIES_SUPPORT` and `__SYCL_COMPILER_BESSEL_I0_SUPPORT` defines up to `20241210` value to exclude DPC++ compiler 2025.0.4 version.
> Bump SYCL compiler min version required

- dpnp/tests/helper.py
- dpnp/tests/test_fft.py
- dpnp/tests/test_linalg.py
This PR suggests updating the helper function `generate_random_numpy_array()` by adding an argument `order` to generate arrays in different orders
Additionally 
Input generation for tests was changed in #2227  , now `test_fft2` and `test_fftn` do not use `order` parameter.
This PR suggests to update these tests to use input data with different orders
> Add `order` agrument to `generate_random_numpy_array()`

- dpnp/dpnp_utils/dpnp_utils_statistics.py
In this PR, implementation of `dpnp.nanmedian` is update to improve performance.
There is a significant improvement when `axis` is not `None` as shown in tables below.
```bash
Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Data Center GPU Max 1100 12.60.7 [1.6.31294+9]
Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8480+ OpenCL 3.0 (Build 0) [2024.18.9.0.28_160000]
```
```python
import dpnp, numpy
a = numpy.ones((16*8192, 32))
axis = 1
w = numpy.random.random((len(a.shape), 200)) * numpy.array(a.shape)[:, None]
w = w.astype(numpy.intp)
a[tuple(w)] = numpy.nan
%timeit numpy.nanmedian(a, axis=axis)
a_cpu = dpnp.array(a, device="cpu")
%timeit dpnp.nanmedian(a_cpu, axis=axis); a_cpu.sycl_queue.wait();
a_gpu = dpnp.array(a, device="gpu")
%timeit dpnp.nanmedian(a_gpu, axis=axis); …
```
> Improve performance of `dpnp.nanmedian`

- dpnp/__init__.py
Since location of "Library\bin" in the virtual environment is not on the default search path, importing of `dpnp` fails due to unmet dependencies towards oneMKL libraries.
The PR proposes to extend `"PATH"` environment on Windows in the virtual environment with a path to `"Library\bin"` directory.
> Support dpnp in virtual environment on Windows out of the box

- CHANGELOG.md
- dpnp/__init__.py
This PR backports of #2242 from development branch to `maintenance/0.16.x`.
> Backport gh-2242

- .github/workflows/conda-package.yml
- CHANGELOG.md
- dpnp/backend/kernels/dpnp_krnl_common.cpp
This PR backports of #2231, #2236 from development branch to `maintenance/0.16.x`.
> Backport gh-2231 and gh-2236

- dpnp/dpnp_iface_manipulation.py
- dpnp/tests/test_manipulation.py
- dpnp/tests/third_party/cupy/manipulation_tests/test_add_remove.py
The PR extends `dpnp.trim_zeros` implement to align with changes introduced in NumPy 2.2.
It adds support for trimming nd-arrays while preserving the old behavior for 1-d input. The new parameter `axis` can specify a single dimension to be trimmed (reducing all other dimensions to the envelope of absolute values). By default (when `None` is specified), all dimensions are trimmed iteratively.
> Add nd-support to `dpnp.trim_zeros`

- .github/workflows/cron-run-tests.yaml
The PR proposes to require installation of the latest dpnp package during night CI run.
> Install the latest package in nightly run

- doc/reference/logic.rst
- doc/reference/ufunc.rst
- dpnp/dpnp_iface_logic.py
`isnat` function is not planning to be supported by dpnp, because it requires an input array with datetime or timedelta data type.
The PR proposes to clean up the documentation and to remove the links to `isnat` function.
> Remove links to `isnat` function from docs

- dpnp/dpnp_array.py
- dpnp/dpnp_iface_indexing.py
- dpnp/tests/test_ndarray.py
The PR proposes to implement `__array_namespace__` method of dpnp ndarray, which is required to be compliant with python array API.
The method will return dpnp as an array namespace, member functions of which implement data API.
The array namespace is assumed to be stored inside dpctl tensor. So dpnp ndarray constructor is updated to explicitly pass `array_namespace=dpnp` into `dpt.usm_ndarray` call. And also to set the namespace through `_set_namespace(dpnp)` every time dpnp ndarray is created from usm_ndarray.
> Add `__array_namespace__` method

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- .github/workflows/generate_coverage.yaml
The PR proposes to add fixes/improvements into the public CI:
- trigger resetup miniconda step on failure in building docs and coverage workflows
- trigger resetup miniconda & reinstall dpnp steps in case of failure within `test_linux` job of conda package workflow
Note, the PR continues work initiated in #2254 and indented to make public CI more stable.
> Resolve issues in public CI (part #2)

- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
- dpnp/backend/src/dpnp_fptr.hpp
- dpnp/backend/src/dpnp_utils.hpp
The PR proposed to remove unused code from the backend.
Specially it's about removing local constant `striped` which produces compilation warnings.
> Clean up backend code

- .github/workflows/array-api-skips.txt
- .github/workflows/conda-package.yml
The PR adds a GitHub job to `Conda package` workflow with array API conformity.
> Add GitHub job with array API conformity run

- .github/workflows/array-api-skips.txt
- dpnp/dpnp_array.py
- dpnp/tests/test_dlpack.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/third_party/cupy/core_tests/test_dlpack.py
The PR proposes to align `dpnp.ndarray.to_device` method with python array API and to add support of `stream` keyword argument.
The tests coverage is extended to cover new argument. Previously muted array-api test is enabled back.
Note, tests for `dpnp.__dlpack__` are updated due to recent changes done in [dpctl#1969](https://github.com/IntelPython/dpctl/pull/1969).
> Add missing `stream` keyword argument to `dpnp.ndarray.to_device` method

- dpnp/dpnp_array.py
- dpnp/tests/test_ndarray.py
The PR is intended to adopt to dpctl changes implemented in [dpctl#1959](https://github.com/IntelPython/dpctl/pull/1959).
It implements support of `__usm_ndarray__` protocol for `dpnp.ndarray` and returns a property with `dpctl.tensor.usm_ndarray` instance corresponding to the content of the array object. 
This property is intended to speed-up conversion from `dpnp.ndarray` to `dpt.usm_ndarray` in `x=dpt.asarray(dpnp_array_obj)`.
The input object that implements `__usm_ndarray__` is recognized as owner of USM allocation that is managed by a smart pointer, and asynchronous deallocation of `x` need not involve GIL.
> Implement `__usm_ndarray_`_ protocol

- .github/workflows/check-mkl-interfaces.yaml
- .github/workflows/cron-run-tests.yaml
The timeout was set up to 12 minutes in `Conda package` workflow.
That PR proposes to align it across all GitHub workflows where tests are running on Linux.
Sometimes the current timeout of 10 minutes might not be enough (like [here](https://github.com/IntelPython/dpnp/actions/runs/12870503193/job/35883466675?pr=2266) in `Test oneMKL interfaces` workflow) which caused unexpected failure or extra rerunning attempt.
> Align timeouts on running tests in public CI on Linux

- dpnp/dpnp_array.py
- dpnp/tests/helper.py
- dpnp/tests/test_arraycreation.py
- dpnp/tests/test_linalg.py
- dpnp/tests/test_manipulation.py
- dpnp/tests/test_ndarray.py
The PR proposes to follow NEP-13 [recommendations](https://numpy.org/neps/nep-0013-ufunc-overrides.html#behavior-in-combination-with-python-s-binary-operations) on how to interact with `numpy.ndarray` in binary the operations.
It will set `__array_ufunc__ = None` which means that dpnp implements Python binary operations freely and so `numpy.ufuncs` called on this argument will raise `TypeError`:
```python
a = numpy.ones(10)
b = dpnp.ones(10)
a += b
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 1
----> 1 a += b
TypeError: operand 'dpnp_array' does not support ufuncs (__array_ufunc__=None)
```
And an elementwise operation with `numpy.ndarray` will cause an explicit …
> Follow recommendation on the interaction with `numpy.ndarray` in binary ops

- .github/workflows/array-api-skips.txt
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_sorting.py
- dpnp/tests/test_sort.py
The PR proposes to add `descending` keyword argument to sorting functions, including `dpnp.sort`, `dpnp.argsort` and `dpnp.ndarray.sort`, `dpnp.ndarray.argsort` methods.
The keyword is mandated according to python array API. The corresponding muted tests are enabled in python array API compliance scope.
> Add `descending` keyword argument to `dpnp.sort` and `dpnp.argsort`

- dpnp/tests/test_arraycreation.py
- dpnp/tests/test_binary_ufuncs.py
- dpnp/tests/test_fft.py
- dpnp/tests/test_flat.py
- dpnp/tests/test_ndarray.py
- dpnp/tests/test_sycl_queue.py
This PR suggests increasing code coverage by adding missing tests for uncovered lines of code for `python` files
> Increase code coverage for `.py` files

- dpnp/__init__.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_histograms.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_libmath.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_sorting.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_utils/dpnp_utils_common.py
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/random/dpnp_iface_random.py
- dpnp/random/dpnp_random_state.py
- dpnp/tests/third_party/cupy/indexing_tests/test_insert.py
This PR continues #2268  and suggests excluding some lines of code from coverage using `pragma:: no cover` to increase the coverage statistic
> Exclude code from coverage

- dpnp/tests/test_arraycreation.py
- dpnp/tests/test_sort.py
Some of the tests which were updated by latest PRs don't work properly when running on a device without fp64 support.
The PR is intended to resolve that and to implement proper check of the resulting arrays for impacted tests.
> Update recently updated tests to run properly when no fp64

- .github/workflows/array-api-skips.txt
- doc/reference/dtype.rst
- dpnp/dpnp_iface_types.py
- dpnp/tests/test_dtype_routines.py
The PR proposes to implement `dpnp.isdtype` function.
The function is mandated according to python array API. The corresponding muted tests are enabled in python array API compliance scope.
> Add `dpnp.isdtype` implementation

- .github/workflows/conda-package.yml
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
- dpnp/tests/third_party/cupy/core_tests/test_elementwise.py
- dpnp/tests/third_party/cupy/core_tests/test_ndarray_complex_ops.py
- dpnp/tests/third_party/cupy/core_tests/test_ndarray_copy_and_view.py
- dpnp/tests/third_party/cupy/creation_tests/test_ranges.py
- dpnp/tests/third_party/cupy/indexing_tests/test_indexing.py
- dpnp/tests/third_party/cupy/linalg_tests/test_einsum.py
- dpnp/tests/third_party/cupy/linalg_tests/test_product.py
- dpnp/tests/third_party/cupy/logic_tests/test_comparison.py
- dpnp/tests/third_party/cupy/math_tests/test_matmul.py
- dpnp/tests/third_party/cupy/math_tests/test_misc.py
- dpnp/tests/third_party/cupy/math_tests/test_trigonometric.py
- dpnp/tests/third_party/cupy/random_tests/test_permutations.py
- dpnp/tests/third_party/cupy/sorting_tests/test_sort.py
- dpnp/tests/third_party/cupy/testing/_loops.py
In this PR, third party tests are update to pass with newly added integer dtypes (int8, int16, uint8, uint16, uint32, uint64).
This PR is in continuation of https://github.com/IntelPython/dpnp/pull/2233.
> update third party tests for newly added integr dtypes (int8, int16, uint8-uint64)

- dpnp/dpnp_iface_histograms.py
- dpnp/dpnp_utils/dpnp_utils_common.py
- dpnp/tests/test_histogram.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
- dpnp/tests/third_party/cupy/statistics_tests/test_histogram.py
Implementation of `histogram2d` via already existing functionality of `histogramdd`.
`histogram2d` accepts 2 different arrays, while `histogramdd` accepts single two-dimensional array.
In order to avoid double copy (first to single array, second to supported type) `histogram2d` perform type checks before calling to `histogramdd`.
> Histogram2d

- .github/workflows/conda-package.yml
The PR proposes to switch `conda-build` version rom `24.11.2` to `25.1.1`.
Note, `.conda` is the new package format since `conda-build=25.1.0`.
> Bump conda-build version from `24.11.2` to `25.1.1`

- .github/workflows/conda-package.yml
Now it is not required to extract dpnp conda package to run the test scope, because the tests will be installed during the conda package installation and so can be run with `pytest -ra --pyargs dpnp.tests` command.
The PR propose to remove obsolete steps from `Conda package` workflow.
> No need to extract dpnp conda package in GitHub actions

- .github/workflows/build-sphinx.yml
- .github/workflows/conda-package.yml
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_statistics.py
- dpnp/tests/test_nanfunctions.py
- dpnp/tests/test_statistics.py
The PR proposes to add `mean` keyword argument to `dpnp.std`, `dpnp.var`, `dpnp.nanstd`, `dpnp.nanvar` functions and `dpnp.ndarray.std`, `dpnp.ndarray.var` methods.
The keyword was introduced by NumPy 2.0 and intended to improve the performance:
> Often when the standard deviation is needed the mean is also needed; the same holds for the variance and the mean. With the current code the mean is then calculated twice, this can be prevented if the functions calculating the variance or the standard deviation can use a precalculated mean
This PR implements similar improvement in dpnp code.
> Add `mean` keyword to `dpnp.std` and `dpnp.var`

- .github/workflows/array-api-skips.txt
- doc/reference/array_api.rst
- doc/reference/fft.rst
- doc/reference/index.rst
- doc/reference/linalg.rst
- dpnp/__init__.py
- dpnp/dpnp_array_api_info.py
- dpnp/tests/test_array_api_info.py
The PR proposes to implement `dpnp.__array_namespace_info__`, what is a python array API Inspection namespace.
It is required to achieve the compliance with python array API.
The implementation leverages on appropriate namespace exposed by dpctl.tensor.
In addition, this PR makes an `__array_api_version__` attribute available in dpnp. It also borrowed from dpctl.
The PR adds a dedication documentation page describing `Array API standard compatibility`, including reference on new `dpnp.__array_namespace_info__`.
> Implement python array API Inspection namespace

- setup.py
The wheel package misses `requires_dist` entry in package info, but dpnp package has a decency on numpy and dpctl packages.
The PR proposes to declare required dependencies in `setup.py`.
Thus the package info of dpnp wheel package built in public CI will include:
```bash
requires_python: >=3.9,<3.14
requires_dist: ['dpctl>=0.19.0dev0', 'numpy']
```
and for internal CI:
```bash
requires_python: >=3.9,<3.14
requires_dist: ['dpctl>=0.19.0dev0', 'numpy', 'dpcpp-cpp-rt', 'onemkl-sycl-blas', 'onemkl-sycl-dft', 'onemkl-sycl-lapack', 'onemkl-sycl-rng', 'onemkl-sycl-stats', 'onemkl-sycl-vm']
```
Note that this PR also specifies a requirement on supported range of python versions.
> Declaring required dependencies for wheel package

- dpnp/tests/test_mathematical.py
- dpnp/tests/test_ndarray.py
- dpnp/tests/test_utils.py
This PR continues #2268 and #2272 and suggests adding a couple new tests to slightly improve code coverage stats
> Add new tests to improve coverage stats

- conda-recipe/run_test.bat
Wheels tests were failing because some python abrupt failures (or windows access violations) would use an exit code that was both non-zero and non-1.
This should capture everything that isn't an exit code of 0
> debug: errorlevel conditionals

- .github/workflows/build-sphinx.yml
`message-id` was added per #2271 to `mshick/add-pr-comment` steps in GitHub workflows, but one of the places was missing.
The PR proposes to resolve that and to set the expected id, otherwise the affected step couldn't find the PR comment to update it (since `message-id: add-pr-comment` which it built by default differs).
> Add missing `message-id` to step which modifies PR comment

- dpnp/backend/extensions/ufunc/CMakeLists.txt
- dpnp/backend/extensions/ufunc/elementwise_functions/nan_to_num.cpp
- dpnp/backend/extensions/ufunc/elementwise_functions/nan_to_num.hpp
- dpnp/backend/kernels/elementwise_functions/nan_to_num.hpp
- dpnp/dpnp_iface_mathematical.py
- dpnp/tests/test_mathematical.py
This PR adds a dedicated kernel for `dnp.nan_to_num` to improve its performance. This reduces the number of kernel calls to at most one in all cases.
A kernel for both strided and contiguous inputs have been added, to avoid additional allocation of device memory for trivial strides when input is fully C- or F-contiguous.
For example of performance gains, using Max GPU
master:
```python
In [1]: import dpnp as dnp
In [2]: import numpy as np
In [3]: x_np = np.random.randn(10**9)
In [4]: x_np[np.random.choice(x_np.size, 200, replace=False)] = np.nan
In [5]: x = dnp.asarray(x_np)
In [6]: q = x.sycl_queue
In [7]: %time r = dnp.nan_to_num(x); q.wait()
CPU times: user 394 ms, sys: 43.8 ms, total: 438 ms
Wall time: 304 ms
In [8]: %time r = dnp.nan_to_num(x); q.wait()
CPU times: user 333 ms, sys: …
```
> Improve performance of `dnp.nan_to_num`

- dpnp/tests/test_usm_type.py
`dpnp.correlate` with input arrays of different USM types produces sporadic crashes on Windows in internal CI.
The PR proposes to temporary mute them until the issue is resolved.
> Temporary mute a test for `dpnp.correlate`

- .github/workflows/array-api-skips.txt
- .github/workflows/check-mkl-interfaces.yaml
- .github/workflows/conda-package.yml
- .github/workflows/cron-run-tests.yaml
- dpnp/backend/extensions/blas/blas_py.cpp
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- dpnp/tests/test_product.py
resolves #2270 
OneMath (OneMKL) routines (`gemm`, `gemv`, `gemm_batch`) for matrix multiplication only support floating point data types. If inputs are integer, to use OneMath we need to upcasting them to floating point dtypes, perform the calculation and then cast back the result to integer dtypes which is unsafe and we may loose some information for large integers.
In this PR, the logic for `dpnp.matmul` is updated to use `dpctl.tensor.matmul` when result has a integer dtypes.
**Performance Analysis**
```bash
$ sycl-ls
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Data Center GPU Max 1100 12.60.7 [1.6.31294+9]
[opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8480+ OpenCL 3.0 (Build 0) [2025.19.1.0.16_160000] …
```
> Use `dpctl.tensor.matmul` in the backend of `dpnp.matmul` when inputs are integer

- .github/workflows/array-api-skips.txt
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_statistics.py
- dpnp/tests/test_nanfunctions.py
- dpnp/tests/test_statistics.py
- pyproject.toml
The PR proposes to add `correction` keyword argument to statistics functions, assuming `dpnp.std`, `dpnp.var`, `dpnp.nanstd`, `dpnp.nanvar` functions and `dpnp.ndarray.std`, `dpnp.ndarray.var` methods.
The keyword is mandated according to python array API. The corresponding muted tests are enabled in python array API compliance scope.
Also this PR adds improvements to the docstrings of functions from statistics interface.
> Add `correction` keyword argument to `dpnp.std` and `dpnp.var`

- dpnp/dpnp_iface_searching.py
The PR proposes to clarify documentation of `dpnp.searchsorted` and to add an example with `sorter` keyword.
> Add an example for `sorter` keyword in `dpnp.searchsorted`

- .github/workflows/conda-package.yml
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- dpnp/tests/test_indexing.py
- dpnp/tests/test_linalg.py
- dpnp/tests/test_product.py
- dpnp/tests/test_statistics.py
In this PR, the GitHub workflow is update to run the test suit with all integer dtypes when the lates python is used. In addition, newly added tests are updated to pass with all integer dtypes.
> update puclic CI workflow for all integer dtypes

- dpnp/dpnp_iface_mathematical.py
The PR updates docstrings for mathematical functions to have a blank line prior `Default` value.
Also it adds some improvements in the parameters description.
> Update docstrings for mathematical functions

- dpnp/dpnp_iface_manipulation.py
The PR updates docstrings for manipulation functions to have a blank line prior `Default` value.
Also it adds some improvements in the parameters description.
> Update docstrings in manipulation functions

- .github/workflows/array-api-skips.txt
- doc/conf.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_statistics.py
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/tests/test_linalg.py
The PR proposes to return namedtuple for linalg functions: `qr`, `eig`, `eigh`, `svd` and `slogdet`.
The namedtuple as a return type there is mandated to be compliant with python array API.
The tests are updated to cover namedtyple as a return type of affected function.
Also this PR requires to patch how napoleon extension from sphinx handles docstring description of namedtuple. The handling was align with NumPy approach.
> Return named tuple for linalg functions per python array API

- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/linalg/dpnp_iface_linalg.py
The PR proposes to implement documentation improvements, including:
- correct example in `dpnp.select`
- updates docstrings for indexing functions to have a blank line prior `Default` value
- align description of `dtype` keyword across all functions
Note, updates in other files with adding blank line prior `Default` will be covered separately.
> Update docstrings in indexing functions 

- doc/reference/ndarray.rst
- dpnp/dpnp_array.py
`numpy.ndarray.tostring` method was deprecated since `1.19` and is going to be removed in `2.3.0` release.
This PR proposes to remove mentioning of `tostring` method in a list of rendered documentation and as TODO method for implementation in `dpnp.ndarray`.
> Remove mentioning of `tostring` method

- dpnp/tests/third_party/cupy/core_tests/test_include.py
- dpnp/tests/third_party/cupy/core_tests/test_raw.py
- dpnp/tests/third_party/cupy/fft_tests/test_fft.py
- dpnp/tests/third_party/cupy/lib_tests/test_polynomial.py
- dpnp/tests/third_party/cupy/manipulation_tests/test_add_remove.py
- dpnp/tests/third_party/cupy/manipulation_tests/test_basic.py
- dpnp/tests/third_party/cupy/math_tests/test_special.py
- dpnp/tests/third_party/cupy/random_tests/test_generator.py
- dpnp/tests/third_party/cupy/sorting_tests/test_search.py
- dpnp/tests/third_party/cupy/statistics_tests/test_histogram.py
- dpnp/tests/third_party/cupy/statistics_tests/test_order.py
The PR proposes to align third party tests with the latest content.
> Update third party tests with the latest changes

- dpnp/dpnp_iface_histograms.py
- dpnp/tests/helper.py
- dpnp/tests/test_histogram.py
`minlength=None` was deprecated for `numpy.bincount` since numpy `1.14` and numpy is going to raise `TypeError` exception in `2.3.0` release.
The PR propose to update implementation of `dpnp.bincount` and to disallow `minlength=None` in the same way as it will be implemented in NumPy 2.3.0.
Additionally there is explicit type check of input arrays added through `dpnp.check_supported_arrays_type` calls at validation step.
> Disallow `minlength=None` in `dpnp.bincount`

- .github/workflows/check-mkl-interfaces.yaml
- .github/workflows/conda-package.yml
- .github/workflows/cron-run-tests.yaml
- dpnp/tests/third_party/cupy/manipulation_tests/test_basic.py
There is currently no way to install dpnp with any numpy version > 2.0, because
- there is no such version available on `https://software.repos.intel.com/python/conda/` channel
- numpy from `conda-forge` channel depends on BLAS libraries which has a runtime dependency `mkl < 2025.0` (since BLAS packages with build number 29)
There is draft PR ([gh-128](https://github.com/conda-forge/blas-feedstock/pull/128)) to build BLAS with MKL version 2025.0, but it is blocked due to MKL issue ([gh-83](https://github.com/conda-forge/intel_repack-feedstock/issues/83)).
Meanwhile there was conda-forge patch ([gh-959](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/959)) merged recently to add `mkl < 2025.0` constraint to already published BLAS packaged on `conda-forge` with …
> Disable GitHub workflows to be run with python 3.13

- dpnp/tests/test_manipulation.py
- dpnp/tests/test_mathematical.py
- dpnp/tests/test_strides.py
The PR proposes to resolve faults in dpnp tests when running towards numpy 2.0.
The affected tests assume numpy fixes released in 2.1 version, so the tests logic has to be updated to align with expected numpy behavior depending on the version used.
> Resolve failures in tests while running with numpy 2.0

- .github/workflows/conda-package.yml
The PR update GitHub workflow with `Conda package` to resolve typos in `Clean up anaconda packages` job there.
There was empty string passed as a name of env file for miniconda resulting to incomplete environment created.
> Resolve typos in the job for Clean up anaconda packages

- dpnp/tests/test_binary_ufuncs.py
- dpnp/tests/test_mathematical.py
- dpnp/tests/test_umath.py
The PR is extending changes proposed in #2329 and suggests to improve `test_invalid_out` test reused in many places for validating various functions.
> Add improvements to the tests

- CHANGELOG.md
The PR populates `CHANGELOG.md` for ongoing `0.17.0` release.
> Populate changelog for `0.17.0` release

- dpnp/backend/extensions/statistics/sliding_window1d.hpp
- dpnp/tests/test_usm_type.py
Temporary workaround for memory corruption inside correlate kernel.
The root cause is still unknown, but the workaround seems to solve crashes
> Fixing memory corruption

- conda-recipe/meta.yaml
The PR proposes to pin to `dpctl=0.19.0` version in scope of `2025.1` release preparation.
> Pin `dpctl` version for 2025.1 release

- CHANGELOG.md
- CMakeLists.txt
The PR populates changelog with `0.17.0` content and initiates `0.18` development.
> Start dpnp 0.18 development

- CHANGELOG.md
The PR proposes to include changes for `0.16.2` and `0.16.3` releases into the `CHANGELOG.md`.
> Extend changelog with 0.16.2 and 0.16.3 releases

- .github/pull_request_template.md
The PR proposes to extend the PR chore list with changelog and documentation notes.
> Add changelog and documentation to PR chore list

- dpnp/dpnp_iface_nanfunctions.py
This PR proposes the use of `nan_to_num` over `_replace_nan` in `nansum`, `nanprod`, `nancumsum`, and `nancumprod` using new internal function `_replace_nan_no_mask`.
> Reuse `dpnp.nan_to_num` in `dpnp.nansum` and `dpnp.nanprod`

- dpnp/dpnp_iface_bitwise.py
The PR updates docstrings for bitwise functions to have a blank line prior `Default` value.
> Update docstrings for bitwise functions

- .github/workflows/conda-package.yml
- dpnp/tests/conftest.py
In this PR, an issue in `conda-package.yml` file is fixed to properly run tests with all integer dtypes on windows when `DPNP_TEST_ALL_INT_TYPES=1`.
> Fix an issue in `conda-package.yml`

- CHANGELOG.md
- dpnp/backend/extensions/statistics/bincount.cpp
- dpnp/backend/extensions/statistics/bincount.hpp
- dpnp/backend/extensions/statistics/histogram.cpp
- dpnp/dpnp_iface_histograms.py
- dpnp/tests/test_histogram.py
- dpnp/tests/third_party/cupy/statistics_tests/test_histogram.py
Previously NumPy prohibits `uint64` dtype of input array in `numpy.bincount`. But that is going to be changed since `2.2.4` release (fixed in numpy#28355 and backported to 2.2.x branch in numpy#28420).
This PR proposes to align with upcoming changes and to allow `uint64` dtype of input array in `dpnp.bincount`.
Additionally, it extends the docstring of histogram-like functions to clearly notify with a warning about possible synchronization impact.
> Add support of `uint64` dtype in `dpnp.bincount`

- dpnp/backend/extensions/lapack/gesv.cpp
- dpnp/backend/extensions/lapack/getrf.cpp
This PR suggests adding a temporary workaround to a problem in oneMath [#642 ](https://github.com/uxlfoundation/oneMath/issues/642) where exceptions are no longer thrown in `lapack` namespace for `getrf` function as expected.
In oneMath develop branch `oneapi::mkl::lapack::computation_error` is not thrown. 
Instead, `oneapi::mkl::computation_error` from `mkl` namespace is used so existing catch block `mkl_lapack::exception` does not handle singular matrix errors.
A workaround has been added to explicitly catch `oneapi::mkl::computation_error` and update `dev_info`  ensuring that singular matrices are handled correctly.
> Add w/a for oneMath to fix test oneMKL interfaces action

- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_bitwise.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_logic.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_nanfunctions.py
- dpnp/dpnp_iface_searching.py
- dpnp/dpnp_iface_statistics.py
- dpnp/dpnp_iface_trigonometric.py
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- dpnp/linalg/dpnp_iface_linalg.py
The PR updates docstrings for logic functions to have a blank line prior `Default` value.
Additionally it proposes to align description of `order`, `out` `keepdims` keywords.
> Update docstrings for logic functions

- doc/reference/math.rst
The PR proposes to remove duplicating reference on `dpnp.bitwise_count` from a list of miscellaneous mathematical functions.
It seems better to have `dpnp.bitwise_count` listed under bit-wise operations only.
> Remove `dpnp.bitwise_count` from a list of miscellaneous mathematical functions

- dpnp/backend/extensions/lapack/gesvd.cpp
- dpnp/backend/extensions/lapack/gesvd_batch.cpp
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/dpnp_iface_histograms.py
- dpnp/dpnp_iface_indexing.py
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_statistics.py
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/random/dpnp_iface_random.py
- dpnp/tests/test_arraycreation.py
The PR updates docstrings for linalg functions to have a blank line prior `Default` value.
Additionally, it adds a space after comma to align with used code style.
> Update docstrings for linalg functions

- dpnp/backend/extensions/fft/CMakeLists.txt
- dpnp/backend/extensions/fft/in_place.hpp
- dpnp/backend/extensions/fft/in_place.tpp
- dpnp/backend/extensions/fft/out_of_place.hpp
- dpnp/backend/extensions/fft/out_of_place.tpp
In this PR, explicit instantiation of `compute_fft_in_place` and `compute_fft_out_of_place` functions in the backend is replaced with including a template definition.
> get rid of explicit instantiation in fft backend

- dpnp/dpnp_iface_sorting.py
- dpnp/dpnp_iface_statistics.py
The PR updates docstrings for sorting functions to have a blank line prior `Default` value.
> Update docstrings for sorting functions

- CHANGELOG.md
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/tests/test_linalg.py
resolves #2319
The vector norms `ord={None, 1, 2, inf}` and the matrix norms `ord={None, 1, 2, inf, "fro", "nuc"}` now consistently return zero for empty arrays, which are arrays with at least one axis of size zero. This change affects `dpnp.linalg.norm`, `dpnp.linalg.vector_norm`, and `dpnp.linalg.matrix_norm`. Previously, dpnp would either raise errors or return zero depending on the parameters provided
> fix_issue-2319

- CHANGELOG.md
- dpnp/backend/kernels/dpnp_krnl_elemwise.cpp
The PR proposes to resolve a sporadic failure due to mismatch with the expected data in `test_strides.py::test_erf`.
The issue looks caused by missing dependency from strided erf kernel on a copy event (produced by copy kernel to transfer the strides of input array from host to device memory).
> Add a missing event dependency for the strided kernel of erf

- .github/workflows/build-sphinx.yml
- .github/workflows/check-mkl-interfaces.yaml
- .github/workflows/generate_coverage.yaml
- environments/build_with_oneapi.yml
- environments/dpctl_pkg.yml
This PR resolves issue with `coverage` and `docs` GitHub workflows observing since 2025.1 release is published.
The reason of the proposed changes is that it isn't possible to install dpctl there as a conda package when the environment is created through installing of Intel OneAPI packages because the dpctl conda package has a runtime dependency on DPC++ RT one. Whereas the DPC++ RT package has been already installed by the apt command above and its version has been matched with the DPC++ compiler.
In case where we install the DPC++ compiler with the apt (including DPC++ RT) and install the DPC++ RT conda package while resolving dependencies, this can lead to a versioning error, i.e. compatibility issue as the DPC++ compiler only guarantees backwards compatibility, not forward …
> Install dpctl via pip manager in coverage and docs workflows

- CHANGELOG.md
- dpnp/fft/dpnp_iface_fft.py
- dpnp/fft/dpnp_utils_fft.py
- dpnp/tests/test_fft.py
The PR proposes to align `dpnp.fft.fftfreq` and `dpnp.fft.rfftfreq` functions with [2024.12](https://data-apis.org/array-api/2024.12/extensions/generated/array_api.fft.fftfreq.html) revision of Python array API spec where `dtype` keyword was specified for the functions.
Additionally, implementation of `dpnp.fft.fftfreq` was reworked a bit to consume less memory and to avoid allocating temporary arrays.
Also docstrings of FFT functions were improved to add blank lines prior defaults values.
> Add `dtype` keyword argument to `dpnp.fft.fftfreq` and `dpnp.fft.rfftfreq`

- dpnp/backend/extensions/blas/blas_py.cpp
- dpnp/backend/extensions/blas/dot_common.hpp
- dpnp/backend/extensions/window/common.hpp
In this PR, unnecessary template in the backend of dot functions is removed.
> get rid of unnecessary template in the backend of dot functions

- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_types.py
- dpnp/tests/third_party/cupy/test_type_routines.py
This PR suggests adding an implementation of `dpnp.common_type()` and updates cupy `TestCommonType` tests
> Implement `dpnp.common_type()`

- .github/workflows/check-mkl-interfaces.yaml
- .github/workflows/conda-package.yml
- dpnp/tests/test_statistics.py
The PR bumps max versions of DPC++ compiler and Intel MKL used during build of dpnp conda packages.
The workflow `Test oneMKL interfaces` is updated to have a proper channels priority in test conda environments.
> Update GH workflows to work with 2025.1 release

- CHANGELOG.md
- doc/quick_start_guide.rst
As reported in #2388 the instruction was not complete and caused compilation error.
The PR proposes to add `dppy/label/dev` channel in `conda create` command to mitigate the issue.
Also the list of conda packages was extended to install `intel-gpu-ocl-icd-system` conda package, because FFT function will fail otherwise.
> Update build and install instructions in Quick start guide

- dpnp/fft/dpnp_iface_fft.py
- dpnp/fft/dpnp_utils_fft.py
- dpnp/tests/test_fft.py
- dpnp/tests/test_umath.py
In this PR, a utility function in FFT module is updated to remove duplication.
In addition a new test is added to make coverage for FFT module 100%.
> update a utility function in FFT module

- .pre-commit-config.yaml
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/tests/third_party/cupy/math_tests/test_sumprod.py
- dpnp/tests/third_party/intel/zero-copy-test1.py
- dpnp/to_numba/dpnp_iface_to_numba.py
- pyproject.toml
In this PR, pre-commit hook is extended with pretty-format-toml. In addition, the version of other packages in pre-commit hook is updated.
> Extend pre-commit hooks with pretty-format-toml

- dpnp/tests/third_party/cupy/lib_tests/test_shape_base.py
This PR add third party tests for `dpnp.apply_over_axes`.
> Add third party tests for `dpnp.apply_over_axes`

- CHANGELOG.md
- dpnp/backend/extensions/window/CMakeLists.txt
- dpnp/backend/extensions/window/common.hpp
- dpnp/backend/extensions/window/kaiser.cpp
- dpnp/backend/extensions/window/kaiser.hpp
- dpnp/backend/extensions/window/window_py.cpp
- dpnp/dpnp_iface_window.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
- dpnp/tests/test_window.py
- dpnp/tests/third_party/cupy/math_tests/test_window.py
In this PR, `dpnp.kaiser` is implemented.
> implement `dpnp.kaiser`

- dpnp/backend/extensions/common/ext/common.hpp
- dpnp/backend/extensions/common/ext/details/common_internal.hpp
- dpnp/backend/extensions/common/ext/details/validation_utils_internal.hpp
- dpnp/backend/extensions/common/ext/dispatch_table.hpp
- dpnp/backend/extensions/common/ext/validation_utils.hpp
- dpnp/backend/extensions/statistics/CMakeLists.txt
- dpnp/backend/extensions/statistics/bincount.cpp
- dpnp/backend/extensions/statistics/bincount.hpp
- dpnp/backend/extensions/statistics/histogram.cpp
- dpnp/backend/extensions/statistics/histogram.hpp
- dpnp/backend/extensions/statistics/histogram_common.cpp
- dpnp/backend/extensions/statistics/histogram_common.hpp
- dpnp/backend/extensions/statistics/histogramdd.cpp
- dpnp/backend/extensions/statistics/histogramdd.hpp
- dpnp/backend/extensions/statistics/sliding_dot_product1d.cpp
- dpnp/backend/extensions/statistics/sliding_dot_product1d.hpp
- dpnp/backend/extensions/statistics/sliding_window1d.cpp
- dpnp/backend/extensions/statistics/sliding_window1d.hpp
> Move statistics utils to common place as headers only

- CHANGELOG.md
- dpnp/dpnp_iface_manipulation.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_statistics.py
- dpnp/tests/helper.py
- dpnp/tests/test_mathematical.py
- dpnp/tests/test_statistics.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
- dpnp/tests/third_party/cupy/math_tests/test_misc.py
Add implementation of `dpnp.convolve`. Implementation is mostly based on already existing functionality developed for `dpnp.correlate`
Similar to [scipy.signal.convolve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html) `method` keyword is introduced, but unlike `scipy.signal.convolve` `dpnp.convolve` works only with 1-d arrays.
> Implementation of convolve

- dpnp/tests/helper.py
- dpnp/tests/test_binary_ufuncs.py
- dpnp/tests/test_histogram.py
- dpnp/tests/test_linalg.py
- dpnp/tests/test_logic.py
- dpnp/tests/test_manipulation.py
- dpnp/tests/test_mathematical.py
- dpnp/tests/test_strides.py
- dpnp/tests/test_sum.py
A new helper function is defined for tests, to get integer and float dtypes.
> define a new helper function for tests called `get_integer_float_dtypes`

- dpnp/tests/test_mathematical.py
The PR proposes to partly merge changes from #2403 to unblock coverage GitHub action.
The workaround for dpctl-2030 was kept only for testing with GPU device (the use case from internal CI, where the changes from dpctl-2030 is not available).
> Disable w/a for dpctl-2030 on CPU device

- dpnp/tests/third_party/cupy/core_tests/test_ndarray_adv_indexing.py
This PR enables tests in advanced indexing scope since [dpctl-1913](https://github.com/IntelPython/dpctl/issues/1913) has been resolved.
> Enabled tests in advanced indexing scope

- .github/workflows/conda-package.yml
- environments/build_conda_pkg.yml
This PR pins `libxml2` version to `2.13.7` due to libs dependency issue with `2.14.0` version as reported on [#146](https://github.com/conda-forge/libxml2-feedstock/issues/146).
Without that change the conda package can not be build through GitHub action, since `conda-build` raises error:
```python
Traceback (most recent call last):
File "C:\Users\runneradmin\miniconda3\envs\build\Scripts\conda-build-script.py", line 6, in <module>
from conda_build.cli.main_build import execute
File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\conda_build\cli\main_build.py", line 19, in <module>
from .. import api, build, source, utils
File "C:\Users\runneradmin\miniconda3\envs\build\Lib\site-packages\conda_build\api.py", line [24](https://github.com/IntelPython/dpnp/actions/runs/142670190 …
```
> Pin `libxml2` version to 2.13.7

- environments/build_conda_pkg.yml
This PR bumps `conda-build` version from 25.3.1 to 25.3.2.
> Bump `conda-build` version

- environments/build_conda_pkg.yml
This PR removes explicit pinning on libxml2 version `2.13.7` added in scope of #2409.
The issue has been the new build published on conda-forge.
> Remove w/a with pinning `libxml2` version

- CHANGELOG.md
- dpnp/dpnp_iface_linearalgebra.py
- dpnp/dpnp_utils/dpnp_utils_einsum.py
- dpnp/tests/test_linalg.py
Add support for `order=None` for `dpnp.einsum`
> add support for `order=None` in `dpnp.einsum`

- .github/workflows/build-sphinx.yml
- .github/workflows/generate_coverage.yaml
- environments/dpctl_pkg.txt
The PR proposes to use a requirement file while installing dpctl wheel package through GitHub actions in `Build docs` and `Coverage` workflows.
This will allow to specified the required dpctl version in one requirement file.
> Use a requirement file to install dpctl wheel package

- CHANGELOG.md
The PR proposes to backport changes from #2345 and #2348.
> Backport review comments for changelog

- conda-recipe/meta.yaml
- setup.py
This PR bumps min required dpctl version to `0.20.0dev0`.
> Bump required dpctl version

- .github/workflows/array-api-skips.txt
`dpctl.tensor` now conforms to array API 2024.12 indexing, so tests can be run
> Enable array API advanced indexing tests

- CHANGELOG.md
- doc/reference/array_api.rst
- dpnp/tests/test_ndarray.py
There was `__array_api_version__` set to `2024.12` in [dpctl#2047](https://github.com/IntelPython/dpctl/pull/2047).
This PR updates tests and documentation to state support with the newer spec version.
> Update array API version supported to 2024.12

- CHANGELOG.md
- dpnp/tests/config.py
The PR closes #2324. It is proposes to cast test env variables with dtype scope to boolean value which can handle empty string as a False value.
> Cast test env variables with dtype scope to boolean value

- CHANGELOG.md
- dpnp/dpnp_iface_linearalgebra.py
`einsum_call` is a [hidden kwarg](https://github.com/numpy/numpy/blob/main/numpy/_core/einsumfunc.pyi#L174). In NumPy, it has been used internally inside `einsum` but it is not needed in dpnp so removing it from the signature.
> remove `einsum_call` kwargs from `dpnp.einsum_path` signature

- .github/workflows/array-api-skips.txt
There were few fixes implemented in `array-api-tests` around clip tests.
The PR proposes to enable `test_clip` test from `array-api-tests` scope.
> Enable clip test from `array-api-tests` scope

- dpnp/tests/third_party/cupy/linalg_tests/test_einsum.py
- dpnp/tests/third_party/cupy/testing/_array.py
- dpnp/tests/third_party/cupy/testing/_loops.py
This PR updates test f/w to align with the recent changes and to add a `strict` keyword to third party testing.
> Add a `strict` keyword to testing f/w

- .github/workflows/conda-package.yml
- .github/workflows/cron-run-tests.yaml
The location of `cl.cfg` file created by installing `intel-opencl-rt` conda package was changed few releases back from `%CONDA_PREFIX%\Library\lib\cl.cfg` to `%CONDA_PREFIX%\Library\bin\cl.cfg`.
The file was still created at `Library\lib\cl.cfg` by `intel-opencl-rt-post-link.bat` script but with empty content.
The PR updates public CI to rely on correct path to `cl.cfg` configuration file.
The issue with `intel-opencl-rt-post-link.bat` script has to be updated by separate change in the compiler repo.
> Correct a path to `cl.cfg` file

- dpnp/tests/test_ndarray.py
The behavior of `repr` was modified in https://github.com/IntelPython/dpctl/pull/2067.
Tests in `dpnp` should be modified to align with this new behavior.
> fix failed test in `test_ndarray.py`

- dpnp/tests/test_ndarray.py
- environments/build_with_oneapi.yml
Using `setuptools` version from `80.0.0` has been causing a failure in the GitHub workflow where
`python scripts/build_locally.py` is used to build dpnp.
This PR pins `setuptools` to `79.0.1` for now while investigating.
> Pin `setuptools` to `79.0.1` in public CI

- CHANGELOG.md
- dpnp/tests/test_array_api_info.py
[dpctl-2071](https://github.com/IntelPython/dpctl/pull/2071) is going to change `"max dimensions"` to `None` in array API capabilities.
This PR updates a test to align with that change.
> Update test to align with dpctl in array API capabilities

- CHANGELOG.md
- dpnp/backend/extensions/window/kaiser.cpp
- dpnp/backend/kernels/elementwise_functions/i0.hpp
This PR suggests updating `dpnp.i0()` and `dpnp.kaiser()`  to avoid including `<sycl/ext/intel/math.hpp>` due to its incompatibility with non-Intel backend (CUDA, AMD).
Instead of using `sycl::ext::intel::math::cyl_bessel_i0`, `dpnp::kernels::i0::impl::cyl_bessel_i0`  is now used when building on non-Intel targets.
Including `<sycl/ext/intel/math.hpp>` with `-fsycl-targets=nvptx64-nvidia-cuda`  or `-fsycl-targets=amdgcn-amd-amdhsa `causes compilation errors due to type conflicts
```
In file included from dpnp/dpnp/backend/extensions/window/kaiser.cpp:44:
In file included from /opt/intel/oneapi/compiler/2025.1/bin/compiler/../../include/sycl/ext/intel/math.hpp:40:
/opt/intel/oneapi/compiler/2025.1/bin/compiler/../../include/sycl/ext/intel/math/imf_fp_conversions.hpp:108:14: error: …
```
> Avoid using `sycl/ext/intel/math.hpp` on non-Intel devices

- .pre-commit-config.yaml
- dpnp/random/dpnp_iface_random.py
The PR bumps versions used in the `pre-commit` config.
> Update `pre-commit` config to the latest versions

- conda-recipe/meta.yaml
- environments/build_with_oneapi.yml
This PR pins `cython <3.1` to w/a build failure observing with `3.1.0` in public CI.
The latest stable Cython version was `3.0.12`.
> Pin cython to unblock public CI

- CHANGELOG.md
- dpnp/backend/extensions/window/kaiser.cpp
- dpnp/backend/kernels/elementwise_functions/i0.hpp
This PR proposes to make `cyl_bessel_i0` function fully exposed by `dpnp/backend/kernels/elementwise_functions/i0.hpp` header to hide all logic validating if `sycl::ext::intel::math::cyl_bessel_i0` function from `sycl/ext/intel/math.hpp` header can be used or native implementation is required.
> Move all logic with `cyl_bessel_i0` support in `i0.hpp`

- conda-recipe/meta.yaml
- dpnp/dpnp_algo/dpnp_arraycreation.py
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- environments/build_with_oneapi.yml
This PR reverts cython pinning added in #2441 which was added to unblock CI due to compilation error:
```bash
$SRC_DIR/_skbuild/linux-x86_64-3.9/cmake-build/dpnp/dpnp_utils/dpnp_algo_utils.cxx:28898:36: error: use of undeclared identifier '__pyx_convert__to_py___pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc'; did you mean '__pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc'?
28898 |   __Pyx_TraceReturnCValue(__pyx_r, __pyx_convert__to_py___pyx_ctuple_4f2d56__4dpnp_9dpnp_algo_9dpnp_algo_enum__space_DPNPFu__etc, 21, 0, __PYX_ERR(0, 466, __pyx_L1_error));
|                                    ^
$SRC_DIR/_skbuild/linux-x86_64-3.9/cmake-build/dpnp/dpnp_utils/dpnp_algo_utils.cxx:2104:89: note: …
```
> Remove cython pinning to `< 3.1`

- CHANGELOG.md
- dpnp/backend/extensions/vm/CMakeLists.txt
- dpnp/backend/extensions/vm/arg.cpp
- dpnp/backend/extensions/vm/arg.hpp
- dpnp/backend/extensions/vm/copysign.cpp
- dpnp/backend/extensions/vm/copysign.hpp
- dpnp/backend/extensions/vm/i0.cpp
- dpnp/backend/extensions/vm/i0.hpp
- dpnp/backend/extensions/vm/inv.cpp
- dpnp/backend/extensions/vm/inv.hpp
- dpnp/backend/extensions/vm/vm_py.cpp
- dpnp/dpnp_algo/dpnp_elementwise_common.py
- dpnp/dpnp_iface_mathematical.py
- dpnp/dpnp_iface_trigonometric.py
The PR add missing MKL functions from VM namespace to the dedicated extension:
- `arg()` to be used by `dpnp.angle`
- `copysign()`
- `i0()`
- `inv()` to be used by `dpnp.reciprocal`
Note, `remainder()` is available as MKL VM function but follows C's module operator and so can't be used to implement `dpnp.remainder` which has to follow Python's module operator according to Python array API [specification](https://data-apis.org/array-api/2024.12/API_specification/generated/array_api.remainder.html):
> This function is equivalent to the Python modulus operator x1_i % x2_i.
Note, `sycl::half` is not intended to be used for VM functions due to accuracy reason and values mismatch with numpy in corner cases.
> Add missing MKL function from VM namespace

- README.md
- doc/quick_start_guide.rst
ref https://github.com/IntelPython/dpctl/pull/2080
> DOC: Clarify details about conda installs

- CHANGELOG.md
- CMakeLists.txt
There was a new `oneMath` release [v0.7](https://github.com/uxlfoundation/oneMath/releases/tag/v0.7) published.
Thus the PR updates `oneMath` version used by default dpnp build with enabled oneMKL interfaces.
Also, the name of fetched oneMath library changed from legacy `onemkl_interfaces_library` to `onemath_library` to reflact the actual library naming.
> Bump `oneMath` version to `v0.7`

- CHANGELOG.md
- dpnp/dpnp_iface_indexing.py
- dpnp/tests/test_indexing.py
set a default value of `-1` for axis parameter in `dpnp.take_along_axis`
> set a default value for axis parameter in `dpnp.take_along_axis`

- CHANGELOG.md
- doc/quick_start_guide.rst
This PR updates the list of required python versions documented in `Quick Start Guide`.
> Update required python versions in `Quick Start Guide`

- CHANGELOG.md
- dpnp/fft/dpnp_iface_fft.py
- dpnp/fft/dpnp_utils_fft.py
- dpnp/tests/test_fft.py
- dpnp/tests/third_party/cupy/fft_tests/test_fft.py
In this PR, input array is made Hermitian before calling complex-to-real FFT.
Input array should be Hermitian before calling complex-to-real FFT otherwise the behavior is undefined. Although it is user responsibility to validate this feature, [NumPy](https://github.com/numpy/numpy/blob/maintenance/2.2.x/numpy/fft/_pocketfft_umath.cpp#L265) and [CuPy](https://github.com/cupy/cupy/blob/v13.4.1/cupy/fft/_fft.py#L109) internally make the input array Hermitian. So, it is done in dpnp for consistency.
> make array Hermitian before calling complex-to-real FFT

- dpnp/tests/third_party/cupy/creation_tests/test_ranges.py
The PR resolves overflow issue observing in `test_linspace_mixed_start_stop2` test when running with `DPNP_TEST_ALL_INT_TYPES=1` on ARL-S machine.
> Avoid overflow in linspace test

- .pre-commit-config.yaml
The PR updates `gitleaks` version up to `v8.26.0` in pre-commit config.
> Bump `gitleaks` version in pre-commit config

- dpnp/tests/helper.py
- dpnp/tests/test_mathematical.py
The stock NumPy returns incorrect result for `numpy.spacing(-0.0)`, while Intel NumPy returns the expected one (the same as dpnp also).
It might be the case when dpnp test is running with the stock NumPy. Thus the PR add a conditional check to update expected result in `TestSpacing::test_zeros` in case when non-Intel NumPy is used.
Previously the same logic was based on NumPy version, assuming Intel NumPy has always `version < "2.0.0"`, but it is not the case anymore.
> Apply w/a for expected result in spacing test only on non-Intel NumPy

- dpnp/backend/extensions/lapack/getrf_batch.cpp
- dpnp/backend/extensions/lapack/getri_batch.cpp
- dpnp/tests/test_linalg.py
The PR mutes the `tests/test_linalg.py::TestCond::test_nan` tests temporary on Windows to unblock the internal CI.
> Temporary disable failing tests for NaN input passed to `dpnp.linalg.cond`

- CHANGELOG.md
- pyproject.toml
The PR updates configuration of `black` tool to align `target-version` with the list of supported python versions.
> Bump `target-version` in black configuration

- CHANGELOG.md
- dpnp/backend/extensions/lapack/getrf_batch.cpp
- dpnp/backend/extensions/lapack/getri_batch.cpp
- dpnp/tests/helper.py
- dpnp/tests/test_linalg.py
- dpnp/tests/third_party/cupy/linalg_tests/test_norms.py
- dpnp/tests/third_party/cupy/linalg_tests/test_solve.py
This PR suggests improvements to the handling of `oneapi::mkl::lapack::batch_error` in `oneapi::mkl::lapack::getrf_batch` and `oneapi::mkl::lapack::getri_batch`
OneMKL batched functions throw a single `oneapi::mkl::lapack::batch_error` interpreted as computation_error for all failed matrices (ids()). Now set dev_info[...] = 1 for each to determinate singular matrix.
This change allows a consistent raising of `LinAlgError` in `dpnp.linalg.inv()` for both non-batched and batched singular matrices and unskipping tests with singular matrices for `dpnp.linalg.inv()` , `dpnp.linalg.det`, `dpnp.linalg.slogdet`
> Update `mkl_lapack::batch_error` handling in `getrf_batch` / `getri_batch`

- dpnp/tests/test_binary_ufuncs.py
`TestFloorDivideRemainder::test_basic` test generates the same values for both input array.
The PR proposes to change values for divisor input array and to make them different from dividend input array. That should makes test more stable with `float32` data type.
Currently it might fail on PVC with LTS driver for case with `floor_divide` function.
> Makes tests with floor_divide more stable on PVC

- CHANGELOG.md
The PR add a summary for upcoming `0.18.0` release.
> Add release summary to the changelog

- .github/workflows/check-mkl-interfaces.yaml
- .github/workflows/conda-package.yml
- .github/workflows/cron-run-tests.yaml
- conda-recipe/conda_build_config.yaml
- conda-recipe/meta.yaml
The PR is indented to remove a temporary pinning to "windows-2019" and to revert changes from #1833.
Besides Windows 2019 GitHub image is going to be fully unsupported by June 30, 2025.
The impacted workflows are moved to use "windows-2022" GH runners.
It requires updating `conda_build_config.yaml` where the version of the compiler as well as standard libraries have to be specified.
While `{{ stdlib('c') }}` is installing into build environment as an alignment with recipe's meta yaml from conda-forge (see [dpctl#1868](https://github.com/IntelPython/dpctl/pull/1868) as for reference).
> Update Windows version used by GitHub CI

- .github/workflows/conda-package.yml
- environments/build_conda_pkg.yml
- environments/create_conda_channel.yml
The PR updates `conda-build` version to `25.0.0` and `conda-index` vrsion to `0.6.1`.
Also the conda packages are now supporting python 3.13, so removing all w/a or limitation due to that in affected GH actions.
> Bump conda versions

- CHANGELOG.md
- conda-recipe/meta.yaml
- environments/dpctl_pkg.txt
- environments/dpctl_pkg.yml
- pyproject.toml
The PR pins to the lates dpctl release version `0.20.0`.
> Pin to the lates dpctl release

- .pre-commit-config.yaml
- CHANGELOG.md
This PR proposes to adjust the `pre-commit` config to run autoupdate weekly.
> Adjust pre-commit config to autoupdate weekly

- CHANGELOG.md
- CMakeLists.txt
- doc/quick_start_guide.rst
- scripts/build_locally.py
This PR suggests adding `--target-cuda` argument to `scripts/build_locally.py` allowing to enable CUDA support and optionally specify the target architecture (e.g. `sm_80`).
If no architecture is specified, `sm_50` is used by default.
```bash
$ python scripts/build_locally.py --target-cuda
$ python scripts/build_locally.py --target-cuda=<arch>
```
The specified architecture is used to construct a SYCL alias target (e.g. `nvidia_gpu_sm_80`) and passed via `-fsycl-targets` option, following [OneAPI for NVIDIA GPUs](https://developer.codeplay.com/products/oneapi/nvidia/2025.0.0/guides/get-started-guide-nvidia#use-dpc-to-target-nvidia-gpus)
> Add `--target-cuda` argument for selecting CUDA architecture

- CHANGELOG.md
- CMakeLists.txt
This PR suggests validating the format of `HIP_TARGETS` (set via `--target-hip`) to ensure it starts with `gfx` (e.g., `gfx1030`).
It also allows users to explicitly indicate that no AMD target should be used by passing values like `--target-hip=OFF` or `--target-hip=FALSE` matching the default behavior
> Validate `HIP_TARGETS` format and allow negative values

- dpnp/tests/third_party/cupy/math_tests/test_hyperbolic.py
- dpnp/tests/third_party/cupy/math_tests/test_trigonometric.py
The PR updates third party tests for hyperbolic and trigonometric elementwise functions to specify correct tolerance for float16 data type (to set `atol=1e-3`) and to keep `atol=1e-5` for other dtypes.
> Update math tests to specify a proper tolerance

- .github/workflows/conda-package.yml
- CHANGELOG.md
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/tests/test_linalg.py
- dpnp/tests/test_product.py
- dpnp/tests/testing/array.py
- dpnp/tests/third_party/cupy/manipulation_tests/test_add_remove.py
- dpnp/tests/third_party/cupy/math_tests/test_matmul.py
- pyproject.toml
This PR backports of #2477 from development branch to `maintenance/0.18.x`.
> Backport gh-2477

- dpnp/tests/third_party/cupy/math_tests/test_hyperbolic.py
- dpnp/tests/third_party/cupy/math_tests/test_trigonometric.py
This PR backports of #2483 from development branch to `maintenance/0.18.x`.
> Backport gh-2483

- dpnp/tests/test_product.py
- dpnp/tests/third_party/cupy/math_tests/test_matmul.py
The new numpy release `2.3.1` has been published which includes the fix for numpy#29164.
That PR enables the previously muted tests for numpy 2.3.1 in #2477.
> Enabled tests previously muted for numpy 2.3

- dpnp/tests/test_product.py
- dpnp/tests/third_party/cupy/math_tests/test_matmul.py
This PR backports of #2495from development branch to `maintenance/0.18.x`.
> Backport gh-2495

- CHANGELOG.md
This PR adds release summary and included changes.
> Populate changelog for `0.18.1` release

- .github/workflows/conda-package.yml
This PR bump max DPC++ compiler and MKL versions used in build GH workflows.
> Bump DPC++ compiler and MKL versions used in build

- CHANGELOG.md
- dpnp/dpnp_iface_linearalgebra.py
The PR updates maths in summary of `dpnp.matvec` and `dpnp.vecmat` to fix the typo.
> Fix typo in docstring of `matvec` and `vecmat`

- dpnp/tests/test_fft.py
> update fft tests

- CHANGELOG.md
- dpnp/dpnp_iface_mathematical.py
The PR adds `strict` word in the docstring of `xp` keyword in `dpnp.interp` following similar change implemented in NumPy.
> Update docstring of `xp` keyword in `dpnp.interp`

- CHANGELOG.md
- dpnp/dpnp_iface_manipulation.py
- dpnp/tests/test_manipulation.py
This PR resolves an issue when calling `dpnp.resize` with unsigned integer size.
The negation of an unsigned int underflows and creates a large positive repeats, which leads to a runtime error. The PR fixes the used ceil division.
> Avoid negating unsigned integers in `dpnp.resize`

- dpnp/tests/helper.py
- dpnp/tests/test_product.py
The PR proposes to skip tests which are failing in internal CI due to known issue on PTL-H machine.
> Temporary skip tests failing on PTL-H

- CHANGELOG.md
- dpnp/backend/extensions/blas/CMakeLists.txt
- dpnp/backend/extensions/blas/blas_py.cpp
- dpnp/backend/extensions/blas/dot_common.hpp
- dpnp/backend/extensions/blas/gemm.cpp
- dpnp/backend/extensions/blas/gemm_batch.cpp
- dpnp/backend/extensions/blas/gemv.cpp
- dpnp/backend/extensions/blas/syrk.cpp
- dpnp/backend/extensions/blas/syrk.hpp
- dpnp/backend/extensions/blas/types_matrix.hpp
- dpnp/backend/extensions/lapack/evd_batch_common.hpp
- dpnp/backend/extensions/lapack/evd_common.hpp
- dpnp/dpnp_utils/dpnp_utils_linearalgebra.py
- dpnp/tests/test_product.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
In this PR, the `syrk` routines from oneMKL is used to perform a rank-k update which is used for a specialized matrix multiplication where the result is a symmetric matrix. 
```bash
$ sycl-ls
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Data Center GPU Max 1100 12.60.7 [1.6.31294+9]
[opencl:cpu][opencl:0] Intel(R) OpenCL, Intel(R) Xeon(R) Platinum 8480+ OpenCL 3.0 (Build 0) [2025.19.1.0.16_160000]
[opencl:gpu][opencl:1] Intel(R) OpenCL Graphics, Intel(R) Data Center GPU Max 1100 OpenCL 3.0 NEO  [24.39.31294]
```
| size | syrk-GPU           | gemm-GPU           | syrk-CPU            | gemm-CPU           |
|------|--------------------|--------------------|---------------------|--------------------|
| 2048 | 1.37 ms ± 2.81 μs  | 2.02 ms ± 3.69 μs …
> using `syrk` for performing special cases of matrix multiplication

- CHANGELOG.md
- dpnp/dpnp_array.py
- dpnp/dpnp_iface.py
- dpnp/memory/__init__.py
- dpnp/memory/_memory.py
- dpnp/tests/test_dlpack.py
- dpnp/tests/test_memory.py
- dpnp/tests/third_party/cupy/core_tests/test_dlpack.py
- dpnp/tests/third_party/cupy/core_tests/test_ndarray.py
- dpnp/tests/third_party/cupy/creation_tests/test_from_data.py
- dpnp/tests/third_party/cupy/linalg_tests/test_einsum.py
- dpnp/tests/third_party/cupy/manipulation_tests/test_shape.py
- dpnp/tests/third_party/cupy/misc_tests/test_byte_bounds.py
This PR adds implementation of `dpnp.ndarray.data` and `dpnp.ndarray.data.ptr` attributes.
The tests are updated to use the new attributes where applicable.
> Add implementation of `dpnp.ndarray.data` and `dpnp.ndarray.data.ptr` attributes

- CHANGELOG.md
- dpnp/dpnp_iface_manipulation.py
- dpnp/tests/helper.py
- dpnp/tests/test_manipulation.py
The PR fixes `dpnp.unique` with 1d input array and `axis=0`, `equal_nan=True` keywords passed where the produced result is wrong and doesn't collapse the NaNs.
> Fix `dpnp.unique` with axis=0 and 1d input

- CHANGELOG.md
- dpnp/memory/_memory.py
- dpnp/tests/test_memory.py
The PR closes gh-2532.
In the faulty example the buffer was passed with `.data` of dpnp.ndarray. In that case there is no need to cast dpctl's `usm_data` to DPNP memory object.
> Fix `dpnp.ndarray` constructor call with buffer passed as data property

- CHANGELOG.md
- dpnp/dpnp_array.py
- dpnp/tests/test_ndarray.py
The PR implements `__contains__` method which needs to define the `in` operator for a `dpnp.ndarray`.
> Add `dpnp.ndarray.__contains__`

- dpnp/tests/test_sycl_queue.py
The PR removes temporary w/a implemented due to crash on Windows in `test_random` and `test_random_state`.
> Remove temporary workaround in tests where "in_order" SYCL queue was used

- .flake8
- .pre-commit-config.yaml
- CHANGELOG.md
- doc/reference/constants.rst
- doc/reference/ndarray.rst
- doc/reference/routines.rst
- dpnp/dpnp_array.py
- dpnp/dpnp_iface_arraycreation.py
- dpnp/tests/test_ndarray.py
- dpnp/tests/third_party/cupy/core_tests/test_ndarray_math.py
This PR improves documentations of `dpnp.ndarray` class, including:
- adding missing docstrings to the methods and attributes
- extending `ndarray.rst` page to have all methods and attributes rendered
- aligning signatures of the methods with numpy.ndarray class
- adding a page with dpnp constants
- updating a link with `dpnp.DLDeviceType` enum
Also `dpnp_array.py` was added to pylint scope.
> Update `dpnp.ndarray` docstrings

- dpnp/tests/test_manipulation.py
- dpnp/tests/third_party/cupy/core_tests/test_ndarray_copy_and_view.py
The PR enables previously muted test due to the [issue](https://github.com/IntelPython/dpctl/issues/2121) in dpctl.
> Enable muted test since dpctl-2121 is resolved

- CHANGELOG.md
- dpnp/fft/dpnp_utils_fft.py
In this PR, FFT module is updated to perform in-place FFT in intermediate steps of ND FFT which brings performance improvements for cases such as:
```python
import dpnp
shape = (30,40,50,60,70)
a = dpnp.random.rand(*shape) + 1j * dpnp.random.rand(*shape)
res = dpnp.fft.fftn(a)
%timeit res = dpnp.fft.fftn(a); res.sycl_queue.wait()
import dpnp
shape = (30,40,50,60,70)
a = dpnp.random.rand(*shape)
out = out=dpnp.empty((30, 40, 50, 60, 36), dtype=dpnp.complex128)
res = dpnp.fft.rfftn(a, out=out)
res is out
%timeit res = dpnp.fft.rfftn(a, out=out); res.sycl_queue.wait()
```
> Perform in-place FFT in intermediate steps of ND FFT

- CHANGELOG.md
- dpnp/backend/kernels/elementwise_functions/sinc.hpp
The PR proposes to reuse dpctl, since it exposes `sycl_complex.hpp` header which enables experimental SYCL namespace for complex types.
> Use dpctl tensor include to use experimental SYCL namespace for complex types

- dpnp/backend/extensions/lapack/getrf.cpp
- dpnp/backend/extensions/lapack/getrf_batch.cpp
- dpnp/backend/extensions/lapack/lapack_py.cpp
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/tests/test_linalg.py
- dpnp/tests/test_sycl_queue.py
- dpnp/tests/test_usm_type.py
This PR suggests adding `dpnp.linalg.lu_factor()` for 2D arrays similar to `scipy.linalg.lu_factor` 
Support for ND inputs will be added in the next phase.
In addition, this PR includes:
1. An updated implementation of `getrf` to support non-square matrices.
2. Refactoring of `_lu_factor()` by splitting the logic into separate functions to improve readability and maintainability.
> Implement `dpnp.linalg.lu_factor` 2D inputs

- CHANGELOG.md
- dpnp/__init__.py
This PR suggests small changes to Windows-specific logic in `__init__.py`
`hasattr(os, "add_dll_directory")` is unnecessary after platform check and is removed, and `sys.platform == "win32"` is used which is more commonly seen in the ecosystem and avoids importing `platform` module
> Adjust Windows-only logic in `__init__.py`

- CHANGELOG.md
- dpnp/linalg/dpnp_utils_linalg.py
- dpnp/tests/test_linalg.py
This PR suggests using oneMKL LAPACK `gesv` instead of `getrf` and `getrs` in `dpnp.linalg.solve()` since the issues in oneMKL have been resolved. This removes the workaround implemented in #1763
> Use oneMKL LAPACK `gesv` for `dpnp.linalg.solve()`

- .github/workflows/cron-run-tests.yaml
- .github/workflows/pre-commit-autoupdate.yml
There is no need to trigger workflows with `Autoupdate pre-commit` and `Run tests suite` on any change in branch protection rules. That trigger was intended only to `Scorecard supply-chain security` workflow.
Thus the PR removes that triggers.
> Remove workflow trigger on change in branch protection rules

- CHANGELOG.md
- dpnp/dpnp_utils/dpnp_algo_utils.pyx
- dpnp/tests/test_random_state.py
The PR updates `object to tuple` logic to align with NumPy and CuPy and to accept any `size` value passed to random function where each element is castable to `Py_ssize_t` type. Previously only `size` value with integer elements was acceptable.
The PR closes #2564.
> Allow `size` value where each element is castable to `Py_ssize_t`

- CHANGELOG.md
- dpnp/tests/test_mathematical.py
There is data type mismatch in result returned for the rounding functions, because numpy.ceil, numpy.floor, numpy.trunc, and numpy.fix always returns floating dtype for "numpy < 2.1.0".
The dpnp behavior is aligned with "numpy >= 2.1.0", so this PR adds a missing fixture to run the test depending on minimum required numpy version.
> Resolve tests failures in rounding functions with numpy 2.0

- .github/workflows/pre-commit-autoupdate.yml
- CHANGELOG.md
The PR adds missing permission definition for "Autoupdate pre-commit" workflow which impacts OpenSSF scope.
> Define token permissions in "Autoupdate pre-commit" workflow

- CHANGELOG.md
- CMakeLists.txt
The PR updates CMakeLists.txt to pull pybind11 `3.0.1` up from `2.13.6`.
> Use Pybind11 `3.0.1` to build dpnp

- .github/workflows/cron-run-tests.yaml
The PR installs missing pytest and scipy packages in the test environment of GitHub action `cron-run-tests.yaml`.
It resolves the issue introduced in #2583.
> Add installation of missing packages for python 3.13 in `cron-run-tests.yaml`

- dpnp/tests/test_linalg.py
This PR suggests adding `_make_nonsingular_np` and ``_make_nonsingular_nd_np functions to `TestLuFactor` and `TestLuFactorBatched` to ensure the generation of non-singular matrices and avoid warnings in test log
> Avoid generating singular matrices in TestLuFactor/TestLuFactorBatched

- environments/build_conda_pkg.yml
The PR updates `conda-build` version from `25.7.0` to `25.9.0`.
> Bump conda-build to `25.9.0` version

- CHANGELOG.md
- dpnp/__init__.py
- dpnp/backend/extensions/lapack/lapack_py.cpp
- dpnp/dpnp_iface.py
- dpnp/linalg/__init__.py
- dpnp/linalg/dpnp_iface_linalg.py
- dpnp/linalg/dpnp_utils_linalg.py
This PR backports of #2608 from development branch to `maintenance/0.19.x`.
> Backport gh-2608
